# generated by datamodel-codegen:
#   filename:  tmp0pcimec7.schema.json

from pydantic import BaseModel
from typing import Any, Dict, List


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Submit(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Close(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class View(BaseModel):
    id: str | None = None
    team_id: str | None = None
    type: str | None = None
    title: Title | None = None
    submit: Submit | None = None
    close: Close | None = None
    blocks: List[Any] | None = None
    private_metadata: str | None = None
    callback_id: str | None = None
    external_id: str | None = None
    state: Dict[str, Any] | None = None
    hash: str | None = None
    clear_on_close: bool | None = None
    notify_on_close: bool | None = None
    submit_disabled: bool | None = None
    root_view_id: str | None = None
    previous_view_id: str | None = None
    app_id: str | None = None
    app_installed_team_id: str | None = None
    bot_id: str | None = None


class AppHomeOpenedEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    channel: str | None = None
    tab: str | None = None
    event_ts: str | None = None
    view: View | None = None
