# generated by datamodel-codegen:
#   filename:  tmp5sz_txgz.schema.json

from pydantic import BaseModel
from typing import Any, List


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Edited(BaseModel):
    user: str | None = None
    ts: str | None = None


class AppMentionEvent(BaseModel):
    type: str | None = None
    client_msg_id: str | None = None
    user: str | None = None
    username: str | None = None
    bot_id: str | None = None
    bot_profile: BotProfile | None = None
    subtype: str | None = None
    text: str | None = None
    blocks: List[Any] | None = None
    attachments: List[Any] | None = None
    ts: str | None = None
    team: str | None = None
    channel: str | None = None
    edited: Edited | None = None
    event_ts: str | None = None
    thread_ts: str | None = None
