# generated by datamodel-codegen

from pydantic import BaseModel


class AppRateLimitedEvent(BaseModel):
    type: str | None = None
    token: str | None = None
    team_id: str | None = None
    minute_rate_limited: int | None = None
    api_app_id: str | None = None
