# generated by datamodel-codegen:
#   filename:  tmp1zkvura0.schema.json

from pydantic import BaseModel


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class Bot(BaseModel):
    id: str | None = None
    app_id: str | None = None
    name: str | None = None
    icons: Icons | None = None


class BotChangedEvent(BaseModel):
    type: str | None = None
    bot: Bot | None = None
