# generated by datamodel-codegen:
#   filename:  tmpqb70j48q.schema.json

from pydantic import BaseModel


class ChannelUnarchiveEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    user: str | None = None
    event_ts: str | None = None
