# generated by datamodel-codegen:
#   filename:  tmpn01046cz.schema.json

from pydantic import BaseModel


class ChannelDeletedEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    actor_id: str | None = None
    event_ts: str | None = None
