# generated by datamodel-codegen

from pydantic import BaseModel


class ChannelArchiveEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    user: str | None = None
    is_moved: int | None = None
    event_ts: str | None = None
