# generated by datamodel-codegen:
#   filename:  tmp12gi0vhm.schema.json

from pydantic import BaseModel


class ChannelLeftEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    actor_id: str | None = None
    event_ts: str | None = None
