# generated by datamodel-codegen:
#   filename:  tmpftouwz6a.schema.json

from pydantic import BaseModel


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    name_normalized: str | None = None
    is_channel: bool | None = None
    is_mpim: bool | None = None
    created: int | None = None


class ChannelRenameEvent(BaseModel):
    type: str | None = None
    channel: Channel | None = None
    event_ts: str | None = None
