# generated by datamodel-codegen:
#   filename:  tmpn5ojt4m5.schema.json

from pydantic import BaseModel


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    created: int | None = None
    creator: str | None = None


class ChannelJoinedEvent(BaseModel):
    type: str | None = None
    channel: Channel | None = None
