# generated by datamodel-codegen:
#   filename:  tmp7n5tkcg6.schema.json

from pydantic import BaseModel


class ChannelMarkedEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    ts: str | None = None
