# generated by datamodel-codegen:
#   filename:  tmpf2p17v6f.schema.json

from pydantic import BaseModel


class ChannelHistoryChangedEvent(BaseModel):
    type: str | None = None
    latest: str | None = None
    ts: str | None = None
    event_ts: str | None = None
