# generated by datamodel-codegen:
#   filename:  tmpq3jheocf.schema.json

from pydantic import BaseModel


class CommandsChangedEvent(BaseModel):
    type: str | None = None
    event_ts: str | None = None
