# generated by datamodel-codegen:
#   filename:  tmpp4jkna6u.schema.json

from pydantic import BaseModel


class EmailDomainChangedEvent(BaseModel):
    type: str | None = None
    email_domain: str | None = None
    event_ts: str | None = None
