# generated by datamodel-codegen:
#   filename:  tmpiinn4oe4.schema.json

from typing import List
from pydantic import BaseModel


class EmojiChangedEvent(BaseModel):
    type: str | None = None
    subtype: str | None = None
    names: List[str] | None = None
    name: str | None = None
    value: str | None = None
    old_name: str | None = None
    new_name: str | None = None
    event_ts: str | None = None
