# generated by datamodel-codegen

from pydantic import BaseModel


class Error(BaseModel):
    code: int | None = None
    msg: str | None = None


class ErrorEvent(BaseModel):
    type: str | None = None
    error: Error | None = None
