# generated by datamodel-codegen:
#   filename:  tmp11hcp0u3.schema.json

from pydantic import BaseModel


class Error(BaseModel):
    code: int | None = None
    msg: str | None = None


class ErrorEvent(BaseModel):
    type: str | None = None
    error: Error | None = None
