# generated by datamodel-codegen

from pydantic import BaseModel


class Team(BaseModel):
    id: str | None = None
    is_migrating: bool | None = None


class ExternalOrgMigrationFinishedEvent(BaseModel):
    type: str | None = None
    team: Team | None = None
    date_started: int | None = None
    date_finished: int | None = None
