# generated by datamodel-codegen:
#   filename:  tmpmnd7sxww.schema.json

from pydantic import BaseModel


class Team(BaseModel):
    id: str | None = None
    is_migrating: bool | None = None


class ExternalOrgMigrationStartedEvent(BaseModel):
    type: str | None = None
    team: Team | None = None
    date_started: int | None = None
