# generated by datamodel-codegen:
#   filename:  tmpl33s3y47.schema.json

from pydantic import BaseModel


class File(BaseModel):
    id: str | None = None


class FileCreatedEvent(BaseModel):
    type: str | None = None
    file_id: str | None = None
    file: File | None = None
    user_id: str | None = None
    event_ts: str | None = None
