# generated by datamodel-codegen:
#   filename:  tmpbll2rwhi.schema.json

from pydantic import BaseModel
from typing import Any, Dict


class File(BaseModel):
    id: str | None = None


class FileCommentEditedEvent(BaseModel):
    type: str | None = None
    comment: Dict[str, Any] | None = None
    file_id: str | None = None
    file: File | None = None
