# generated by datamodel-codegen:
#   filename:  tmpjp7okkm3.schema.json

from pydantic import BaseModel


class File(BaseModel):
    id: str | None = None


class FileSharedEvent(BaseModel):
    type: str | None = None
    file_id: str | None = None
    file: File | None = None
    channel_id: str | None = None
    user_id: str | None = None
    event_ts: str | None = None
