# generated by datamodel-codegen:
#   filename:  tmp6m9llong.schema.json

from pydantic import BaseModel


class File(BaseModel):
    id: str | None = None


class FilePublicEvent(BaseModel):
    type: str | None = None
    file_id: str | None = None
    file: File | None = None
    user_id: str | None = None
    event_ts: str | None = None
