# generated by datamodel-codegen:
#   filename:  tmpnm71lmq6.schema.json

from pydantic import BaseModel


class File(BaseModel):
    id: str | None = None


class FileChangeEvent(BaseModel):
    type: str | None = None
    file_id: str | None = None
    file: File | None = None
