# generated by datamodel-codegen

from pydantic import BaseModel


class File(BaseModel):
    id: str | None = None


class FileCommentDeletedEvent(BaseModel):
    type: str | None = None
    comment: str | None = None
    file_id: str | None = None
    file: File | None = None
