# generated by datamodel-codegen

from typing import Any, List
from pydantic import BaseModel


class FileDeletedEvent(BaseModel):
    type: str | None = None
    file_id: str | None = None
    channel_ids: List[Any] | None = None
    event_ts: str | None = None
