# generated by datamodel-codegen:
#   filename:  tmpbxu88r8f.schema.json

from pydantic import BaseModel


class GridMigrationStartedEvent(BaseModel):
    type: str | None = None
    enterprise_id: str | None = None
