# generated by datamodel-codegen:
#   filename:  tmprrigal53.schema.json

from pydantic import BaseModel


class GridMigrationFinishedEvent(BaseModel):
    type: str | None = None
    enterprise_id: str | None = None
