# generated by datamodel-codegen:
#   filename:  tmp9nal8nxw.schema.json

from pydantic import BaseModel


class GridMigrationStartedEvent(BaseModel):
    type: str | None = None
    enterprise_id: str | None = None
