# generated by datamodel-codegen

from pydantic import BaseModel


class GroupLeftEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    actor_id: str | None = None
    event_ts: str | None = None
