# generated by datamodel-codegen:
#   filename:  tmpj6i3ce93.schema.json

from typing import Any, Dict
from pydantic import BaseModel


class GroupJoinedEvent(BaseModel):
    type: str | None = None
    channel: Dict[str, Any] | None = None
