# generated by datamodel-codegen:
#   filename:  tmprk18tv44.schema.json

from pydantic import BaseModel


class GroupOpenEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    user: str | None = None
