# generated by datamodel-codegen:
#   filename:  tmp4r1p7eg9.schema.json

from pydantic import BaseModel


class GroupLeftEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    actor_id: str | None = None
    event_ts: str | None = None
