# generated by datamodel-codegen:
#   filename:  tmpv3k3u35o.schema.json

from pydantic import BaseModel


class GroupArchiveEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    user: str | None = None
    is_moved: int | None = None
    actor_id: str | None = None
    event_ts: str | None = None
