# generated by datamodel-codegen:
#   filename:  tmp0qcqu0ts.schema.json

from typing import Any, Dict
from pydantic import BaseModel


class GroupJoinedEvent(BaseModel):
    type: str | None = None
    channel: Dict[str, Any] | None = None
