# generated by datamodel-codegen:
#   filename:  tmpvhui3evr.schema.json

from pydantic import BaseModel


class GroupHistoryChangedEvent(BaseModel):
    type: str | None = None
    latest: str | None = None
    ts: str | None = None
    event_ts: str | None = None
