# generated by datamodel-codegen:
#   filename:  tmpbsbkldyn.schema.json

from pydantic import BaseModel


class GroupDeletedEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    date_deleted: int | None = None
    actor_id: str | None = None
    event_ts: str | None = None
