# generated by datamodel-codegen:
#   filename:  tmp6bfrz40g.schema.json

from pydantic import BaseModel


class GroupMarkedEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    ts: str | None = None
