# generated by datamodel-codegen:
#   filename:  tmpklnq1qte.schema.json

from pydantic import BaseModel


class GroupCloseEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    channel: str | None = None
