# generated by datamodel-codegen:
#   filename:  tmpdmj6_tgh.schema.json

from typing import Any, Dict
from pydantic import BaseModel


class ImCreatedEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    channel: Dict[str, Any] | None = None
