# generated by datamodel-codegen

from pydantic import BaseModel


class ImCloseEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    channel: str | None = None
    event_ts: str | None = None
