# generated by datamodel-codegen:
#   filename:  tmpx6qms4br.schema.json

from pydantic import BaseModel


class ImHistoryChangedEvent(BaseModel):
    type: str | None = None
    latest: str | None = None
    ts: str | None = None
    event_ts: str | None = None
