# generated by datamodel-codegen:
#   filename:  tmpqvli4wjn.schema.json

from pydantic import BaseModel


class ImMarkedEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    ts: str | None = None
