# generated by datamodel-codegen:
#   filename:  tmp2l21jtr5.schema.json

from pydantic import BaseModel


class ImOpenEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    user: str | None = None
    event_ts: str | None = None
