# generated by datamodel-codegen:
#   filename:  tmpt08fgqvv.schema.json

from pydantic import BaseModel
from typing import List


class Link(BaseModel):
    domain: str | None = None
    url: str | None = None


class LinkSharedEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    user: str | None = None
    message_ts: str | None = None
    thread_ts: str | None = None
    links: List[Link] | None = None
    is_bot_user_member: bool | None = None
    unfurl_id: str | None = None
    source: str | None = None
    event_ts: str | None = None
