# generated by datamodel-codegen:
#   filename:  tmpknxx9ss0.schema.json

from pydantic import BaseModel


class ManualPresenceChangeEvent(BaseModel):
    type: str | None = None
    presence: str | None = None
