# generated by datamodel-codegen:
#   filename:  tmpvbyc3y8j.schema.json

from pydantic import BaseModel


class ManualPresenceChangeEvent(BaseModel):
    type: str | None = None
    presence: str | None = None
