# generated by datamodel-codegen:
#   filename:  tmppprsaj6n.schema.json

from pydantic import BaseModel


class MemberJoinedChannelEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    channel: str | None = None
    channel_type: str | None = None
    team: str | None = None
    inviter: str | None = None
    event_ts: str | None = None
