# generated by datamodel-codegen:
#   filename:  tmp9qs7ha9y.schema.json

from pydantic import BaseModel


class MemberLeftChannelEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    channel: str | None = None
    channel_type: str | None = None
    team: str | None = None
    event_ts: str | None = None
