# generated by datamodel-codegen:
#   filename:  tmp7lrqp2pb.schema.json

from pydantic import BaseModel


class PrefChangeEvent(BaseModel):
    type: str | None = None
    name: str | None = None
    value: str | None = None
