# generated by datamodel-codegen:
#   filename:  tmpy9mpebn1.schema.json

from pydantic import BaseModel


class PrefChangeEvent(BaseModel):
    type: str | None = None
    name: str | None = None
    value: str | None = None
