# generated by datamodel-codegen:
#   filename:  tmp6mj73vdf.schema.json

from typing import List
from pydantic import BaseModel


class PresenceChangeEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    users: List[str] | None = None
    presence: str | None = None
