# generated by datamodel-codegen:
#   filename:  tmpyzrorbxn.schema.json

from pydantic import BaseModel


class Item(BaseModel):
    type: str | None = None
    channel: str | None = None
    ts: str | None = None
    file: str | None = None
    file_comment: str | None = None


class ReactionRemovedEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    reaction: str | None = None
    item_user: str | None = None
    item: Item | None = None
    event_ts: str | None = None
