# generated by datamodel-codegen:
#   filename:  tmp711miy7x.schema.json

from pydantic import BaseModel
from typing import List


class Grant(BaseModel):
    type: str | None = None
    resource_id: str | None = None


class Resource1(BaseModel):
    type: str | None = None
    grant: Grant | None = None


class Resource(BaseModel):
    resource: Resource1 | None = None
    scopes: List[str] | None = None


class ResourcesRemovedEvent(BaseModel):
    type: str | None = None
    resources: List[Resource] | None = None
