# generated by datamodel-codegen

from typing import List
from pydantic import BaseModel


class ScopeGrantedEvent(BaseModel):
    type: str | None = None
    scopes: List[str] | None = None
    trigger_id: str | None = None
