# generated by datamodel-codegen:
#   filename:  tmp7udux5rb.schema.json

from pydantic import BaseModel, Field
from typing import Any, Dict, List


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Text(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm1(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Deny(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm1 | None = None
    deny: Deny | None = None
    style: str | None = None


class CustomizableInputParameter(BaseModel):
    name: str | None = None
    value: str | None = None


class Trigger(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow(BaseModel):
    trigger: Trigger | None = None


class Element(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm | None = None
    accessibility_label: str | None = None
    workflow: Workflow | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None


class Block(BaseModel):
    type: str | None = None
    elements: List[Element] | None = None
    block_id: str | None = None


class FieldModel(BaseModel):
    title: str | None = None
    value: str | None = None
    short: bool | None = None


class Confirm2(BaseModel):
    title: str | None = None
    text: str | None = None
    ok_text: str | None = None
    dismiss_text: str | None = None


class Option(BaseModel):
    text: str | None = None
    value: str | None = None


class SelectedOption(BaseModel):
    text: str | None = None
    value: str | None = None


class OptionGroup(BaseModel):
    text: str | None = None
    options: List[Option] | None = None


class Action(BaseModel):
    id: str | None = None
    name: str | None = None
    text: str | None = None
    style: str | None = None
    type: str | None = None
    value: str | None = None
    confirm: Confirm2 | None = None
    options: List[Option] | None = None
    selected_options: List[SelectedOption] | None = None
    data_source: str | None = None
    min_query_length: int | None = None
    option_groups: List[OptionGroup] | None = None
    url: str | None = None


class Confirm4(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm3(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm4 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger1(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow1(BaseModel):
    trigger: Trigger1 | None = None


class Element1(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm3 | None = None
    accessibility_label: str | None = None
    workflow: Workflow1 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None


class Block1(BaseModel):
    type: str | None = None
    elements: List[Element1] | None = None
    block_id: str | None = None


class Confirm6(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm5(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm6 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger2(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow2(BaseModel):
    trigger: Trigger2 | None = None


class Element2(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm5 | None = None
    accessibility_label: str | None = None
    workflow: Workflow2 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None


class Block2(BaseModel):
    type: str | None = None
    elements: List[Element2] | None = None
    block_id: str | None = None


class BotProfile1(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Icons2(BaseModel):
    emoji: str | None = None
    image_36: str | None = None
    image_48: str | None = None
    image_64: str | None = None
    image_72: str | None = None


class Transcription(BaseModel):
    status: str | None = None
    locale: str | None = None


class Headers(BaseModel):
    date: str | None = None
    in_reply_to: str | None = None
    reply_to: str | None = None
    message_id: str | None = None


class MediaProgress(BaseModel):
    offset_ms: int | None = None
    max_offset_ms: int | None = None
    duration_ms: int | None = None


class Saved(BaseModel):
    is_archived: bool | None = None
    date_completed: int | None = None
    date_due: int | None = None
    state: str | None = None


class InitialComment(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    user: str | None = None
    comment: str | None = None
    channel: str | None = None
    is_intro: bool | None = None


class File(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    editors: List[Any] | None = None
    edit_timestamp: int | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    url_static_preview: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[Any] | None = None
    groups: List[Any] | None = None
    ims: List[Any] | None = None
    shares: Dict[str, Any] | None = None
    has_more_shares: bool | None = None
    to: List[Any] | None = None
    from_: List[Any] | None = Field(None, alias='from')
    cc: List[Any] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    quip_thread_id: str | None = None
    is_channel_space: bool | None = None
    linked_channel_id: str | None = None
    access: str | None = None
    teams_shared_with: List[Any] | None = None
    last_read: int | None = None
    title_blocks: List[Any] | None = None
    private_channels_with_file_access_count: int | None = None
    dm_mpdm_users_with_file_access: List[Any] | None = None
    org_or_workspace_access: str | None = None
    update_notification: int | None = None
    canvas_template_mode: str | None = None
    template_conversion_ts: int | None = None
    template_name: str | None = None
    template_title: str | None = None
    template_description: str | None = None
    template_icon: str | None = None
    team_pref_version_history_enabled: bool | None = None
    show_badge: bool | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[Any] | None = None
    reactions: List[Any] | None = None
    comments_count: int | None = None
    attachments: List[Any] | None = None
    blocks: List[Any] | None = None


class Comment(BaseModel):
    id: str | None = None
    name: str | None = None
    title: str | None = None
    created: str | None = None
    timestamp: str | None = None
    user: str | None = None
    username: str | None = None
    is_intro: bool | None = None
    is_public: bool | None = None
    is_starred: bool | None = None
    public_url_shared: bool | None = None
    url_private: str | None = None
    url_private_download: bool | None = None
    permalink: str | None = None
    permalink_public: bool | None = None
    edit_link: str | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    lines: int | None = None
    lines_more: int | None = None
    preview_is_truncated: bool | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    is_external: bool | None = None
    external_type: str | None = None
    editable: bool | None = None
    display_as_bot: bool | None = None
    size: int | None = None
    mode: str | None = None
    comment: str | None = None


class Edited(BaseModel):
    user: str | None = None
    ts: str | None = None


class Icons4(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile2(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons4 | None = None
    team_id: str | None = None


class Room(BaseModel):
    id: str | None = None
    name: str | None = None
    media_server: str | None = None
    created_by: str | None = None
    date_start: int | None = None
    date_end: int | None = None
    participants: List[Any] | None = None
    participant_history: List[Any] | None = None
    participants_camera_on: List[Any] | None = None
    participants_camera_off: List[Any] | None = None
    participants_screenshare_on: List[Any] | None = None
    participants_screenshare_off: List[Any] | None = None
    canvas_thread_ts: str | None = None
    thread_root_ts: str | None = None
    channels: List[Any] | None = None
    is_dm_call: bool | None = None
    was_rejected: bool | None = None
    was_missed: bool | None = None
    was_accepted: bool | None = None
    has_ended: bool | None = None
    background_id: str | None = None
    canvas_background: str | None = None
    is_prewarmed: bool | None = None
    is_scheduled: bool | None = None
    attached_file_ids: List[Any] | None = None
    media_backend_type: str | None = None
    display_id: str | None = None
    external_unique_id: str | None = None
    app_id: str | None = None
    call_family: str | None = None


class Root(BaseModel):
    text: str | None = None
    user: str | None = None
    parent_user_id: str | None = None
    username: str | None = None
    team: str | None = None
    bot_id: str | None = None
    mrkdwn: bool | None = None
    type: str | None = None
    subtype: str | None = None
    thread_ts: str | None = None
    icons: Icons2 | None = None
    bot_profile: BotProfile2 | None = None
    edited: Edited | None = None
    replies: List[Any] | None = None
    reply_count: int | None = None
    reply_users: List[Any] | None = None
    reply_users_count: int | None = None
    latest_reply: str | None = None
    subscribed: bool | None = None
    last_read: str | None = None
    unread_count: int | None = None
    ts: str | None = None
    room: Room | None = None
    no_notifications: bool | None = None


class Item1(BaseModel):
    id: str | None = None
    name: str | None = None
    title: str | None = None
    created: str | None = None
    timestamp: str | None = None
    user: str | None = None
    username: str | None = None
    is_intro: bool | None = None
    is_public: bool | None = None
    is_starred: bool | None = None
    public_url_shared: bool | None = None
    url_private: str | None = None
    url_private_download: bool | None = None
    permalink: str | None = None
    permalink_public: bool | None = None
    edit_link: str | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    lines: int | None = None
    lines_more: int | None = None
    preview_is_truncated: bool | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    is_external: bool | None = None
    external_type: str | None = None
    editable: bool | None = None
    display_as_bot: bool | None = None
    size: int | None = None
    mode: str | None = None
    comment: str | None = None


class Metadata(BaseModel):
    event_type: str | None = None


class Message1(BaseModel):
    type: str | None = None
    subtype: str | None = None
    team: str | None = None
    channel: str | None = None
    user: str | None = None
    username: str | None = None
    text: str | None = None
    blocks: List[Block2] | None = None
    attachments: List[Any] | None = None
    ts: str | None = None
    thread_ts: str | None = None
    is_intro: bool | None = None
    is_starred: bool | None = None
    wibblr: bool | None = None
    pinned_to: List[Any] | None = None
    reactions: List[Any] | None = None
    app_id: str | None = None
    bot_id: str | None = None
    bot_link: str | None = None
    display_as_bot: bool | None = None
    bot_profile: BotProfile1 | None = None
    icons: Icons2 | None = None
    file: File | None = None
    files: List[Any] | None = None
    upload: bool | None = None
    parent_user_id: str | None = None
    inviter: str | None = None
    client_msg_id: str | None = None
    comment: Comment | None = None
    topic: str | None = None
    purpose: str | None = None
    edited: Edited | None = None
    unfurl_links: bool | None = None
    unfurl_media: bool | None = None
    is_thread_broadcast: bool | None = None
    is_locked: bool | None = None
    replies: List[Any] | None = None
    reply_count: int | None = None
    reply_users: List[Any] | None = None
    reply_users_count: int | None = None
    latest_reply: str | None = None
    subscribed: bool | None = None
    x_files: List[Any] | None = None
    hidden: bool | None = None
    last_read: str | None = None
    root: Root | None = None
    item_type: str | None = None
    item: Item1 | None = None
    metadata: Metadata | None = None
    room: Room | None = None
    no_notifications: bool | None = None


class MessageBlock(BaseModel):
    team: str | None = None
    channel: str | None = None
    ts: str | None = None
    message: Message1 | None = None


class Subtitle(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Preview(BaseModel):
    type: str | None = None
    can_remove: bool | None = None
    title: Title | None = None
    subtitle: Subtitle | None = None
    icon_url: str | None = None


class C03E94MkuItem(BaseModel):
    share_user_id: str | None = None
    reply_users: List[str] | None = None
    reply_users_count: int | None = None
    reply_count: int | None = None
    ts: str | None = None
    thread_ts: str | None = None
    latest_reply: str | None = None
    channel_name: str | None = None
    team_id: str | None = None
    access: str | None = None
    source: str | None = None
    date_last_shared: int | None = None


class Public(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Private(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Shares(BaseModel):
    public: Public | None = None
    private: Private | None = None


class ToItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class FromItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class CcItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class Confirm8(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm7(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm8 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger3(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow3(BaseModel):
    trigger: Trigger3 | None = None


class Element3(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm7 | None = None
    accessibility_label: str | None = None
    workflow: Workflow3 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None


class TitleBlock(BaseModel):
    type: str | None = None
    elements: List[Element3] | None = None
    block_id: str | None = None


class DmMpdmUsersWithFileAcces(BaseModel):
    user_id: str | None = None
    access: str | None = None


class Reaction(BaseModel):
    name: str | None = None
    count: int | None = None
    users: List[str] | None = None
    url: str | None = None


class Confirm10(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm9(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm10 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger4(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow4(BaseModel):
    trigger: Trigger4 | None = None


class Element4(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm9 | None = None
    accessibility_label: str | None = None
    workflow: Workflow4 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None


class Block3(BaseModel):
    type: str | None = None
    elements: List[Element4] | None = None
    block_id: str | None = None


class File1(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    editors: List[str] | None = None
    edit_timestamp: int | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    url_static_preview: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    shares: Shares | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    quip_thread_id: str | None = None
    is_channel_space: bool | None = None
    linked_channel_id: str | None = None
    access: str | None = None
    teams_shared_with: List[Any] | None = None
    last_read: int | None = None
    title_blocks: List[TitleBlock] | None = None
    private_channels_with_file_access_count: int | None = None
    dm_mpdm_users_with_file_access: List[DmMpdmUsersWithFileAcces] | None = None
    org_or_workspace_access: str | None = None
    update_notification: int | None = None
    canvas_template_mode: str | None = None
    template_conversion_ts: int | None = None
    template_name: str | None = None
    template_title: str | None = None
    template_description: str | None = None
    template_icon: str | None = None
    team_pref_version_history_enabled: bool | None = None
    show_badge: bool | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction] | None = None
    comments_count: int | None = None
    attachments: List[Any] | None = None
    blocks: List[Block3] | None = None


class Metadata1(BaseModel):
    thumb_64: bool | None = None
    thumb_80: bool | None = None
    thumb_160: bool | None = None
    original_w: int | None = None
    original_h: int | None = None
    thumb_360_w: int | None = None
    thumb_360_h: int | None = None
    format: str | None = None
    extension: str | None = None
    rotation: int | None = None
    thumb_tiny: str | None = None


class Attachment(BaseModel):
    msg_subtype: str | None = None
    fallback: str | None = None
    callback_id: str | None = None
    color: str | None = None
    hide_color: bool | None = None
    pretext: str | None = None
    service_url: str | None = None
    service_name: str | None = None
    service_icon: str | None = None
    author_id: str | None = None
    author_name: str | None = None
    author_link: str | None = None
    author_icon: str | None = None
    from_url: str | None = None
    original_url: str | None = None
    author_subname: str | None = None
    channel_id: str | None = None
    channel_name: str | None = None
    channel_team: str | None = None
    id: int | None = None
    app_id: str | None = None
    bot_id: str | None = None
    indent: bool | None = None
    is_msg_unfurl: bool | None = None
    is_reply_unfurl: bool | None = None
    is_thread_root_unfurl: bool | None = None
    is_app_unfurl: bool | None = None
    app_unfurl_url: str | None = None
    title: str | None = None
    title_link: str | None = None
    text: str | None = None
    fields: List[FieldModel] | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    thumb_url: str | None = None
    thumb_width: int | None = None
    thumb_height: int | None = None
    video_url: str | None = None
    video_html: str | None = None
    video_html_width: int | None = None
    video_html_height: int | None = None
    footer: str | None = None
    footer_icon: str | None = None
    ts: str | None = None
    mrkdwn_in: List[str] | None = None
    actions: List[Action] | None = None
    blocks: List[Block1] | None = None
    message_blocks: List[MessageBlock] | None = None
    preview: Preview | None = None
    files: List[File1] | None = None
    filename: str | None = None
    size: int | None = None
    mimetype: str | None = None
    url: str | None = None
    metadata: Metadata1 | None = None
    is_file_attachment: bool | None = None


class Message(BaseModel):
    client_msg_id: str | None = None
    type: str | None = None
    app_id: str | None = None
    team: str | None = None
    user: str | None = None
    bot_id: str | None = None
    bot_profile: BotProfile | None = None
    text: str | None = None
    blocks: List[Block] | None = None
    attachments: List[Attachment] | None = None
    ts: str | None = None
    pinned_to: List[str] | None = None
    permalink: str | None = None
    edited: Edited | None = None


class File2(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    editors: List[Any] | None = None
    edit_timestamp: int | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    url_static_preview: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[Any] | None = None
    groups: List[Any] | None = None
    ims: List[Any] | None = None
    shares: Dict[str, Any] | None = None
    has_more_shares: bool | None = None
    to: List[Any] | None = None
    from_: List[Any] | None = Field(None, alias='from')
    cc: List[Any] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    quip_thread_id: str | None = None
    is_channel_space: bool | None = None
    linked_channel_id: str | None = None
    access: str | None = None
    teams_shared_with: List[Any] | None = None
    last_read: int | None = None
    title_blocks: List[Any] | None = None
    private_channels_with_file_access_count: int | None = None
    dm_mpdm_users_with_file_access: List[Any] | None = None
    org_or_workspace_access: str | None = None
    update_notification: int | None = None
    canvas_template_mode: str | None = None
    template_conversion_ts: int | None = None
    template_name: str | None = None
    template_title: str | None = None
    template_description: str | None = None
    template_icon: str | None = None
    team_pref_version_history_enabled: bool | None = None
    show_badge: bool | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[Any] | None = None
    reactions: List[Any] | None = None
    comments_count: int | None = None
    attachments: List[Any] | None = None
    blocks: List[Any] | None = None


class Comment1(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    user: str | None = None
    comment: str | None = None
    channel: str | None = None
    is_intro: bool | None = None


class Item(BaseModel):
    type: str | None = None
    channel: str | None = None
    created_by: str | None = None
    date_create: int | None = None
    message: Message | None = None
    file: File2 | None = None
    comment: Comment1 | None = None


class StarRemovedEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    item: Item | None = None
    event_ts: str | None = None
