# generated by datamodel-codegen

from pydantic import BaseModel


class SubteamSelfRemovedEvent(BaseModel):
    type: str | None = None
    subteam_id: str | None = None
    event_ts: str | None = None
