# generated by datamodel-codegen:
#   filename:  tmpwqud9bxu.schema.json

from pydantic import BaseModel


class SubteamSelfAddedEvent(BaseModel):
    type: str | None = None
    subteam_id: str | None = None
    event_ts: str | None = None
