# generated by datamodel-codegen:
#   filename:  tmpi7idl0i0.schema.json

from pydantic import BaseModel


class SubteamSelfRemovedEvent(BaseModel):
    type: str | None = None
    subteam_id: str | None = None
    event_ts: str | None = None
