# generated by datamodel-codegen:
#   filename:  tmpd0ax_5ep.schema.json

from pydantic import BaseModel


class TeamDomainChangeEvent(BaseModel):
    type: str | None = None
    url: str | None = None
    domain: str | None = None
