# generated by datamodel-codegen:
#   filename:  tmpd_vnsk7l.schema.json

from pydantic import BaseModel


class TeamDomainChangeEvent(BaseModel):
    type: str | None = None
    url: str | None = None
    domain: str | None = None
