# generated by datamodel-codegen

from pydantic import BaseModel
from typing import List


class Field(BaseModel):
    id: str | None = None
    ordering: int | None = None


class Profile(BaseModel):
    fields: List[Field] | None = None


class TeamProfileReorderEvent(BaseModel):
    type: str | None = None
    profile: Profile | None = None
