# generated by datamodel-codegen:
#   filename:  tmp8nodrirp.schema.json

from pydantic import BaseModel


class TeamPrefChangeEvent(BaseModel):
    type: str | None = None
    name: str | None = None
    value: str | None = None
