# generated by datamodel-codegen:
#   filename:  tmpqi9d5eiz.schema.json

from pydantic import BaseModel
from typing import List


class Field(BaseModel):
    id: str | None = None


class Profile(BaseModel):
    fields: List[Field] | None = None


class TeamProfileDeleteEvent(BaseModel):
    type: str | None = None
    profile: Profile | None = None
