# generated by datamodel-codegen:
#   filename:  tmp3o9b3ygc.schema.json

from pydantic import BaseModel
from typing import List


class Field(BaseModel):
    id: str | None = None


class Profile(BaseModel):
    fields: List[Field] | None = None


class TeamProfileChangeEvent(BaseModel):
    type: str | None = None
    profile: Profile | None = None
