# generated by datamodel-codegen:
#   filename:  tmptpuxbwl8.schema.json

from typing import List
from pydantic import BaseModel


class TeamPlanChangeEvent(BaseModel):
    type: str | None = None
    plan: str | None = None
    can_add_ura: bool | None = None
    paid_features: List[str] | None = None
