# generated by datamodel-codegen

from typing import List
from pydantic import BaseModel


class Tokens(BaseModel):
    oauth: List[str] | None = None
    bot: List[str] | None = None


class TokensRevokedEvent(BaseModel):
    type: str | None = None
    tokens: Tokens | None = None
