# generated by datamodel-codegen:
#   filename:  tmphcgty01c.schema.json

from typing import List
from pydantic import BaseModel


class Tokens(BaseModel):
    oauth: List[str] | None = None
    bot: List[str] | None = None


class TokensRevokedEvent(BaseModel):
    type: str | None = None
    tokens: Tokens | None = None
