# generated by datamodel-codegen:
#   filename:  tmpnw85vgrs.schema.json

from pydantic import BaseModel


class UserTypingEvent(BaseModel):
    type: str | None = None
    channel: str | None = None
    user: str | None = None
