# generated by datamodel-codegen:
#   filename:  tmp0zynws6h.schema.json

from typing import List
from pydantic import BaseModel


class UserResourceDeniedEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    scopes: List[str] | None = None
    trigger_id: str | None = None
