# generated by datamodel-codegen

from pydantic import BaseModel


class UserResourceRemovedEvent(BaseModel):
    type: str | None = None
    user: str | None = None
    trigger_id: str | None = None
