# generated by datamodel-codegen:
#   filename:  tmpibzcyrbd.schema.json

from pydantic import BaseModel
from typing import List


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Text(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm1(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Deny(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm1 | None = None
    deny: Deny | None = None
    style: str | None = None


class Placeholder(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Filter(BaseModel):
    include: List[str] | None = None
    exclude_external_shared_channels: bool | None = None
    exclude_bot_users: bool | None = None


class Description(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class InitialOption(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class SlackFile(BaseModel):
    id: str | None = None
    url: str | None = None


class Element(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm | None = None
    accessibility_label: str | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    focus_on_load: bool | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_date: str | None = None
    initial_option: InitialOption | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None
    initial_user: str | None = None


class Field(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None
    verbatim: bool | None = None


class Accessory(BaseModel):
    type: str | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class Block(BaseModel):
    type: str | None = None
    elements: List[Element] | None = None
    block_id: str | None = None
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    is_animated: bool | None = None
    slack_file: SlackFile | None = None
    alt_text: str | None = None
    title: Title | None = None
    text: Text | None = None
    fields: List[Field] | None = None
    accessory: Accessory | None = None


class UserProfile(BaseModel):
    name: str | None = None
    first_name: str | None = None
    real_name: str | None = None
    display_name: str | None = None
    team: str | None = None
    is_restricted: bool | None = None
    is_ultra_restricted: bool | None = None
    avatar_hash: str | None = None
    image_72: str | None = None


class Edited(BaseModel):
    user: str | None = None
    ts: str | None = None


class Event(BaseModel):
    type: str | None = None
    client_msg_id: str | None = None
    user: str | None = None
    username: str | None = None
    app_id: str | None = None
    bot_id: str | None = None
    bot_profile: BotProfile | None = None
    subtype: str | None = None
    text: str | None = None
    blocks: List[Block] | None = None
    upload: bool | None = None
    display_as_bot: bool | None = None
    ts: str | None = None
    team: str | None = None
    channel: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    user_profile: UserProfile | None = None
    edited: Edited | None = None
    event_ts: str | None = None
    thread_ts: str | None = None


class AppMentionPayload(BaseModel):
    token: str | None = None
    enterprise_id: str | None = None
    team_id: str | None = None
    api_app_id: str | None = None
    type: str | None = None
    authed_users: List[str] | None = None
    authed_teams: List[str] | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_id: str | None = None
    event_time: int | None = None
    event_context: str | None = None
    event: Event | None = None
