# generated by datamodel-codegen:
#   filename:  tmpe0z6bxz9.schema.json

from pydantic import BaseModel
from typing import Any, Dict, List


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Submit(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Close(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class View(BaseModel):
    id: str | None = None
    team_id: str | None = None
    type: str | None = None
    title: Title | None = None
    submit: Submit | None = None
    close: Close | None = None
    private_metadata: str | None = None
    callback_id: str | None = None
    external_id: str | None = None
    state: Dict[str, Any] | None = None
    hash: str | None = None
    clear_on_close: bool | None = None
    notify_on_close: bool | None = None
    submit_disabled: bool | None = None
    root_view_id: str | None = None
    previous_view_id: str | None = None
    app_id: str | None = None
    app_installed_team_id: str | None = None
    bot_id: str | None = None


class Event(BaseModel):
    type: str | None = None
    user: str | None = None
    channel: str | None = None
    tab: str | None = None
    event_ts: str | None = None
    view: View | None = None


class AppHomeOpenedPayload(BaseModel):
    token: str | None = None
    enterprise_id: str | None = None
    team_id: str | None = None
    api_app_id: str | None = None
    type: str | None = None
    authed_users: List[str] | None = None
    authed_teams: List[str] | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_id: str | None = None
    event_time: int | None = None
    event_context: str | None = None
    event: Event | None = None
