# generated by datamodel-codegen:
#   filename:  tmpuw364bok.schema.json

from pydantic import BaseModel
from typing import List


class Channel(BaseModel):
    id: str | None = None
    is_channel: bool | None = None
    is_mpim: bool | None = None
    name: str | None = None
    name_normalized: str | None = None
    created: int | None = None


class Event(BaseModel):
    type: str | None = None
    channel: Channel | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class ChannelRenamePayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
