# generated by datamodel-codegen:
#   filename:  tmpl5gamhu2.schema.json

from pydantic import BaseModel
from typing import List


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Channel(BaseModel):
    id: str | None = None
    is_channel: bool | None = None
    name: str | None = None
    name_normalized: str | None = None
    created: int | None = None
    creator: str | None = None
    is_shared: bool | None = None
    is_org_shared: bool | None = None
    context_team_id: str | None = None
    is_group: bool | None = None
    is_im: bool | None = None
    is_mpim: bool | None = None
    is_private: bool | None = None
    is_archived: bool | None = None
    is_general: bool | None = None
    unlinked: int | None = None
    is_pending_ext_shared: bool | None = None
    pending_shared: List[str] | None = None
    updated: int | None = None
    is_moved: int | None = None
    is_ext_shared: bool | None = None
    shared_team_ids: List[str] | None = None
    internal_team_ids: List[str] | None = None
    pending_connected_team_ids: List[str] | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    previous_names: List[str] | None = None


class Event(BaseModel):
    type: str | None = None
    channel: Channel | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class ChannelCreatedPayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
