# generated by datamodel-codegen:
#   filename:  tmpv77g46i_.schema.json

from pydantic import BaseModel
from typing import List


class DndStatus(BaseModel):
    dnd_enabled: bool | None = None
    next_dnd_start_ts: int | None = None
    next_dnd_end_ts: int | None = None


class Event(BaseModel):
    type: str | None = None
    user: str | None = None
    dnd_status: DndStatus | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class DndUpdatedUserPayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
