# generated by datamodel-codegen:
#   filename:  tmpla43kwiv.schema.json

from pydantic import BaseModel
from typing import List


class File(BaseModel):
    id: str | None = None


class Event(BaseModel):
    file_id: str | None = None
    user_id: str | None = None
    file: File | None = None
    type: str | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class FileCreatedPayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
