# generated by datamodel-codegen:
#   filename:  tmp9dojzl22.schema.json

from pydantic import BaseModel
from typing import List


class Event(BaseModel):
    type: str | None = None
    channel: str | None = None
    actor_id: str | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class GroupUnarchivePayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
