# generated by datamodel-codegen:
#   filename:  tmpi7ode8vz.schema.json

from pydantic import BaseModel
from typing import List


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class Link(BaseModel):
    domain: str | None = None
    url: str | None = None


class Event(BaseModel):
    type: str | None = None
    channel: str | None = None
    user: str | None = None
    message_ts: str | None = None
    thread_ts: str | None = None
    links: List[Link] | None = None
    is_bot_user_member: bool | None = None
    unfurl_id: str | None = None
    source: str | None = None
    event_ts: str | None = None


class LinkSharedPayload(BaseModel):
    token: str | None = None
    enterprise_id: str | None = None
    team_id: str | None = None
    api_app_id: str | None = None
    type: str | None = None
    authed_users: List[str] | None = None
    authed_teams: List[str] | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_id: str | None = None
    event_time: int | None = None
    event_context: str | None = None
    event: Event | None = None
