# generated by datamodel-codegen:
#   filename:  tmpjtmsdlex.schema.json

from pydantic import BaseModel
from typing import Any, Dict, List


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Edited(BaseModel):
    user: str | None = None
    ts: str | None = None


class Text(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm1(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Deny(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm1 | None = None
    deny: Deny | None = None
    style: str | None = None


class Placeholder(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Filter(BaseModel):
    include: List[str] | None = None
    exclude_external_shared_channels: bool | None = None
    exclude_bot_users: bool | None = None


class Description(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class InitialOption(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class SlackFile(BaseModel):
    id: str | None = None
    url: str | None = None


class Element(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm | None = None
    accessibility_label: str | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    focus_on_load: bool | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_date: str | None = None
    initial_option: InitialOption | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None
    initial_user: str | None = None


class Field(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None
    verbatim: bool | None = None


class Accessory(BaseModel):
    type: str | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class Block(BaseModel):
    type: str | None = None
    elements: List[Element] | None = None
    block_id: str | None = None
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    is_animated: bool | None = None
    slack_file: SlackFile | None = None
    alt_text: str | None = None
    title: Title | None = None
    text: Text | None = None
    fields: List[Field] | None = None
    accessory: Accessory | None = None


class Field1(BaseModel):
    title: str | None = None
    value: str | None = None
    short: bool | None = None


class Confirm2(BaseModel):
    title: str | None = None
    text: str | None = None
    ok_text: str | None = None
    dismiss_text: str | None = None


class Action(BaseModel):
    id: str | None = None
    name: str | None = None
    text: str | None = None
    style: str | None = None
    type: str | None = None
    value: str | None = None
    confirm: Confirm2 | None = None
    options: List[Any] | None = None
    selected_options: List[Any] | None = None
    data_source: str | None = None
    min_query_length: int | None = None
    url: str | None = None


class Subtitle(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Preview(BaseModel):
    type: str | None = None
    can_remove: bool | None = None
    title: Title | None = None
    subtitle: Subtitle | None = None
    icon_url: str | None = None


class Record(BaseModel):
    record_id: str | None = None


class ListRecord(BaseModel):
    record: Record | None = None


class CreationSource(BaseModel):
    type: str | None = None
    reference_id: str | None = None
    workflow_function_id: str | None = None


class ListMetadata(BaseModel):
    icon: str | None = None
    icon_url: str | None = None
    icon_team_id: str | None = None
    description: str | None = None
    is_trial: bool | None = None
    creation_source: CreationSource | None = None


class ListLimits(BaseModel):
    over_row_maximum: bool | None = None
    row_count_limit: int | None = None
    row_count: int | None = None
    over_column_maximum: bool | None = None
    column_count: int | None = None
    column_count_limit: int | None = None
    over_view_maximum: bool | None = None
    view_count: int | None = None
    view_count_limit: int | None = None
    max_attachments_per_cell: int | None = None


class ListModel(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    external_type: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    editable: bool | None = None
    size: int | None = None
    mode: str | None = None
    is_external: bool | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    username: str | None = None
    list_metadata: ListMetadata | None = None
    list_limits: ListLimits | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    comments_count: int | None = None
    shares: Dict[str, Any] | None = None
    has_more_shares: bool | None = None
    private_channels_with_file_access_count: int | None = None
    private_file_with_access_count: int | None = None
    has_rich_preview: bool | None = None
    file_access: str | None = None


class Grouping(BaseModel):
    group_by: str | None = None
    group_by_column_id: str | None = None


class ListView(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None
    is_locked: bool | None = None
    position: str | None = None
    date_created: int | None = None
    created_by: str | None = None
    stick_column_left: bool | None = None
    is_all_items_view: bool | None = None
    default_view_key: str | None = None
    show_completed_items: bool | None = None
    grouping: Grouping | None = None


class Metadata(BaseModel):
    thumb_64: bool | None = None
    thumb_80: bool | None = None
    thumb_160: bool | None = None
    original_w: int | None = None
    original_h: int | None = None
    thumb_360_w: int | None = None
    thumb_360_h: int | None = None
    format: str | None = None
    extension: str | None = None
    rotation: int | None = None
    thumb_tiny: str | None = None


class Attachment(BaseModel):
    msg_subtype: str | None = None
    fallback: str | None = None
    callback_id: str | None = None
    color: str | None = None
    hide_color: bool | None = None
    pretext: str | None = None
    service_url: str | None = None
    service_name: str | None = None
    service_icon: str | None = None
    author_id: str | None = None
    author_name: str | None = None
    author_link: str | None = None
    author_icon: str | None = None
    from_url: str | None = None
    original_url: str | None = None
    author_subname: str | None = None
    channel_id: str | None = None
    channel_name: str | None = None
    channel_team: str | None = None
    id: int | None = None
    app_id: str | None = None
    bot_id: str | None = None
    indent: bool | None = None
    is_msg_unfurl: bool | None = None
    is_reply_unfurl: bool | None = None
    is_thread_root_unfurl: bool | None = None
    is_app_unfurl: bool | None = None
    app_unfurl_url: str | None = None
    title: str | None = None
    title_link: str | None = None
    text: str | None = None
    fields: List[Field1] | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    thumb_url: str | None = None
    thumb_width: int | None = None
    thumb_height: int | None = None
    video_url: str | None = None
    video_html: str | None = None
    video_html_width: float | None = None
    video_html_height: float | None = None
    footer: str | None = None
    footer_icon: str | None = None
    ts: str | None = None
    mrkdwn_in: List[str] | None = None
    actions: List[Action] | None = None
    preview: Preview | None = None
    file_id: str | None = None
    list_record_id: str | None = None
    list_record: ListRecord | None = None
    hide_border: bool | None = None
    list_view_id: str | None = None
    list: ListModel | None = None
    list_view: ListView | None = None
    filename: str | None = None
    size: int | None = None
    mimetype: str | None = None
    url: str | None = None
    metadata: Metadata | None = None
    is_file_attachment: bool | None = None


class Message(BaseModel):
    client_msg_id: str | None = None
    type: str | None = None
    subtype: str | None = None
    user: str | None = None
    team: str | None = None
    bot_id: str | None = None
    bot_profile: BotProfile | None = None
    edited: Edited | None = None
    text: str | None = None
    blocks: List[Block] | None = None
    attachments: List[Attachment] | None = None
    upload: bool | None = None
    display_as_bot: bool | None = None
    thread_ts: str | None = None
    parent_user_id: str | None = None
    hidden: bool | None = None
    is_locked: bool | None = None
    subscribed: bool | None = None
    ts: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    is_starred: bool | None = None
    reply_count: int | None = None
    reply_users_count: int | None = None
    latest_reply: str | None = None
    last_read: str | None = None


class BotProfile1(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Confirm4(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm3(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm4 | None = None
    deny: Deny | None = None
    style: str | None = None


class InitialOption1(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Element1(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm3 | None = None
    accessibility_label: str | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    focus_on_load: bool | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_date: str | None = None
    initial_option: InitialOption1 | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None
    initial_user: str | None = None


class Field2(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None
    verbatim: bool | None = None


class Accessory1(BaseModel):
    type: str | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class Block1(BaseModel):
    type: str | None = None
    elements: List[Element1] | None = None
    block_id: str | None = None
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    is_animated: bool | None = None
    slack_file: SlackFile | None = None
    alt_text: str | None = None
    title: Title | None = None
    text: Text | None = None
    fields: List[Field2] | None = None
    accessory: Accessory1 | None = None


class Field3(BaseModel):
    title: str | None = None
    value: str | None = None
    short: bool | None = None


class Confirm5(BaseModel):
    title: str | None = None
    text: str | None = None
    ok_text: str | None = None
    dismiss_text: str | None = None


class Action1(BaseModel):
    id: str | None = None
    name: str | None = None
    text: str | None = None
    style: str | None = None
    type: str | None = None
    value: str | None = None
    confirm: Confirm5 | None = None
    options: List[Any] | None = None
    selected_options: List[Any] | None = None
    data_source: str | None = None
    min_query_length: int | None = None
    url: str | None = None


class Preview1(BaseModel):
    type: str | None = None
    can_remove: bool | None = None
    title: Title | None = None
    subtitle: Subtitle | None = None
    icon_url: str | None = None


class ListRecord1(BaseModel):
    record: Record | None = None


class ListMetadata1(BaseModel):
    icon: str | None = None
    icon_url: str | None = None
    icon_team_id: str | None = None
    description: str | None = None
    is_trial: bool | None = None
    creation_source: CreationSource | None = None


class List1(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    external_type: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    editable: bool | None = None
    size: int | None = None
    mode: str | None = None
    is_external: bool | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    username: str | None = None
    list_metadata: ListMetadata1 | None = None
    list_limits: ListLimits | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    comments_count: int | None = None
    shares: Dict[str, Any] | None = None
    has_more_shares: bool | None = None
    private_channels_with_file_access_count: int | None = None
    private_file_with_access_count: int | None = None
    has_rich_preview: bool | None = None
    file_access: str | None = None


class ListView1(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None
    is_locked: bool | None = None
    position: str | None = None
    date_created: int | None = None
    created_by: str | None = None
    stick_column_left: bool | None = None
    is_all_items_view: bool | None = None
    default_view_key: str | None = None
    show_completed_items: bool | None = None
    grouping: Grouping | None = None


class Attachment1(BaseModel):
    msg_subtype: str | None = None
    fallback: str | None = None
    callback_id: str | None = None
    color: str | None = None
    hide_color: bool | None = None
    pretext: str | None = None
    service_url: str | None = None
    service_name: str | None = None
    service_icon: str | None = None
    author_id: str | None = None
    author_name: str | None = None
    author_link: str | None = None
    author_icon: str | None = None
    from_url: str | None = None
    original_url: str | None = None
    author_subname: str | None = None
    channel_id: str | None = None
    channel_name: str | None = None
    channel_team: str | None = None
    id: int | None = None
    app_id: str | None = None
    bot_id: str | None = None
    indent: bool | None = None
    is_msg_unfurl: bool | None = None
    is_reply_unfurl: bool | None = None
    is_thread_root_unfurl: bool | None = None
    is_app_unfurl: bool | None = None
    app_unfurl_url: str | None = None
    title: str | None = None
    title_link: str | None = None
    text: str | None = None
    fields: List[Field3] | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    thumb_url: str | None = None
    thumb_width: int | None = None
    thumb_height: int | None = None
    video_url: str | None = None
    video_html: str | None = None
    video_html_width: float | None = None
    video_html_height: float | None = None
    footer: str | None = None
    footer_icon: str | None = None
    ts: str | None = None
    mrkdwn_in: List[str] | None = None
    actions: List[Action1] | None = None
    preview: Preview1 | None = None
    file_id: str | None = None
    list_record_id: str | None = None
    list_record: ListRecord1 | None = None
    hide_border: bool | None = None
    list_view_id: str | None = None
    list: List1 | None = None
    list_view: ListView1 | None = None
    filename: str | None = None
    size: int | None = None
    mimetype: str | None = None
    url: str | None = None
    metadata: Metadata | None = None
    is_file_attachment: bool | None = None


class PreviousMessage(BaseModel):
    client_msg_id: str | None = None
    type: str | None = None
    subtype: str | None = None
    user: str | None = None
    team: str | None = None
    bot_id: str | None = None
    bot_profile: BotProfile1 | None = None
    edited: Edited | None = None
    text: str | None = None
    blocks: List[Block1] | None = None
    attachments: List[Attachment1] | None = None
    upload: bool | None = None
    display_as_bot: bool | None = None
    thread_ts: str | None = None
    parent_user_id: str | None = None
    hidden: bool | None = None
    is_locked: bool | None = None
    subscribed: bool | None = None
    ts: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    is_starred: bool | None = None
    reply_count: int | None = None
    reply_users_count: int | None = None
    latest_reply: str | None = None
    last_read: str | None = None


class Event(BaseModel):
    type: str | None = None
    subtype: str | None = None
    channel: str | None = None
    hidden: bool | None = None
    message: Message | None = None
    previous_message: PreviousMessage | None = None
    event_ts: str | None = None
    ts: str | None = None
    channel_type: str | None = None


class MessageChangedPayload(BaseModel):
    token: str | None = None
    enterprise_id: str | None = None
    team_id: str | None = None
    api_app_id: str | None = None
    type: str | None = None
    authed_users: List[str] | None = None
    authed_teams: List[str] | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_id: str | None = None
    event_time: int | None = None
    event_context: str | None = None
    event: Event | None = None
