# generated by datamodel-codegen:
#   filename:  tmppggo1mnm.schema.json

from pydantic import BaseModel
from typing import List


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class Event(BaseModel):
    type: str | None = None
    subtype: str | None = None
    channel: str | None = None
    username: str | None = None
    user: str | None = None
    bot_id: str | None = None
    text: str | None = None
    event_ts: str | None = None
    ts: str | None = None
    channel_type: str | None = None


class MessageMePayload(BaseModel):
    token: str | None = None
    enterprise_id: str | None = None
    team_id: str | None = None
    api_app_id: str | None = None
    type: str | None = None
    authed_users: List[str] | None = None
    authed_teams: List[str] | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_id: str | None = None
    event_time: int | None = None
    event_context: str | None = None
    event: Event | None = None
