# generated by datamodel-codegen:
#   filename:  tmplac6as5c.schema.json

from pydantic import BaseModel
from typing import List


class Item(BaseModel):
    type: str | None = None
    channel: str | None = None
    ts: str | None = None


class Event(BaseModel):
    type: str | None = None
    user: str | None = None
    item: Item | None = None
    reaction: str | None = None
    item_user: str | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class ReactionRemovedPayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
    context_team_id: str | None = None
    context_enterprise_id: str | None = None
