# generated by datamodel-codegen:
#   filename:  tmp6ycv491s.schema.json

from pydantic import BaseModel
from typing import List


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Message(BaseModel):
    bot_id: str | None = None
    type: str | None = None
    text: str | None = None
    user: str | None = None
    ts: str | None = None
    app_id: str | None = None
    team: str | None = None
    bot_profile: BotProfile | None = None
    permalink: str | None = None


class Item(BaseModel):
    type: str | None = None
    channel: str | None = None
    message: Message | None = None
    date_create: int | None = None


class Event(BaseModel):
    type: str | None = None
    user: str | None = None
    item: Item | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class StarRemovedPayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
