# generated by datamodel-codegen:
#   filename:  tmpgobae_do.schema.json

from typing import List
from pydantic import BaseModel


class Event(BaseModel):
    type: str | None = None
    subteam_id: str | None = None
    team_id: str | None = None
    date_previous_update: int | None = None
    date_update: int | None = None
    added_users: List[str] | None = None
    added_users_count: int | None = None
    removed_users: List[str] | None = None
    removed_users_count: int | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class SubteamMembersChangedPayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
