# generated by datamodel-codegen:
#   filename:  tmp63_jadca.schema.json

from typing import List
from pydantic import BaseModel


class Prefs(BaseModel):
    channels: List[str] | None = None
    groups: List[str] | None = None


class Subteam(BaseModel):
    id: str | None = None
    team_id: str | None = None
    is_usergroup: bool | None = None
    is_subteam: bool | None = None
    name: str | None = None
    description: str | None = None
    handle: str | None = None
    is_external: bool | None = None
    date_create: int | None = None
    date_update: int | None = None
    date_delete: int | None = None
    auto_provision: bool | None = None
    enterprise_subteam_id: str | None = None
    created_by: str | None = None
    updated_by: str | None = None
    prefs: Prefs | None = None
    users: List[str] | None = None
    user_count: int | None = None
    channel_count: int | None = None
    deleted_by: str | None = None
    is_section: bool | None = None


class Event(BaseModel):
    type: str | None = None
    subteam: Subteam | None = None
    event_ts: str | None = None


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class SubteamUpdatedPayload(BaseModel):
    token: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    api_app_id: str | None = None
    event: Event | None = None
    type: str | None = None
    event_id: str | None = None
    event_time: int | None = None
    authorizations: List[Authorization] | None = None
    is_ext_shared_channel: bool | None = None
    event_context: str | None = None
