# generated by datamodel-codegen:
#   filename:  tmp4u6stmd3.schema.json

from pydantic import BaseModel


class AdminConversationsArchiveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
