# generated by datamodel-codegen:
#   filename:  tmpy9mco411.schema.json

from pydantic import BaseModel


class AdminTeamsSettingsSetDescriptionResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
