# generated by datamodel-codegen:
#   filename:  tmp3231itjk.schema.json

from typing import Any, Dict, List
from pydantic import BaseModel, Field


class Config(BaseModel):
    name: str | None = None
    description: str | None = None
    schema_: Dict[str, Any] | None = Field(None, alias='schema')
    event_type: str | None = None


class TripInformation(BaseModel):
    user_id: str | None = None
    channel_id: str | None = None
    reaction: str | None = None
    message_ts: str | None = None
    list_id: str | None = None


class Trigger(BaseModel):
    id: str | None = None
    type: str | None = None
    config: Config | None = None
    trip_information: TripInformation | None = None


class Outputs(BaseModel):
    channel_id: str | None = None
    message_ts: str | None = None


class Payload(BaseModel):
    exec_outcome: str | None = None
    workflow_name: str | None = None
    function_name: str | None = None
    function_type: str | None = None
    function_id: str | None = None
    function_execution_id: str | None = None
    total_steps: int | None = None
    current_step: int | None = None
    actor: str | None = None
    error: str | None = None
    log: str | None = None
    type: str | None = None
    billing_reason: List[str] | None = None
    is_billing_excluded: bool | None = None
    trigger: Trigger | None = None
    channel_id: str | None = None
    bot_user_id: str | None = None
    inputs: Dict[str, Any] | None = None
    details: str | None = None
    request_type: str | None = None
    datastore_name: str | None = None
    action: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    bundle_size_kb: int | None = None
    outputs: Outputs | None = None
    code: str | None = None
    app_id: str | None = None


class Activity(BaseModel):
    app_id: str | None = None
    level: str | None = None
    event_type: str | None = None
    source: str | None = None
    component_type: str | None = None
    component_id: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    payload: Payload | None = None
    created: int | None = None
    trace_id: str | None = None
    parent_execution_id: str | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class AdminAppsActivitiesListResponse(BaseModel):
    ok: bool | None = None
    activities: List[Activity] | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
