# generated by datamodel-codegen:
#   filename:  tmp73m3e6w3.schema.json

from pydantic import BaseModel


class AdminBarriersDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
