# generated by datamodel-codegen:
#   filename:  tmpbe3p2bf3.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class AdminTeamsSettingsSetDefaultChannelsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
