# generated by datamodel-codegen:
#   filename:  tmp5pn3so1i.schema.json

from pydantic import BaseModel


class AdminUsersSessionResetBulkResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
