# generated by datamodel-codegen:
#   filename:  tmpwrt95sfd.schema.json

from pydantic import BaseModel
from typing import List


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class ChannelEmailAddress(BaseModel):
    team_id: str | None = None
    user_id: str | None = None
    conversation_id: str | None = None
    date_created: int | None = None
    address: str | None = None
    name: str | None = None
    icons: Icons | None = None


class OwnershipDetail(BaseModel):
    count: int | None = None
    team_id: str | None = None


class Canvas(BaseModel):
    total_count: int | None = None
    ownership_details: List[OwnershipDetail] | None = None


class Lists(BaseModel):
    total_count: int | None = None
    ownership_details: List[OwnershipDetail] | None = None


class Canvas1(BaseModel):
    file_id: str | None = None
    is_empty: bool | None = None
    quip_thread_id: str | None = None
    is_migrated: bool | None = None


class PostingRestrictedTo(BaseModel):
    type: List[str] | None = None
    user: List[str] | None = None


class ThreadsRestrictedTo(BaseModel):
    type: List[str] | None = None


class Data(BaseModel):
    file_id: str | None = None
    shared_ts: str | None = None


class Tab(BaseModel):
    id: str | None = None
    label: str | None = None
    type: str | None = None
    data: Data | None = None
    is_disabled: bool | None = None


class TabzItem(BaseModel):
    id: str | None = None
    label: str | None = None
    type: str | None = None
    data: Data | None = None
    is_disabled: bool | None = None


class MeetingNotes(BaseModel):
    file_id: str | None = None


class Properties(BaseModel):
    canvas: Canvas1 | None = None
    posting_restricted_to: PostingRestrictedTo | None = None
    threads_restricted_to: ThreadsRestrictedTo | None = None
    huddles_restricted: bool | None = None
    at_here_restricted: bool | None = None
    at_channel_restricted: bool | None = None
    tabs: List[Tab] | None = None
    tabz: List[TabzItem] | None = None
    meeting_notes: MeetingNotes | None = None
    is_dormant: bool | None = None
    has_slack_connect_invite_created: bool | None = None


class Conversation(BaseModel):
    id: str | None = None
    name: str | None = None
    purpose: str | None = None
    member_count: int | None = None
    created: int | None = None
    creator_id: str | None = None
    is_private: bool | None = None
    is_archived: bool | None = None
    is_general: bool | None = None
    last_activity_ts: int | None = None
    is_ext_shared: bool | None = None
    is_global_shared: bool | None = None
    is_org_default: bool | None = None
    is_org_mandatory: bool | None = None
    is_org_shared: bool | None = None
    is_frozen: bool | None = None
    internal_team_ids_count: int | None = None
    internal_team_ids_sample_team: str | None = None
    pending_connected_team_ids: List[str] | None = None
    is_pending_ext_shared: bool | None = None
    connected_team_ids: List[str] | None = None
    conversation_host_id: str | None = None
    channel_email_addresses: List[ChannelEmailAddress] | None = None
    connected_limited_team_ids: List[str] | None = None
    external_user_count: int | None = None
    internal_team_ids: List[str] | None = None
    channel_manager_count: int | None = None
    is_disconnect_in_progress: bool | None = None
    canvas: Canvas | None = None
    context_team_id: str | None = None
    lists: Lists | None = None
    properties: Properties | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class AdminConversationsSearchResponse(BaseModel):
    ok: bool | None = None
    conversations: List[Conversation] | None = None
    next_cursor: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    total_count: int | None = None
    response_metadata: ResponseMetadata | None = None
    warning: str | None = None
