# generated by datamodel-codegen:
#   filename:  tmpkvpvemtm.schema.json

from pydantic import BaseModel


class AdminAppsApproveResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
