# generated by datamodel-codegen:
#   filename:  tmparqmnpyt.schema.json

from pydantic import BaseModel


class AdminRolesRemoveAssignmentsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
