# generated by datamodel-codegen:
#   filename:  tmpmeklpyiw.schema.json

from pydantic import BaseModel
from typing import List


class Created(BaseModel):
    device_hardware: str | None = None
    os: str | None = None
    os_version: str | None = None
    slack_client_version: str | None = None
    ip: str | None = None


class Recent(BaseModel):
    device_hardware: str | None = None
    os: str | None = None
    os_version: str | None = None
    slack_client_version: str | None = None
    ip: str | None = None


class ActiveSession(BaseModel):
    user_id: str | None = None
    session_id: int | None = None
    team_id: str | None = None
    created: Created | None = None
    recent: Recent | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class AdminUsersSessionListResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    active_sessions: List[ActiveSession] | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
