# generated by datamodel-codegen:
#   filename:  tmphji_90et.schema.json

from pydantic import BaseModel


class AdminConversationsSetTeamsResponse(BaseModel):
    ok: bool | None = None
    channel: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
