# generated by datamodel-codegen:
#   filename:  tmpxuciwykd.schema.json

from pydantic import BaseModel


class AdminTeamsSettingsSetDiscoverabilityResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
