# generated by datamodel-codegen:
#   filename:  tmp7rz7lm_3.schema.json

from pydantic import BaseModel


class AdminUsersSessionSetSettingsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
