# generated by datamodel-codegen:
#   filename:  tmp0jvjzr2t.schema.json

from pydantic import BaseModel
from typing import List


class Error(BaseModel):
    user: str | None = None
    workflow: str | None = None
    message: str | None = None


class AdminWorkflowsCollaboratorsRemoveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    errors: List[Error] | None = None
    needed: str | None = None
    provided: str | None = None
