# generated by datamodel-codegen:
#   filename:  tmpw_24wnc7.schema.json

from typing import List
from pydantic import BaseModel


class User(BaseModel):
    id: str | None = None
    email: str | None = None
    is_admin: bool | None = None
    is_owner: bool | None = None
    is_primary_owner: bool | None = None
    is_restricted: bool | None = None
    is_ultra_restricted: bool | None = None
    is_bot: bool | None = None
    expiration_ts: int | None = None
    username: str | None = None
    full_name: str | None = None
    is_active: bool | None = None
    date_created: int | None = None
    roles: List[str] | None = None
    workspaces: List[str] | None = None
    has_2fa: bool | None = None
    has_sso: bool | None = None
    last_active_ts: int | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None
    messages: List[str] | None = None


class AdminUsersListResponse(BaseModel):
    ok: bool | None = None
    users: List[User] | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
