# generated by datamodel-codegen:
#   filename:  tmptor7vzev.schema.json

from pydantic import BaseModel


class AdminInviteRequestsApproveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
