# generated by datamodel-codegen:
#   filename:  tmppzga36f9.schema.json

from pydantic import BaseModel


class AdminAppsConfigSetResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
