# generated by datamodel-codegen:
#   filename:  tmpyau1yeqd.schema.json

from pydantic import BaseModel


class AdminConversationsGetCustomRetentionResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    is_policy_enabled: bool | None = None
    duration_days: int | None = None
