# generated by datamodel-codegen:
#   filename:  tmp1x_sff74.schema.json

from pydantic import BaseModel


class AdminUsersSetExpirationResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
