# generated by datamodel-codegen

from pydantic import BaseModel


class AdminAuthPolicyAssignEntitiesResponse(BaseModel):
    ok: bool | None = None
    entity_total_count: int | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
