# generated by datamodel-codegen:
#   filename:  tmpnvqc8n_s.schema.json

from pydantic import BaseModel, Field


class FailedUserIds(BaseModel):
    u00000000: str | None = Field(None, alias='U00000000')
    u00000001: str | None = Field(None, alias='U00000001')


class AdminConversationsInviteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    failed_user_ids: FailedUserIds | None = None
    needed: str | None = None
    provided: str | None = None
