# generated by datamodel-codegen:
#   filename:  tmpvida1but.schema.json

from pydantic import BaseModel


class AdminUsergroupsAddChannelsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
