# generated by datamodel-codegen:
#   filename:  tmpcc5_5j61.schema.json

from pydantic import BaseModel


class AdminBarriersDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
