# generated by datamodel-codegen:
#   filename:  tmp1he6ou0f.schema.json

from pydantic import BaseModel, Field
from typing import List


class Field0000000000(BaseModel):
    type: str | None = None
    name: str | None = None
    title: str | None = None
    description: str | None = None
    is_required: bool | None = None
    is_hidden: bool | None = None


class InputParameters(BaseModel):
    field_0000000000: Field0000000000 | None = Field(None, alias='0000000000')
    field_0000000000_: Field0000000000 | None = Field(None, alias='0000000000_')


class Field00000000002(BaseModel):
    hidden: bool | None = None
    locked: bool | None = None


class Inputs(BaseModel):
    field_0000000000: Field00000000002 | None = Field(None, alias='0000000000')
    field_0000000000_: Field00000000002 | None = Field(None, alias='0000000000_')


class Step(BaseModel):
    id: str | None = None
    function_id: str | None = None
    inputs: Inputs | None = None
    is_pristine: bool | None = None


class Icons(BaseModel):
    image_96: str | None = None
    image_192: str | None = None


class Workflow(BaseModel):
    id: str | None = None
    team_id: str | None = None
    workflow_function_id: str | None = None
    callback_id: str | None = None
    title: str | None = None
    description: str | None = None
    input_parameters: InputParameters | None = None
    steps: List[Step] | None = None
    collaborators: List[str] | None = None
    icons: Icons | None = None
    is_published: bool | None = None
    last_updated_by: str | None = None
    unpublished_change_count: int | None = None
    app_id: str | None = None
    source: str | None = None
    billing_type: str | None = None
    date_updated: int | None = None
    is_billable: bool | None = None
    last_published_version_id: str | None = None
    last_published_date: str | None = None
    trigger_ids: List[str] | None = None
    is_sales_home_workflow: bool | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    next_cursor: str | None = None


class AdminWorkflowsSearchResponse(BaseModel):
    ok: bool | None = None
    workflows: List[Workflow] | None = None
    total_found: int | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    response_metadata: ResponseMetadata | None = None
