# generated by datamodel-codegen:
#   filename:  tmpxndskooy.schema.json

from pydantic import BaseModel


class AdminConversationsDisconnectSharedResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
