# generated by datamodel-codegen:
#   filename:  tmpfar88p_l.schema.json

from pydantic import BaseModel


class AdminConversationsRenameResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
