# generated by datamodel-codegen:
#   filename:  tmp5bj71d91.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class PrimaryUsergroup(BaseModel):
    id: str | None = None
    name: str | None = None


class BarrieredFromUsergroup(BaseModel):
    id: str | None = None
    name: str | None = None


class Barrier(BaseModel):
    id: str | None = None
    enterprise_id: str | None = None
    primary_usergroup: PrimaryUsergroup | None = None
    barriered_from_usergroups: List[BarrieredFromUsergroup] | None = None
    restricted_subjects: List[str] | None = None
    date_update: int | None = None


class AdminBarriersCreateResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    response_metadata: ResponseMetadata | None = None
    barrier: Barrier | None = None
