# generated by datamodel-codegen:
#   filename:  tmpdcbor85w.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    warnings: List[str] | None = None


class AdminConversationsWhitelistRemoveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    warning: str | None = None
    needed: str | None = None
    provided: str | None = None
