# generated by datamodel-codegen:
#   filename:  tmpt2oam7mt.schema.json

from pydantic import BaseModel


class AdminConversationsDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
