# generated by datamodel-codegen:
#   filename:  tmp7yjqsado.schema.json

from pydantic import BaseModel


class AdminUsersAssignResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
