# generated by datamodel-codegen:
#   filename:  tmpn0xd8q2m.schema.json

from pydantic import BaseModel


class AdminConversationsSetCustomRetentionResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
