# generated by datamodel-codegen:
#   filename:  tmpahe692tq.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    next_cursor: str | None = None


class InputParameter(BaseModel):
    type: str | None = None
    name: str | None = None
    title: str | None = None
    is_required: bool | None = None
    description: str | None = None


class OutputParameter(BaseModel):
    type: str | None = None
    name: str | None = None
    title: str | None = None
    is_required: bool | None = None
    description: str | None = None


class ProductLevelAvailability(BaseModel):
    is_available: bool | None = None
    available_to: str | None = None


class Function(BaseModel):
    id: str | None = None
    callback_id: str | None = None
    title: str | None = None
    description: str | None = None
    type: str | None = None
    input_parameters: List[InputParameter] | None = None
    output_parameters: List[OutputParameter] | None = None
    app_id: str | None = None
    date_created: int | None = None
    date_updated: int | None = None
    date_deleted: int | None = None
    form_enabled: bool | None = None
    date_released: int | None = None
    category_id: str | None = None
    category_label: str | None = None
    product_level_availability: ProductLevelAvailability | None = None


class AdminFunctionsListResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    functions: List[Function] | None = None
    warning: str | None = None
