# generated by datamodel-codegen:
#   filename:  tmp8rkt6tw8.schema.json

from pydantic import BaseModel


class AdminAppsRestrictResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
