# generated by datamodel-codegen:
#   filename:  tmpeg7sqjim.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class DomainRestrictions(BaseModel):
    emails: List[str] | None = None
    urls: List[str] | None = None


class Config(BaseModel):
    app_id: str | None = None
    workflow_auth_strategy: str | None = None
    domain_restrictions: DomainRestrictions | None = None


class AdminAppsConfigLookupResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    configs: List[Config] | None = None
    warning: str | None = None
