# generated by datamodel-codegen:
#   filename:  tmpowmyikld.schema.json

from pydantic import BaseModel


class AdminUsersSetExpirationResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
