# generated by datamodel-codegen:
#   filename:  tmpg9pe6z15.schema.json

from pydantic import BaseModel


class AdminTeamsSettingsSetNameResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
