# generated by datamodel-codegen:
#   filename:  tmpup_sqlgt.schema.json

from pydantic import BaseModel


class AdminUsersSetRegularResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
