# generated by datamodel-codegen:
#   filename:  tmp0drgg6qv.schema.json

from pydantic import BaseModel
from typing import Any, List


class Icons(BaseModel):
    image_32: str | None = None
    image_36: str | None = None
    image_48: str | None = None
    image_64: str | None = None
    image_72: str | None = None
    image_96: str | None = None
    image_128: str | None = None
    image_192: str | None = None
    image_512: str | None = None
    image_1024: str | None = None
    image_original: str | None = None


class App(BaseModel):
    id: str | None = None
    name: str | None = None
    description: str | None = None
    help_url: str | None = None
    privacy_policy_url: str | None = None
    app_homepage_url: str | None = None
    app_directory_url: str | None = None
    is_app_directory_approved: bool | None = None
    is_internal: bool | None = None
    is_granular_bot_app: bool | None = None
    additional_info: str | None = None
    icons: Icons | None = None


class User(BaseModel):
    id: str | None = None
    name: str | None = None
    email: str | None = None


class Team(BaseModel):
    id: str | None = None
    name: str | None = None
    domain: str | None = None


class PreviousResolution(BaseModel):
    status: str | None = None
    scopes: List[Any] | None = None


class AppRequest(BaseModel):
    id: str | None = None
    app: App | None = None
    user: User | None = None
    team: Team | None = None
    scopes: List[Any] | None = None
    previous_resolution: PreviousResolution | None = None
    is_user_app_collaborator: bool | None = None
    message: str | None = None
    date_created: int | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None
    messages: List[str] | None = None
    warnings: List[str] | None = None


class AdminAppsRequestsListResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    app_requests: List[AppRequest] | None = None
    response_metadata: ResponseMetadata | None = None
