# generated by datamodel-codegen:
#   filename:  tmp4th9_st2.schema.json

from pydantic import BaseModel


class AdminUsersSessionResetResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
