# generated by datamodel-codegen:
#   filename:  tmpe0k_io1f.schema.json

from pydantic import BaseModel


class AdminUsersSessionClearSettingsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
