# generated by datamodel-codegen:
#   filename:  tmp6y31i5pv.schema.json

from pydantic import BaseModel


class AdminConversationsConvertToPrivateResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
