# generated by datamodel-codegen:
#   filename:  tmpzzjagcyy.schema.json

from pydantic import BaseModel
from typing import List


class Icon(BaseModel):
    image_34: str | None = None
    image_44: str | None = None
    image_68: str | None = None
    image_88: str | None = None
    image_102: str | None = None
    image_132: str | None = None
    image_230: str | None = None
    image_original: str | None = None
    image_default: bool | None = None


class Team(BaseModel):
    id: str | None = None
    name: str | None = None
    domain: str | None = None
    email_domain: str | None = None
    icon: Icon | None = None
    enterprise_id: str | None = None
    enterprise_name: str | None = None
    default_channels: List[str] | None = None
    is_verified: bool | None = None
    enterprise_domain: str | None = None
    url: str | None = None
    avatar_base_url: str | None = None


class AdminTeamsSettingsInfoResponse(BaseModel):
    ok: bool | None = None
    team: Team | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
