# generated by datamodel-codegen:
#   filename:  tmprl_u_e1f.schema.json

from pydantic import BaseModel


class AdminAuthPolicyRemoveEntitiesResponse(BaseModel):
    ok: bool | None = None
    entity_total_count: int | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
