# generated by datamodel-codegen:
#   filename:  tmpktbzrovj.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class AdminTeamsCreateResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    team: str | None = None
    needed: str | None = None
    provided: str | None = None
