# generated by datamodel-codegen:
#   filename:  tmp6h70i326.schema.json

from typing import List
from pydantic import BaseModel


class NotAddedItem(BaseModel):
    channel_id: str | None = None
    errors: List[str] | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class AdminConversationsBulkDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    bulk_action_id: str | None = None
    not_added: List[NotAddedItem] | None = None
    response_metadata: ResponseMetadata | None = None
    warning: str | None = None
