# generated by datamodel-codegen:
#   filename:  tmporadv94r.schema.json

from pydantic import BaseModel


class AdminConversationsUnarchiveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
