# generated by datamodel-codegen:
#   filename:  tmpfc9cxy6f.schema.json

from pydantic import BaseModel


class AdminUsersSetOwnerResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
