# generated by datamodel-codegen:
#   filename:  tmp4nla18g4.schema.json

from pydantic import BaseModel


class AdminUsersRemoveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
