# generated by datamodel-codegen:
#   filename:  tmpyg5y_bw0.schema.json

from pydantic import BaseModel


class AdminUsergroupsAddTeamsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
