# generated by datamodel-codegen:
#   filename:  tmpwin421wk.schema.json

from pydantic import BaseModel


class AdminConversationsRemoveCustomRetentionResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
