# generated by datamodel-codegen:
#   filename:  tmpasg781a3.schema.json

from pydantic import BaseModel


class AdminConversationsEkmListOriginalConnectedChannelInfoResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
