# generated by datamodel-codegen:
#   filename:  tmpr53u6a5z.schema.json

from typing import List
from pydantic import BaseModel


class AdminConversationsGetTeamsResponse(BaseModel):
    ok: bool | None = None
    team_ids: List[str] | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
