# generated by datamodel-codegen:
#   filename:  tmp26jo93wx.schema.json

from typing import Any, Dict, List
from pydantic import BaseModel, Field


class Distribution(BaseModel):
    type: str | None = None
    user_ids: List[str] | None = None


class AllowedEntities(BaseModel):
    type: str | None = None
    user_ids: List[str] | None = None
    team_ids: List[str] | None = None
    org_ids: List[str] | None = None
    channel_ids: List[str] | None = None


class AllowedByAdmin(BaseModel):
    type: str | None = None
    user_ids: List[str] | None = None


class Fn0000000000(BaseModel):
    distribution: Distribution | None = None
    allowed_entities: AllowedEntities | None = None
    allowed_by_admin: AllowedByAdmin | None = None


class Fn00000000001(BaseModel):
    distribution: Distribution | None = None
    allowed_entities: AllowedEntities | None = None
    allowed_by_admin: AllowedByAdmin | None = None


class Permissions(BaseModel):
    fn0000000000: Fn0000000000 | None = Field(None, alias='Fn0000000000')
    fn0000000000_: Fn00000000001 | None = Field(None, alias='Fn0000000000_')


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class Metadata(BaseModel):
    fn0000000000: Dict[str, Any] | None = Field(None, alias='Fn0000000000')
    fn0000000000_: Dict[str, Any] | None = Field(None, alias='Fn0000000000_')


class AdminFunctionsPermissionsLookupResponse(BaseModel):
    ok: bool | None = None
    permissions: Permissions | None = None
    errors: Dict[str, Any] | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    response_metadata: ResponseMetadata | None = None
    metadata: Metadata | None = None
    warning: str | None = None
