# generated by datamodel-codegen:
#   filename:  tmpty0ujr8b.schema.json

from pydantic import BaseModel
from typing import List


class SessionSetting(BaseModel):
    user_id: str | None = None
    desktop_app_browser_quit: bool | None = None
    duration: int | None = None


class AdminUsersSessionGetSettingsResponse(BaseModel):
    ok: bool | None = None
    session_settings: List[SessionSetting] | None = None
    no_settings_applied: List[str] | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
