# generated by datamodel-codegen:
#   filename:  tmp0tsimjir.schema.json

from pydantic import BaseModel


class AdminUsersSetAdminResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
