# generated by datamodel-codegen:
#   filename:  tmphcly30ss.schema.json

from pydantic import BaseModel
from typing import List


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class PostingRestrictedTo(BaseModel):
    type: List[str] | None = None


class ThreadsRestrictedTo(BaseModel):
    type: List[str] | None = None


class Properties(BaseModel):
    posting_restricted_to: PostingRestrictedTo | None = None
    threads_restricted_to: ThreadsRestrictedTo | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    is_channel: bool | None = None
    is_group: bool | None = None
    is_im: bool | None = None
    created: int | None = None
    is_archived: bool | None = None
    is_general: bool | None = None
    unlinked: int | None = None
    name_normalized: str | None = None
    is_shared: bool | None = None
    creator: str | None = None
    is_moved: int | None = None
    is_ext_shared: bool | None = None
    enterprise_id: str | None = None
    is_global_shared: bool | None = None
    is_org_default: bool | None = None
    is_org_mandatory: bool | None = None
    is_org_shared: bool | None = None
    pending_shared: List[str] | None = None
    pending_connected_team_ids: List[str] | None = None
    is_pending_ext_shared: bool | None = None
    is_member: bool | None = None
    is_private: bool | None = None
    is_mpim: bool | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    previous_names: List[str] | None = None
    date_connected: int | None = None
    context_team_id: str | None = None
    updated: int | None = None
    properties: Properties | None = None


class AdminUsergroupsListChannelsResponse(BaseModel):
    ok: bool | None = None
    channels: List[Channel] | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
