# generated by datamodel-codegen:
#   filename:  tmpozov2g97.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class Error(BaseModel):
    message: str | None = None
    user: str | None = None
    workflow: str | None = None


class AdminWorkflowsCollaboratorsAddResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    errors: List[Error] | None = None
