# generated by datamodel-codegen:
#   filename:  tmpu5_853ke.schema.json

from pydantic import BaseModel
from typing import List


class RoleAssignment(BaseModel):
    role_id: str | None = None
    entity_id: str | None = None
    user_id: str | None = None
    date_create: int | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None
    messages: List[str] | None = None


class AdminRolesListAssignmentsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    role_assignments: List[RoleAssignment] | None = None
    response_metadata: ResponseMetadata | None = None
    warning: str | None = None
