# generated by datamodel-codegen:
#   filename:  tmpd73rddch.schema.json

from pydantic import BaseModel
from typing import List


class RejectedUser(BaseModel):
    id: str | None = None
    error: str | None = None


class AdminRolesAddAssignmentsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    rejected_users: List[RejectedUser] | None = None
    needed: str | None = None
    provided: str | None = None
