# generated by datamodel-codegen:
#   filename:  tmp1wbm_r_g.schema.json

from pydantic import BaseModel


class AdminTeamsSettingsSetDiscoverabilityResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
