# generated by datamodel-codegen:
#   filename:  tmpjkfra_99.schema.json

from pydantic import BaseModel, Field


class Field333(BaseModel):
    url: str | None = None
    date_created: int | None = None
    uploaded_by: str | None = None


class Field444(BaseModel):
    url: str | None = None
    date_created: int | None = None
    uploaded_by: str | None = None


class Emoji(BaseModel):
    field_333: Field333 | None = Field(None, alias='333')
    field_444: Field444 | None = Field(None, alias='444')


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class AdminEmojiListResponse(BaseModel):
    ok: bool | None = None
    emoji: Emoji | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
