# generated by datamodel-codegen:
#   filename:  tmpeodyzzdq.schema.json

from pydantic import BaseModel


class AdminConversationsSetConversationPrefsResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
