# generated by datamodel-codegen:
#   filename:  tmplr7btfed.schema.json

from pydantic import BaseModel


class AdminInviteRequestsDenyResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
