# generated by datamodel-codegen:
#   filename:  tmpugjx361h.schema.json

from pydantic import BaseModel
from typing import List


class PrimaryUsergroup(BaseModel):
    id: str | None = None
    name: str | None = None


class BarrieredFromUsergroup(BaseModel):
    id: str | None = None
    name: str | None = None


class Barrier(BaseModel):
    id: str | None = None
    enterprise_id: str | None = None
    primary_usergroup: PrimaryUsergroup | None = None
    barriered_from_usergroups: List[BarrieredFromUsergroup] | None = None
    restricted_subjects: List[str] | None = None
    date_update: int | None = None


class AdminBarriersUpdateResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    barrier: Barrier | None = None
    needed: str | None = None
    provided: str | None = None
