# generated by datamodel-codegen:
#   filename:  tmpnwuvrd3d.schema.json

from pydantic import BaseModel
from typing import List


class Icons(BaseModel):
    image_32: str | None = None
    image_36: str | None = None
    image_48: str | None = None
    image_64: str | None = None
    image_72: str | None = None
    image_96: str | None = None
    image_128: str | None = None
    image_192: str | None = None
    image_512: str | None = None
    image_1024: str | None = None
    image_original: str | None = None


class App(BaseModel):
    id: str | None = None
    name: str | None = None
    description: str | None = None
    help_url: str | None = None
    privacy_policy_url: str | None = None
    app_homepage_url: str | None = None
    app_directory_url: str | None = None
    is_app_directory_approved: bool | None = None
    is_internal: bool | None = None
    is_granular_bot_app: bool | None = None
    additional_info: str | None = None
    icons: Icons | None = None


class Scope(BaseModel):
    name: str | None = None
    description: str | None = None
    is_sensitive: bool | None = None
    token_type: str | None = None


class LastResolvedBy(BaseModel):
    actor_id: str | None = None
    actor_type: str | None = None


class RestrictedApp(BaseModel):
    app: App | None = None
    scopes: List[Scope] | None = None
    date_updated: int | None = None
    last_resolved_by: LastResolvedBy | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None
    messages: List[str] | None = None
    warnings: List[str] | None = None


class AdminAppsRestrictedListResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    restricted_apps: List[RestrictedApp] | None = None
    response_metadata: ResponseMetadata | None = None
