# generated by datamodel-codegen:
#   filename:  tmpdfiaix14.schema.json

from pydantic import BaseModel


class Args(BaseModel):
    error: str | None = None
    foo: str | None = None


class ApiTestResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    args: Args | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
