# generated by datamodel-codegen:
#   filename:  tmpiud3jr9n.schema.json

from pydantic import BaseModel, Field
from typing import List


class FieldMetadata(BaseModel):
    major_version: int | None = None
    minor_version: int | None = None


class DisplayInformation(BaseModel):
    name: str | None = None
    long_description: str | None = None
    description: str | None = None
    background_color: str | None = None


class EventSubscriptions(BaseModel):
    bot_events: List[str] | None = None
    user_events: List[str] | None = None
    request_url: str | None = None


class Interactivity(BaseModel):
    is_enabled: bool | None = None
    request_url: str | None = None
    message_menu_options_url: str | None = None


class Settings(BaseModel):
    description: str | None = None
    long_description: str | None = None
    background_color: str | None = None
    event_subscriptions: EventSubscriptions | None = None
    interactivity: Interactivity | None = None
    allowed_ip_address_ranges: List[str] | None = None
    org_deploy_enabled: bool | None = None
    socket_mode_enabled: bool | None = None
    token_rotation_enabled: bool | None = None
    hermes_app_type: str | None = None
    function_runtime: str | None = None
    is_mcp_enabled: bool | None = None


class AppHome(BaseModel):
    home_tab_enabled: bool | None = None
    messages_tab_enabled: bool | None = None
    messages_tab_read_only_enabled: bool | None = None


class BotUser(BaseModel):
    display_name: str | None = None
    always_online: bool | None = None


class Shortcut(BaseModel):
    type: str | None = None
    callback_id: str | None = None
    name: str | None = None
    description: str | None = None


class SlashCommand(BaseModel):
    command: str | None = None
    description: str | None = None
    usage_hint: str | None = None
    url: str | None = None
    should_escape: bool | None = None


class Features(BaseModel):
    app_home: AppHome | None = None
    bot_user: BotUser | None = None
    shortcuts: List[Shortcut] | None = None
    slash_commands: List[SlashCommand] | None = None
    unfurl_domains: List[str] | None = None


class Scopes(BaseModel):
    bot: List[str] | None = None
    user: List[str] | None = None


class OauthConfig(BaseModel):
    scopes: Scopes | None = None
    redirect_urls: List[str] | None = None
    token_management_enabled: bool | None = None
    pkce_enabled: bool | None = None


class Fn00000000001(BaseModel):
    type: str | None = None
    name: str | None = None
    is_required: bool | None = None
    description: str | None = None
    title: str | None = None
    hint: str | None = None
    min_length: int | None = Field(None, alias='minLength')
    max_length: int | None = Field(None, alias='maxLength')
    minimum: int | None = None
    maximum: int | None = None


class InputParameters(BaseModel):
    fn0000000000: Fn00000000001 | None = Field(None, alias='Fn0000000000')
    fn0000000000_: Fn00000000001 | None = Field(None, alias='Fn0000000000_')


class OutputParameters(BaseModel):
    fn0000000000: Fn00000000001 | None = Field(None, alias='Fn0000000000')
    fn0000000000_: Fn00000000001 | None = Field(None, alias='Fn0000000000_')


class Fn0000000000(BaseModel):
    title: str | None = None
    description: str | None = None
    input_parameters: InputParameters | None = None
    output_parameters: OutputParameters | None = None


class Fn00000000006(BaseModel):
    type: str | None = None
    name: str | None = None
    is_required: bool | None = None
    description: str | None = None
    title: str | None = None
    hint: str | None = None
    min_length: int | None = Field(None, alias='minLength')
    max_length: int | None = Field(None, alias='maxLength')
    minimum: int | None = None
    maximum: int | None = None


class InputParameters1(BaseModel):
    fn0000000000: Fn00000000006 | None = Field(None, alias='Fn0000000000')
    fn0000000000_: Fn00000000006 | None = Field(None, alias='Fn0000000000_')


class OutputParameters1(BaseModel):
    fn0000000000: Fn00000000006 | None = Field(None, alias='Fn0000000000')
    fn0000000000_: Fn00000000006 | None = Field(None, alias='Fn0000000000_')


class Fn00000000005(BaseModel):
    title: str | None = None
    description: str | None = None
    input_parameters: InputParameters1 | None = None
    output_parameters: OutputParameters1 | None = None


class Functions(BaseModel):
    fn0000000000: Fn0000000000 | None = Field(None, alias='Fn0000000000')
    fn0000000000_: Fn00000000005 | None = Field(None, alias='Fn0000000000_')


class Manifest(BaseModel):
    field_metadata: FieldMetadata | None = Field(None, alias='_metadata')
    display_information: DisplayInformation | None = None
    settings: Settings | None = None
    features: Features | None = None
    oauth_config: OauthConfig | None = None
    functions: Functions | None = None


class AppsManifestExportResponse(BaseModel):
    ok: bool | None = None
    manifest: Manifest | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
