# generated by datamodel-codegen:
#   filename:  tmp6f9ywvub.schema.json

from pydantic import BaseModel


class AppsPermissionsUsersListResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
