# generated by datamodel-codegen:
#   filename:  tmpu2ibb2fm.schema.json

from pydantic import BaseModel


class AppsPermissionsRequestResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
