# generated by datamodel-codegen:
#   filename:  tmpt_2aailc.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class Error(BaseModel):
    code: str | None = None
    message: str | None = None
    pointer: str | None = None
    related_component: str | None = None


class Credentials(BaseModel):
    client_id: str | None = None
    client_secret: str | None = None
    verification_token: str | None = None
    signing_secret: str | None = None


class AppsManifestCreateResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    errors: List[Error] | None = None
    app_id: str | None = None
    credentials: Credentials | None = None
    oauth_authorize_url: str | None = None
    team_id: str | None = None
    team_domain: str | None = None
    warning: str | None = None
