# generated by datamodel-codegen:
#   filename:  tmptjw_1mbj.schema.json

from pydantic import BaseModel


class AppsManifestDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
