# generated by datamodel-codegen:
#   filename:  tmp4448tbet.schema.json

from pydantic import BaseModel


class AppsUserConnectionUpdateResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
