# generated by datamodel-codegen:
#   filename:  tmpa9sqhnky.schema.json

from pydantic import BaseModel


class AppsPermissionsUsersRequestResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
