# generated by datamodel-codegen:
#   filename:  tmp56tiy8kt.schema.json

from pydantic import BaseModel


class AppsPermissionsResourcesListResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
