# generated by datamodel-codegen:
#   filename:  tmp2_1dmtns.schema.json

from pydantic import BaseModel


class AppsPermissionsUsersRequestResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
