# generated by datamodel-codegen:
#   filename:  tmp8pkavx4u.schema.json

from pydantic import BaseModel
from typing import List


class Authorization(BaseModel):
    enterprise_id: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    is_bot: bool | None = None
    is_enterprise_install: bool | None = None


class AppsEventAuthorizationsListResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    authorizations: List[Authorization] | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
