# generated by datamodel-codegen:
#   filename:  tmpp1dt1elc.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class AppsConnectionsOpenResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    url: str | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
