# generated by datamodel-codegen:
#   filename:  tmpmlwwhqnh.schema.json

from pydantic import BaseModel


class AppsPermissionsScopesListResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
