# generated by datamodel-codegen:
#   filename:  tmpb6z8mtex.schema.json

from pydantic import BaseModel


class AppsPermissionsInfoResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
