# generated by datamodel-codegen:
#   filename:  tmpna1oc5cw.schema.json

from pydantic import BaseModel


class AssistantThreadsSetStatusResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
