# generated by datamodel-codegen:
#   filename:  tmp8fa0vsqf.schema.json

from pydantic import BaseModel


class AssistantThreadsSetSuggestedPromptsResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
