# generated by datamodel-codegen:
#   filename:  tmpm8krusml.schema.json

from pydantic import BaseModel


class AssistantThreadsSetTitleResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
