# generated by datamodel-codegen:
#   filename:  tmpo0pt7mjo.schema.json

from pydantic import BaseModel
from typing import List


class Icon(BaseModel):
    image_default: bool | None = None
    image_34: str | None = None
    image_44: str | None = None
    image_68: str | None = None
    image_88: str | None = None
    image_102: str | None = None
    image_230: str | None = None
    image_132: str | None = None


class Team(BaseModel):
    id: str | None = None
    name: str | None = None
    icon: Icon | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class AuthTeamsListResponse(BaseModel):
    ok: bool | None = None
    teams: List[Team] | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
