# generated by datamodel-codegen:
#   filename:  tmp8fl5xun3.schema.json

from pydantic import BaseModel


class AuthRevokeResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
