# generated by datamodel-codegen:
#   filename:  tmppheo5unx.schema.json

from pydantic import BaseModel


class AuthTestResponse(BaseModel):
    ok: bool | None = None
    url: str | None = None
    team: str | None = None
    user: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    bot_id: str | None = None
    is_enterprise_install: bool | None = None
    app_name: str | None = None
    app_id: str | None = None
    enterprise_id: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    expires_in: int | None = None
    context: str | None = None
    warning: str | None = None
