# generated by datamodel-codegen:
#   filename:  tmp7zzv8i54.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class Bookmark(BaseModel):
    id: str | None = None
    channel_id: str | None = None
    title: str | None = None
    link: str | None = None
    emoji: str | None = None
    icon_url: str | None = None
    entity_id: str | None = None
    type: str | None = None
    date_created: int | None = None
    date_updated: int | None = None
    rank: str | None = None
    last_updated_by_user_id: str | None = None
    last_updated_by_team_id: str | None = None
    shortcut_id: str | None = None
    app_id: str | None = None
    app_action_id: str | None = None


class BookmarksEditResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    bookmark: Bookmark | None = None
    warning: str | None = None
