# generated by datamodel-codegen:
#   filename:  tmpdi0grqav.schema.json

from pydantic import BaseModel


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class Bot(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    user_id: str | None = None
    icons: Icons | None = None


class BotsInfoResponse(BaseModel):
    ok: bool | None = None
    bot: Bot | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
