# generated by datamodel-codegen:
#   filename:  tmp9b7dx6eq.schema.json

from pydantic import BaseModel
from typing import List


class User(BaseModel):
    slack_id: str | None = None
    external_id: str | None = None
    display_name: str | None = None
    avatar_url: str | None = None


class Call(BaseModel):
    id: str | None = None
    date_start: int | None = None
    external_unique_id: str | None = None
    join_url: str | None = None
    external_display_id: str | None = None
    title: str | None = None
    users: List[User] | None = None
    desktop_app_join_url: str | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class CallsAddResponse(BaseModel):
    ok: bool | None = None
    call: Call | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
