# generated by datamodel-codegen

from typing import Any, Dict
from pydantic import BaseModel


class CanvasesDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: Dict[str, Any] | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
