# generated by datamodel-codegen:
#   filename:  tmp7ou2rncd.schema.json

from typing import Any, Dict, List
from pydantic import BaseModel


class CanvasesAccessDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    failed_to_update_channel_ids: List[str] | None = None
    failed_to_update_user_ids: List[str] | None = None
    response_metadata: Dict[str, Any] | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
