# generated by datamodel-codegen:
#   filename:  tmptolk_2_y.schema.json

from pydantic import BaseModel
from typing import List


class File(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    editable: bool | None = None
    size: int | None = None
    mode: str | None = None
    is_external: bool | None = None
    external_type: str | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    username: str | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    lines: int | None = None
    lines_more: int | None = None
    preview_is_truncated: bool | None = None
    is_starred: bool | None = None
    has_rich_preview: bool | None = None


class Text(BaseModel):
    type: str | None = None
    text: str | None = None
    verbatim: bool | None = None
    emoji: bool | None = None


class Accessory(BaseModel):
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    type: str | None = None
    alt_text: str | None = None


class Text1(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm1(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Deny(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm(BaseModel):
    title: Title | None = None
    text: Text1 | None = None
    confirm: Confirm1 | None = None
    deny: Deny | None = None


class Placeholder(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Description(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class InitialOption(BaseModel):
    text: Text1 | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Element(BaseModel):
    type: str | None = None
    action_id: str | None = None
    text: Text1 | None = None
    value: str | None = None
    url: str | None = None
    style: str | None = None
    confirm: Confirm | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    initial_conversation: str | None = None
    initial_date: str | None = None
    initial_option: InitialOption | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    initial_user: str | None = None


class Field(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None
    verbatim: bool | None = None


class Block(BaseModel):
    type: str | None = None
    block_id: str | None = None
    text: Text | None = None
    accessory: Accessory | None = None
    elements: List[Element] | None = None
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    alt_text: str | None = None
    title: Title | None = None
    fields: List[Field] | None = None


class Field1(BaseModel):
    title: str | None = None
    value: str | None = None
    short: bool | None = None


class Confirm2(BaseModel):
    title: str | None = None
    text: str | None = None
    ok_text: str | None = None
    dismiss_text: str | None = None


class Option(BaseModel):
    text: str | None = None
    value: str | None = None


class SelectedOption(BaseModel):
    text: str | None = None
    value: str | None = None


class OptionGroup(BaseModel):
    text: str | None = None


class Action(BaseModel):
    id: str | None = None
    name: str | None = None
    text: str | None = None
    style: str | None = None
    type: str | None = None
    value: str | None = None
    confirm: Confirm2 | None = None
    options: List[Option] | None = None
    selected_options: List[SelectedOption] | None = None
    data_source: str | None = None
    min_query_length: int | None = None
    option_groups: List[OptionGroup] | None = None
    url: str | None = None


class Metadata(BaseModel):
    thumb_64: bool | None = None
    thumb_80: bool | None = None
    thumb_160: bool | None = None
    original_w: int | None = None
    original_h: int | None = None
    thumb_360_w: int | None = None
    thumb_360_h: int | None = None
    format: str | None = None
    extension: str | None = None
    rotation: int | None = None
    thumb_tiny: str | None = None


class Attachment(BaseModel):
    msg_subtype: str | None = None
    fallback: str | None = None
    callback_id: str | None = None
    color: str | None = None
    pretext: str | None = None
    service_url: str | None = None
    service_name: str | None = None
    service_icon: str | None = None
    author_name: str | None = None
    author_link: str | None = None
    author_icon: str | None = None
    from_url: str | None = None
    original_url: str | None = None
    author_subname: str | None = None
    channel_id: str | None = None
    channel_name: str | None = None
    id: int | None = None
    bot_id: str | None = None
    indent: bool | None = None
    is_msg_unfurl: bool | None = None
    is_reply_unfurl: bool | None = None
    is_thread_root_unfurl: bool | None = None
    is_app_unfurl: bool | None = None
    app_unfurl_url: str | None = None
    title: str | None = None
    title_link: str | None = None
    text: str | None = None
    fields: List[Field1] | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    thumb_url: str | None = None
    thumb_width: int | None = None
    thumb_height: int | None = None
    video_html: str | None = None
    video_html_width: int | None = None
    video_html_height: int | None = None
    footer: str | None = None
    footer_icon: str | None = None
    ts: str | None = None
    mrkdwn_in: List[str] | None = None
    actions: List[Action] | None = None
    filename: str | None = None
    size: int | None = None
    mimetype: str | None = None
    url: str | None = None
    metadata: Metadata | None = None


class Edited(BaseModel):
    user: str | None = None
    ts: str | None = None


class Latest(BaseModel):
    type: str | None = None
    text: str | None = None
    files: List[File] | None = None
    upload: bool | None = None
    user: str | None = None
    display_as_bot: bool | None = None
    ts: str | None = None
    subtype: str | None = None
    username: str | None = None
    bot_id: str | None = None
    blocks: List[Block] | None = None
    x_files: List[str] | None = None
    attachments: List[Attachment] | None = None
    edited: Edited | None = None


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    is_channel: bool | None = None
    created: int | None = None
    is_archived: bool | None = None
    is_general: bool | None = None
    unlinked: int | None = None
    creator: str | None = None
    name_normalized: str | None = None
    is_shared: bool | None = None
    is_org_shared: bool | None = None
    is_member: bool | None = None
    is_private: bool | None = None
    is_mpim: bool | None = None
    last_read: str | None = None
    latest: Latest | None = None
    unread_count: int | None = None
    unread_count_display: int | None = None
    members: List[str] | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    previous_names: List[str] | None = None


class ChannelsInfoResponse(BaseModel):
    ok: bool | None = None
    channel: Channel | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
