# generated by datamodel-codegen:
#   filename:  tmp2rzwktoq.schema.json

from pydantic import BaseModel


class ChannelsLeaveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
