# generated by datamodel-codegen:
#   filename:  tmppthgruj7.schema.json

from pydantic import BaseModel
from typing import List


class Latest(BaseModel):
    type: str | None = None
    subtype: str | None = None
    ts: str | None = None
    user: str | None = None
    text: str | None = None


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    is_channel: bool | None = None
    created: int | None = None
    is_archived: bool | None = None
    is_general: bool | None = None
    unlinked: int | None = None
    creator: str | None = None
    name_normalized: str | None = None
    is_shared: bool | None = None
    is_org_shared: bool | None = None
    is_member: bool | None = None
    is_private: bool | None = None
    is_mpim: bool | None = None
    last_read: str | None = None
    latest: Latest | None = None
    unread_count: int | None = None
    unread_count_display: int | None = None
    members: List[str] | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    previous_names: List[str] | None = None
    priority: int | None = None


class ChannelsJoinResponse(BaseModel):
    ok: bool | None = None
    channel: Channel | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
