# generated by datamodel-codegen

from pydantic import BaseModel


class ChannelsSetPurposeResponse(BaseModel):
    ok: bool | None = None
    purpose: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
