# generated by datamodel-codegen:
#   filename:  tmpygyqe9ac.schema.json

from pydantic import BaseModel
from typing import List


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    is_channel: bool | None = None
    created: int | None = None
    is_archived: bool | None = None
    is_general: bool | None = None
    unlinked: int | None = None
    creator: str | None = None
    name_normalized: str | None = None
    is_shared: bool | None = None
    is_org_shared: bool | None = None
    is_member: bool | None = None
    is_private: bool | None = None
    is_mpim: bool | None = None
    members: List[str] | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    previous_names: List[str] | None = None


class ChannelsRenameResponse(BaseModel):
    channel: Channel | None = None
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
