# generated by datamodel-codegen:
#   filename:  tmpi44t2ys_.schema.json

from pydantic import BaseModel


class ChannelsArchiveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
