# generated by datamodel-codegen:
#   filename:  tmpqp43lqu9.schema.json

from pydantic import BaseModel


class ChannelsSetPurposeResponse(BaseModel):
    ok: bool | None = None
    purpose: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
