# generated by datamodel-codegen

from pydantic import BaseModel


class ChannelsSetTopicResponse(BaseModel):
    topic: str | None = None
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
