# generated by datamodel-codegen:
#   filename:  tmp51my_kqt.schema.json

from pydantic import BaseModel


class ChannelsKickResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
