# generated by datamodel-codegen:
#   filename:  tmpjrt9iy9b.schema.json

from pydantic import BaseModel


class ChannelsUnarchiveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
