# generated by datamodel-codegen:
#   filename:  tmpoauxw7xl.schema.json

from pydantic import BaseModel


class ChannelsMarkResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
