# generated by datamodel-codegen:
#   filename:  tmpbrcyaj22.schema.json

from pydantic import BaseModel, Field
from typing import Any, Dict, List


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Edited(BaseModel):
    user: str | None = None
    ts: str | None = None


class Metadata(BaseModel):
    event_payload: Dict[str, Any] | None = None
    event_type: str | None = None


class Recording(BaseModel):
    transcript: bool | None = None
    summary: bool | None = None
    notetaking: bool | None = None
    summary_status: str | None = None
    can_record_summary: str | None = None


class Room(BaseModel):
    id: str | None = None
    name: str | None = None
    media_server: str | None = None
    created_by: str | None = None
    date_start: int | None = None
    date_end: int | None = None
    participants: List[str] | None = None
    participant_history: List[str] | None = None
    participants_camera_on: List[str] | None = None
    participants_camera_off: List[str] | None = None
    participants_screenshare_on: List[str] | None = None
    participants_screenshare_off: List[str] | None = None
    canvas_thread_ts: str | None = None
    thread_root_ts: str | None = None
    channels: List[str] | None = None
    is_dm_call: bool | None = None
    was_rejected: bool | None = None
    was_missed: bool | None = None
    was_accepted: bool | None = None
    has_ended: bool | None = None
    background_id: str | None = None
    canvas_background: str | None = None
    is_prewarmed: bool | None = None
    is_scheduled: bool | None = None
    attached_file_ids: List[str] | None = None
    media_backend_type: str | None = None
    display_id: str | None = None
    external_unique_id: str | None = None
    app_id: str | None = None
    call_family: str | None = None
    pending_invitees: Dict[str, Any] | None = None
    last_invite_status_by_user: Dict[str, Any] | None = None
    knocks: Dict[str, Any] | None = None
    recording: Recording | None = None
    huddle_link: str | None = None


class Preview(BaseModel):
    content: str | None = None
    has_more: bool | None = None


class Transcription(BaseModel):
    status: str | None = None
    locale: str | None = None
    preview: Preview | None = None


class C03E94MkuItem(BaseModel):
    share_user_id: str | None = None
    reply_users: List[str] | None = None
    reply_users_count: int | None = None
    reply_count: int | None = None
    ts: str | None = None
    thread_ts: str | None = None
    latest_reply: str | None = None
    channel_name: str | None = None
    team_id: str | None = None
    access: str | None = None
    source: str | None = None
    date_last_shared: int | None = None


class Public(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Private(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Shares(BaseModel):
    public: Public | None = None
    private: Private | None = None


class ToItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class FromItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class CcItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class Headers(BaseModel):
    date: str | None = None
    in_reply_to: str | None = None
    reply_to: str | None = None
    message_id: str | None = None


class MediaProgress(BaseModel):
    offset_ms: int | None = None
    max_offset_ms: int | None = None
    duration_ms: int | None = None
    media_watched: bool | None = None


class Saved(BaseModel):
    is_archived: bool | None = None
    date_completed: int | None = None
    date_due: int | None = None
    state: str | None = None


class Text(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm1(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Deny(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm1 | None = None
    deny: Deny | None = None
    style: str | None = None


class CustomizableInputParameter(BaseModel):
    name: str | None = None
    value: str | None = None


class Trigger(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow(BaseModel):
    trigger: Trigger | None = None


class SlackFile(BaseModel):
    id: str | None = None
    url: str | None = None


class Element(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm | None = None
    accessibility_label: str | None = None
    workflow: Workflow | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class TitleBlock(BaseModel):
    type: str | None = None
    elements: List[Element] | None = None
    block_id: str | None = None


class DmMpdmUsersWithFileAcces(BaseModel):
    user_id: str | None = None
    access: str | None = None


class Favorite(BaseModel):
    collection_id: str | None = None
    collection_name: str | None = None
    position: str | None = None


class CreationSource(BaseModel):
    type: str | None = None
    reference_id: str | None = None
    workflow_function_id: str | None = None


class Choice(BaseModel):
    value: str | None = None
    label: str | None = None
    color: str | None = None


class DefaultValueTyped(BaseModel):
    select: List[str] | None = None


class CanvasPlaceholderMappingItem(BaseModel):
    variable: str | None = None
    column: str | None = None


class Options(BaseModel):
    choices: List[Choice] | None = None
    format: str | None = None
    default_value: str | None = None
    default_value_typed: DefaultValueTyped | None = None
    emoji: str | None = None
    max: int | None = None
    precision: int | None = None
    show_member_name: bool | None = None
    date_format: str | None = None
    time_format: str | None = None
    currency_format: str | None = None
    emoji_team_id: str | None = None
    currency: str | None = None
    rounding: str | None = None
    mark_as_done_when_checked: bool | None = None
    for_assignment: bool | None = None
    notify_users: bool | None = None
    linked_to: List[str] | None = None
    canvas_id: str | None = None
    canvas_placeholder_mapping: List[CanvasPlaceholderMappingItem] | None = None


class SchemaItem(BaseModel):
    id: str | None = None
    name: str | None = None
    key: str | None = None
    type: str | None = None
    is_primary_column: bool | None = None
    options: Options | None = None


class Column(BaseModel):
    visible: bool | None = None
    key: str | None = None
    id: str | None = None
    position: str | None = None
    width: int | None = None


class Grouping(BaseModel):
    group_by: str | None = None
    group_by_column_id: str | None = None


class Filter(BaseModel):
    key: str | None = None
    operator: str | None = None
    values: List[str] | None = None
    typed_values: List[Any] | None = None
    column_id: str | None = None


class View(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None
    is_locked: bool | None = None
    position: str | None = None
    columns: List[Column] | None = None
    date_created: int | None = None
    created_by: str | None = None
    stick_column_left: bool | None = None
    is_all_items_view: bool | None = None
    default_view_key: str | None = None
    show_completed_items: bool | None = None
    grouping: Grouping | None = None
    filters: List[Filter] | None = None


class Confirm3(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm2(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm3 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger1(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow1(BaseModel):
    trigger: Trigger1 | None = None


class Element1(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm2 | None = None
    accessibility_label: str | None = None
    workflow: Workflow1 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class DescriptionBlock(BaseModel):
    type: str | None = None
    elements: List[Element1] | None = None
    block_id: str | None = None


class ListMetadata(BaseModel):
    icon: str | None = None
    icon_url: str | None = None
    icon_team_id: str | None = None
    description: str | None = None
    is_trial: bool | None = None
    creation_source: CreationSource | None = None
    schema_: List[SchemaItem] | None = Field(None, alias='schema')
    views: List[View] | None = None
    integrations: List[str] | None = None
    description_blocks: List[DescriptionBlock] | None = None


class ListLimits(BaseModel):
    over_row_maximum: bool | None = None
    row_count_limit: int | None = None
    row_count: int | None = None
    over_column_maximum: bool | None = None
    column_count: int | None = None
    column_count_limit: int | None = None
    over_view_maximum: bool | None = None
    view_count: int | None = None
    view_count_limit: int | None = None
    max_attachments_per_cell: int | None = None


class InitialComment(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    user: str | None = None
    comment: str | None = None
    channel: str | None = None
    is_intro: bool | None = None


class Reaction(BaseModel):
    name: str | None = None
    count: int | None = None
    users: List[str] | None = None
    url: str | None = None


class File(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    editors: List[str] | None = None
    edit_timestamp: int | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    url_static_preview: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    shares: Shares | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    quip_thread_id: str | None = None
    is_channel_space: bool | None = None
    linked_channel_id: str | None = None
    access: str | None = None
    teams_shared_with: List[Any] | None = None
    last_read: int | None = None
    title_blocks: List[TitleBlock] | None = None
    private_channels_with_file_access_count: int | None = None
    private_file_with_access_count: int | None = None
    dm_mpdm_users_with_file_access: List[DmMpdmUsersWithFileAcces] | None = None
    org_or_workspace_access: str | None = None
    update_notification: int | None = None
    canvas_template_mode: str | None = None
    template_conversion_ts: int | None = None
    template_name: str | None = None
    template_title: str | None = None
    template_description: str | None = None
    template_icon: str | None = None
    team_pref_version_history_enabled: bool | None = None
    show_badge: bool | None = None
    favorites: List[Favorite] | None = None
    list_metadata: ListMetadata | None = None
    list_limits: ListLimits | None = None
    list_csv_download_url: str | None = None
    can_toggle_canvas_lock: bool | None = None
    is_restricted_sharing_enabled: bool | None = None
    canvas_printing_enabled: bool | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction] | None = None
    comments_count: int | None = None


class Confirm5(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm4(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm5 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger2(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow2(BaseModel):
    trigger: Trigger2 | None = None


class Element2(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm4 | None = None
    accessibility_label: str | None = None
    workflow: Workflow2 | None = None


class AppIconUrls(BaseModel):
    image_32: str | None = None
    image_36: str | None = None
    image_48: str | None = None
    image_64: str | None = None
    image_72: str | None = None
    image_96: str | None = None
    image_128: str | None = None
    image_192: str | None = None
    image_512: str | None = None
    image_1024: str | None = None
    image_original: str | None = None


class ActiveParticipant(BaseModel):
    slack_id: str | None = None
    external_id: str | None = None
    display_name: str | None = None
    avatar_url: str | None = None


class AllParticipant(BaseModel):
    slack_id: str | None = None
    external_id: str | None = None
    display_name: str | None = None
    avatar_url: str | None = None


class V1(BaseModel):
    id: str | None = None
    app_id: str | None = None
    app_icon_urls: AppIconUrls | None = None
    date_start: int | None = None
    active_participants: List[ActiveParticipant] | None = None
    all_participants: List[AllParticipant] | None = None
    display_id: str | None = None
    join_url: str | None = None
    desktop_app_join_url: str | None = None
    name: str | None = None
    created_by: str | None = None
    date_end: int | None = None
    channels: List[str] | None = None
    is_dm_call: bool | None = None
    was_rejected: bool | None = None
    was_missed: bool | None = None
    was_accepted: bool | None = None
    has_ended: bool | None = None


class Call(BaseModel):
    v1: V1 | None = None
    media_backend_type: str | None = None


class Transcription1(BaseModel):
    status: str | None = None
    locale: str | None = None
    preview: Preview | None = None


class Public1(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Private1(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Shares1(BaseModel):
    public: Public1 | None = None
    private: Private1 | None = None


class Confirm7(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm6(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm7 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger3(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow3(BaseModel):
    trigger: Trigger3 | None = None


class Element3(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm6 | None = None
    accessibility_label: str | None = None
    workflow: Workflow3 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class TitleBlock1(BaseModel):
    type: str | None = None
    elements: List[Element3] | None = None
    block_id: str | None = None


class Options1(BaseModel):
    choices: List[Choice] | None = None
    format: str | None = None
    default_value: str | None = None
    default_value_typed: DefaultValueTyped | None = None
    emoji: str | None = None
    max: int | None = None
    precision: int | None = None
    show_member_name: bool | None = None
    date_format: str | None = None
    time_format: str | None = None
    currency_format: str | None = None
    emoji_team_id: str | None = None
    currency: str | None = None
    rounding: str | None = None
    mark_as_done_when_checked: bool | None = None
    for_assignment: bool | None = None
    notify_users: bool | None = None
    linked_to: List[str] | None = None
    canvas_id: str | None = None
    canvas_placeholder_mapping: List[CanvasPlaceholderMappingItem] | None = None


class SchemaItem1(BaseModel):
    id: str | None = None
    name: str | None = None
    key: str | None = None
    type: str | None = None
    is_primary_column: bool | None = None
    options: Options1 | None = None


class View1(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None
    is_locked: bool | None = None
    position: str | None = None
    columns: List[Column] | None = None
    date_created: int | None = None
    created_by: str | None = None
    stick_column_left: bool | None = None
    is_all_items_view: bool | None = None
    default_view_key: str | None = None
    show_completed_items: bool | None = None
    grouping: Grouping | None = None
    filters: List[Filter] | None = None


class Confirm9(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm8(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm9 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger4(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow4(BaseModel):
    trigger: Trigger4 | None = None


class Element4(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm8 | None = None
    accessibility_label: str | None = None
    workflow: Workflow4 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class DescriptionBlock1(BaseModel):
    type: str | None = None
    elements: List[Element4] | None = None
    block_id: str | None = None


class ListMetadata1(BaseModel):
    icon: str | None = None
    icon_url: str | None = None
    icon_team_id: str | None = None
    description: str | None = None
    is_trial: bool | None = None
    creation_source: CreationSource | None = None
    schema_: List[SchemaItem1] | None = Field(None, alias='schema')
    views: List[View1] | None = None
    integrations: List[str] | None = None
    description_blocks: List[DescriptionBlock1] | None = None


class Confirm11(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm10(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm11 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger5(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow5(BaseModel):
    trigger: Trigger5 | None = None


class Element5(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm10 | None = None
    accessibility_label: str | None = None
    workflow: Workflow5 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class Block1(BaseModel):
    type: str | None = None
    elements: List[Element5] | None = None
    block_id: str | None = None


class File1(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    editors: List[str] | None = None
    edit_timestamp: int | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription1 | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    url_static_preview: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    shares: Shares1 | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    quip_thread_id: str | None = None
    is_channel_space: bool | None = None
    linked_channel_id: str | None = None
    access: str | None = None
    teams_shared_with: List[Any] | None = None
    last_read: int | None = None
    title_blocks: List[TitleBlock1] | None = None
    private_channels_with_file_access_count: int | None = None
    private_file_with_access_count: int | None = None
    dm_mpdm_users_with_file_access: List[DmMpdmUsersWithFileAcces] | None = None
    org_or_workspace_access: str | None = None
    update_notification: int | None = None
    canvas_template_mode: str | None = None
    template_conversion_ts: int | None = None
    template_name: str | None = None
    template_title: str | None = None
    template_description: str | None = None
    template_icon: str | None = None
    team_pref_version_history_enabled: bool | None = None
    show_badge: bool | None = None
    favorites: List[Favorite] | None = None
    list_metadata: ListMetadata1 | None = None
    list_limits: ListLimits | None = None
    list_csv_download_url: str | None = None
    can_toggle_canvas_lock: bool | None = None
    is_restricted_sharing_enabled: bool | None = None
    canvas_printing_enabled: bool | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction] | None = None
    comments_count: int | None = None
    attachments: List[Any] | None = None
    blocks: List[Block1] | None = None


class Description(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class FieldModel(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None
    verbatim: bool | None = None


class Confirm13(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm12(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm13 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger6(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow6(BaseModel):
    trigger: Trigger6 | None = None


class Option(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption1(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Placeholder(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Filter2(BaseModel):
    include: List[Any] | None = None
    exclude_external_shared_channels: bool | None = None
    exclude_bot_users: bool | None = None


class Label(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Option1(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup(BaseModel):
    label: Label | None = None
    options: List[Option1] | None = None


class Accessory(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm12 | None = None
    accessibility_label: str | None = None
    workflow: Workflow6 | None = None
    options: List[Option] | None = None
    initial_options: List[InitialOption] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption1 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter2 | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None
    option_groups: List[OptionGroup] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None


class Confirm15(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm14(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm15 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger7(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow7(BaseModel):
    trigger: Trigger7 | None = None


class Option2(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption2(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption3(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Option3(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup1(BaseModel):
    label: Label | None = None
    options: List[Option3] | None = None


class Element6(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm14 | None = None
    accessibility_label: str | None = None
    workflow: Workflow7 | None = None
    options: List[Option2] | None = None
    initial_options: List[InitialOption2] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption3 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter2 | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None
    option_groups: List[OptionGroup1] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None


class Hint(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Block(BaseModel):
    type: str | None = None
    elements: List[Element2] | None = None
    block_id: str | None = None
    call_id: str | None = None
    api_decoration_available: bool | None = None
    call: Call | None = None
    external_id: str | None = None
    source: str | None = None
    file_id: str | None = None
    file: File1 | None = None
    text: Text | None = None
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    is_animated: bool | None = None
    slack_file: SlackFile | None = None
    alt_text: str | None = None
    title: Title | None = None
    title_url: str | None = None
    description: Description | None = None
    video_url: str | None = None
    thumbnail_url: str | None = None
    author_name: str | None = None
    provider_name: str | None = None
    provider_icon_url: str | None = None
    function_trigger_id: str | None = None
    app_id: str | None = None
    is_workflow_app: bool | None = None
    sales_home_workflow_app_type: int | None = None
    app_collaborators: List[str] | None = None
    button_label: str | None = None
    bot_user_id: str | None = None
    url: str | None = None
    owning_team_id: str | None = None
    workflow_id: str | None = None
    developer_trace_id: str | None = None
    trigger_type: str | None = None
    trigger_subtype: str | None = None
    share_url: str | None = None
    fields: List[FieldModel] | None = None
    accessory: Accessory | None = None
    expand: bool | None = None
    label: Label | None = None
    element: Element6 | None = None
    dispatch_action: bool | None = None
    hint: Hint | None = None
    optional: bool | None = None


class Confirm17(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm16(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm17 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger8(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow8(BaseModel):
    trigger: Trigger8 | None = None


class Element7(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm16 | None = None
    accessibility_label: str | None = None
    workflow: Workflow8 | None = None


class V11(BaseModel):
    id: str | None = None
    app_id: str | None = None
    app_icon_urls: AppIconUrls | None = None
    date_start: int | None = None
    active_participants: List[ActiveParticipant] | None = None
    all_participants: List[AllParticipant] | None = None
    display_id: str | None = None
    join_url: str | None = None
    desktop_app_join_url: str | None = None
    name: str | None = None
    created_by: str | None = None
    date_end: int | None = None
    channels: List[str] | None = None
    is_dm_call: bool | None = None
    was_rejected: bool | None = None
    was_missed: bool | None = None
    was_accepted: bool | None = None
    has_ended: bool | None = None


class Call1(BaseModel):
    v1: V11 | None = None
    media_backend_type: str | None = None


class Transcription2(BaseModel):
    status: str | None = None
    locale: str | None = None
    preview: Preview | None = None


class Public2(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Private2(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Shares2(BaseModel):
    public: Public2 | None = None
    private: Private2 | None = None


class Confirm19(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm18(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm19 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger9(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow9(BaseModel):
    trigger: Trigger9 | None = None


class Element8(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm18 | None = None
    accessibility_label: str | None = None
    workflow: Workflow9 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class TitleBlock3(BaseModel):
    type: str | None = None
    elements: List[Element8] | None = None
    block_id: str | None = None


class Options2(BaseModel):
    choices: List[Choice] | None = None
    format: str | None = None
    default_value: str | None = None
    default_value_typed: DefaultValueTyped | None = None
    emoji: str | None = None
    max: int | None = None
    precision: int | None = None
    show_member_name: bool | None = None
    date_format: str | None = None
    time_format: str | None = None
    currency_format: str | None = None
    emoji_team_id: str | None = None
    currency: str | None = None
    rounding: str | None = None
    mark_as_done_when_checked: bool | None = None
    for_assignment: bool | None = None
    notify_users: bool | None = None
    linked_to: List[str] | None = None
    canvas_id: str | None = None
    canvas_placeholder_mapping: List[CanvasPlaceholderMappingItem] | None = None


class SchemaItem2(BaseModel):
    id: str | None = None
    name: str | None = None
    key: str | None = None
    type: str | None = None
    is_primary_column: bool | None = None
    options: Options2 | None = None


class Filter4(BaseModel):
    key: str | None = None
    operator: str | None = None
    values: List[str] | None = None
    typed_values: List[Any] | None = None
    column_id: str | None = None


class View2(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None
    is_locked: bool | None = None
    position: str | None = None
    columns: List[Column] | None = None
    date_created: int | None = None
    created_by: str | None = None
    stick_column_left: bool | None = None
    is_all_items_view: bool | None = None
    default_view_key: str | None = None
    show_completed_items: bool | None = None
    grouping: Grouping | None = None
    filters: List[Filter4] | None = None


class Confirm21(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm20(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm21 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger10(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow10(BaseModel):
    trigger: Trigger10 | None = None


class Element9(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm20 | None = None
    accessibility_label: str | None = None
    workflow: Workflow10 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class DescriptionBlock2(BaseModel):
    type: str | None = None
    elements: List[Element9] | None = None
    block_id: str | None = None


class ListMetadata2(BaseModel):
    icon: str | None = None
    icon_url: str | None = None
    icon_team_id: str | None = None
    description: str | None = None
    is_trial: bool | None = None
    creation_source: CreationSource | None = None
    schema_: List[SchemaItem2] | None = Field(None, alias='schema')
    views: List[View2] | None = None
    integrations: List[str] | None = None
    description_blocks: List[DescriptionBlock2] | None = None


class Confirm23(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm22(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm23 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger11(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow11(BaseModel):
    trigger: Trigger11 | None = None


class Element10(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm22 | None = None
    accessibility_label: str | None = None
    workflow: Workflow11 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class Block2(BaseModel):
    type: str | None = None
    elements: List[Element10] | None = None
    block_id: str | None = None


class File2(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    editors: List[str] | None = None
    edit_timestamp: int | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription2 | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    url_static_preview: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    shares: Shares2 | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    quip_thread_id: str | None = None
    is_channel_space: bool | None = None
    linked_channel_id: str | None = None
    access: str | None = None
    teams_shared_with: List[Any] | None = None
    last_read: int | None = None
    title_blocks: List[TitleBlock3] | None = None
    private_channels_with_file_access_count: int | None = None
    private_file_with_access_count: int | None = None
    dm_mpdm_users_with_file_access: List[DmMpdmUsersWithFileAcces] | None = None
    org_or_workspace_access: str | None = None
    update_notification: int | None = None
    canvas_template_mode: str | None = None
    template_conversion_ts: int | None = None
    template_name: str | None = None
    template_title: str | None = None
    template_description: str | None = None
    template_icon: str | None = None
    team_pref_version_history_enabled: bool | None = None
    show_badge: bool | None = None
    favorites: List[Favorite] | None = None
    list_metadata: ListMetadata2 | None = None
    list_limits: ListLimits | None = None
    list_csv_download_url: str | None = None
    can_toggle_canvas_lock: bool | None = None
    is_restricted_sharing_enabled: bool | None = None
    canvas_printing_enabled: bool | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction] | None = None
    comments_count: int | None = None
    attachments: List[Any] | None = None
    blocks: List[Block2] | None = None


class Confirm25(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm24(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm25 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger12(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow12(BaseModel):
    trigger: Trigger12 | None = None


class Option4(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption4(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption5(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Filter5(BaseModel):
    include: List[Any] | None = None
    exclude_external_shared_channels: bool | None = None
    exclude_bot_users: bool | None = None


class Option5(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup2(BaseModel):
    label: Label | None = None
    options: List[Option5] | None = None


class Accessory1(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm24 | None = None
    accessibility_label: str | None = None
    workflow: Workflow12 | None = None
    options: List[Option4] | None = None
    initial_options: List[InitialOption4] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption5 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter5 | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None
    option_groups: List[OptionGroup2] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None


class Confirm27(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm26(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm27 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger13(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow13(BaseModel):
    trigger: Trigger13 | None = None


class Option6(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption6(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption7(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Option7(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup3(BaseModel):
    label: Label | None = None
    options: List[Option7] | None = None


class Element11(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm26 | None = None
    accessibility_label: str | None = None
    workflow: Workflow13 | None = None
    options: List[Option6] | None = None
    initial_options: List[InitialOption6] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption7 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter5 | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None
    option_groups: List[OptionGroup3] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None


class TitleBlock2(BaseModel):
    type: str | None = None
    elements: List[Element7] | None = None
    block_id: str | None = None
    call_id: str | None = None
    api_decoration_available: bool | None = None
    call: Call1 | None = None
    external_id: str | None = None
    source: str | None = None
    file_id: str | None = None
    file: File2 | None = None
    text: Text | None = None
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    is_animated: bool | None = None
    slack_file: SlackFile | None = None
    alt_text: str | None = None
    title: Title | None = None
    title_url: str | None = None
    description: Description | None = None
    video_url: str | None = None
    thumbnail_url: str | None = None
    author_name: str | None = None
    provider_name: str | None = None
    provider_icon_url: str | None = None
    function_trigger_id: str | None = None
    app_id: str | None = None
    is_workflow_app: bool | None = None
    sales_home_workflow_app_type: int | None = None
    app_collaborators: List[str] | None = None
    button_label: str | None = None
    bot_user_id: str | None = None
    url: str | None = None
    owning_team_id: str | None = None
    workflow_id: str | None = None
    developer_trace_id: str | None = None
    trigger_type: str | None = None
    trigger_subtype: str | None = None
    share_url: str | None = None
    fields: List[FieldModel] | None = None
    accessory: Accessory1 | None = None
    expand: bool | None = None
    label: Label | None = None
    element: Element11 | None = None
    dispatch_action: bool | None = None
    hint: Hint | None = None
    optional: bool | None = None


class AssistantAppThread(BaseModel):
    title: str | None = None
    title_blocks: List[TitleBlock2] | None = None
    first_user_thread_reply: str | None = None


class Message(BaseModel):
    bot_id: str | None = None
    type: str | None = None
    text: str | None = None
    user: str | None = None
    team: str | None = None
    bot_profile: BotProfile | None = None
    edited: Edited | None = None
    upload: bool | None = None
    display_as_bot: bool | None = None
    x_files: List[str] | None = None
    app_id: str | None = None
    metadata: Metadata | None = None
    room: Room | None = None
    files: List[File] | None = None
    blocks: List[Block] | None = None
    assistant_app_thread: AssistantAppThread | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class ChatUpdateResponse(BaseModel):
    ok: bool | None = None
    channel: str | None = None
    ts: str | None = None
    text: str | None = None
    message: Message | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    response_metadata: ResponseMetadata | None = None
