# generated by datamodel-codegen:
#   filename:  tmpjkiux03s.schema.json

from pydantic import BaseModel


class ChatPostEphemeralResponse(BaseModel):
    ok: bool | None = None
    message_ts: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
