# generated by datamodel-codegen

from pydantic import BaseModel


class ChatMeMessageResponse(BaseModel):
    channel: str | None = None
    ts: str | None = None
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
