# generated by datamodel-codegen:
#   filename:  tmpfciedo26.schema.json

from pydantic import BaseModel


class ChatStartStreamResponse(BaseModel):
    ok: bool | None = None
    ts: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    channel: str | None = None
    warning: str | None = None
