# generated by datamodel-codegen:
#   filename:  tmphltt3t6n.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    warnings: List[str] | None = None


class ChatUnfurlResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    callstack: str | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
