# generated by datamodel-codegen:
#   filename:  tmpye5rmrtg.schema.json

from pydantic import BaseModel
from typing import List


class ScheduledMessage(BaseModel):
    id: str | None = None
    channel_id: str | None = None
    post_at: int | None = None
    date_created: int | None = None
    text: str | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class ChatScheduledMessagesListResponse(BaseModel):
    ok: bool | None = None
    scheduled_messages: List[ScheduledMessage] | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
