# generated by datamodel-codegen:
#   filename:  tmp0ikuvyh_.schema.json

from pydantic import BaseModel


class ChatGetPermalinkResponse(BaseModel):
    ok: bool | None = None
    permalink: str | None = None
    channel: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
