# generated by datamodel-codegen:
#   filename:  tmp0vwzw9e3.schema.json

from pydantic import BaseModel


class ChatDeleteScheduledMessageResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
