# generated by datamodel-codegen:
#   filename:  tmpjc_7izbg.schema.json

from pydantic import BaseModel


class ChatStopStreamResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
