# generated by datamodel-codegen:
#   filename:  tmpflytb4as.schema.json

from pydantic import BaseModel


class ConversationsArchiveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
