# generated by datamodel-codegen:
#   filename:  tmplc0_vh65.schema.json

from pydantic import BaseModel


class ConversationsLeaveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
