# generated by datamodel-codegen:
#   filename:  tmp6ubdhefi.schema.json

from pydantic import BaseModel
from typing import List


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class ConversationsMembersResponse(BaseModel):
    ok: bool | None = None
    members: List[str] | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
