# generated by datamodel-codegen:
#   filename:  tmpsggyuy48.schema.json

from pydantic import BaseModel


class ConversationsRequestSharedInviteApproveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    invite_id: str | None = None
