# generated by datamodel-codegen:
#   filename:  tmpkv8i6igj.schema.json

from pydantic import BaseModel
from typing import List


class Icon(BaseModel):
    image_102: str | None = None
    image_132: str | None = None
    image_230: str | None = None
    image_34: str | None = None
    image_44: str | None = None
    image_68: str | None = None
    image_88: str | None = None
    image_default: bool | None = None
    image_original: str | None = None


class InvitingTeam(BaseModel):
    id: str | None = None
    name: str | None = None
    icon: Icon | None = None
    is_verified: bool | None = None
    domain: str | None = None
    date_created: int | None = None
    avatar_base_url: str | None = None
    requires_sponsorship: bool | None = None


class Profile(BaseModel):
    real_name: str | None = None
    display_name: str | None = None
    real_name_normalized: str | None = None
    display_name_normalized: str | None = None
    team: str | None = None
    avatar_hash: str | None = None
    email: str | None = None
    image_24: str | None = None
    image_32: str | None = None
    image_48: str | None = None
    image_72: str | None = None
    image_192: str | None = None
    image_512: str | None = None
    image_1024: str | None = None
    image_original: str | None = None
    is_custom_image: bool | None = None


class InvitingUser(BaseModel):
    id: str | None = None
    team_id: str | None = None
    name: str | None = None
    updated: int | None = None
    profile: Profile | None = None
    who_can_share_contact_card: str | None = None


class Invite1(BaseModel):
    id: str | None = None
    date_created: int | None = None
    date_invalid: int | None = None
    inviting_team: InvitingTeam | None = None
    inviting_user: InvitingUser | None = None
    link: str | None = None
    recipient_user_id: str | None = None
    recipient_email: str | None = None
    sig: str | None = None


class Channel(BaseModel):
    id: str | None = None
    is_im: bool | None = None
    is_private: bool | None = None
    name: str | None = None


class Icon1(BaseModel):
    image_102: str | None = None
    image_132: str | None = None
    image_230: str | None = None
    image_34: str | None = None
    image_44: str | None = None
    image_68: str | None = None
    image_88: str | None = None
    image_original: str | None = None
    image_default: bool | None = None


class AcceptingTeam(BaseModel):
    id: str | None = None
    name: str | None = None
    icon: Icon1 | None = None
    is_verified: bool | None = None
    domain: str | None = None
    date_created: int | None = None
    avatar_base_url: str | None = None
    requires_sponsorship: bool | None = None


class AcceptingUser(BaseModel):
    id: str | None = None
    team_id: str | None = None
    name: str | None = None
    updated: int | None = None
    profile: Profile | None = None
    who_can_share_contact_card: str | None = None


class ReviewingTeam(BaseModel):
    id: str | None = None
    name: str | None = None
    icon: Icon1 | None = None
    is_verified: bool | None = None
    domain: str | None = None
    date_created: int | None = None
    avatar_base_url: str | None = None
    requires_sponsorship: bool | None = None


class Review(BaseModel):
    type: str | None = None
    date_review: int | None = None
    reviewing_team: ReviewingTeam | None = None


class Acceptance(BaseModel):
    approval_status: str | None = None
    date_accepted: int | None = None
    date_invalid: int | None = None
    date_last_updated: int | None = None
    accepting_team: AcceptingTeam | None = None
    accepting_user: AcceptingUser | None = None
    reviews: List[Review] | None = None


class Icon3(BaseModel):
    image_default: bool | None = None
    image_34: str | None = None
    image_44: str | None = None
    image_68: str | None = None
    image_88: str | None = None
    image_102: str | None = None
    image_230: str | None = None
    image_132: str | None = None


class InvitingTeam1(BaseModel):
    id: str | None = None
    name: str | None = None
    icon: Icon3 | None = None
    avatar_base_url: str | None = None
    is_verified: bool | None = None
    domain: str | None = None
    date_created: int | None = None
    requires_sponsorship: bool | None = None


class Profile2(BaseModel):
    real_name: str | None = None
    display_name: str | None = None
    real_name_normalized: str | None = None
    display_name_normalized: str | None = None
    team: str | None = None
    avatar_hash: str | None = None
    email: str | None = None
    image_24: str | None = None
    image_32: str | None = None
    image_48: str | None = None
    image_72: str | None = None
    image_192: str | None = None
    image_512: str | None = None


class InvitingUser1(BaseModel):
    id: str | None = None
    team_id: str | None = None
    name: str | None = None
    updated: int | None = None
    who_can_share_contact_card: str | None = None
    profile: Profile2 | None = None


class Channel1(BaseModel):
    id: str | None = None
    is_private: bool | None = None
    name: str | None = None
    is_im: bool | None = None


class InvitePayload(BaseModel):
    invite_type: str | None = None
    is_sponsored: bool | None = None
    is_external_limited: bool | None = None
    channel: Channel1 | None = None


class Invite(BaseModel):
    direction: str | None = None
    status: str | None = None
    date_last_updated: int | None = None
    invite_type: str | None = None
    invite: Invite1 | None = None
    channel: Channel | None = None
    acceptances: List[Acceptance] | None = None
    id: str | None = None
    date_created: int | None = None
    date_invalid: int | None = None
    inviting_team: InvitingTeam1 | None = None
    inviting_user: InvitingUser1 | None = None
    invite_payload: InvitePayload | None = None
    sig: str | None = None
    link: str | None = None
    recipient_user_id: str | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None
    messages: List[str] | None = None


class ConversationsListConnectInvitesResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    arg: str | None = None
    invites: List[Invite] | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
