# generated by datamodel-codegen:
#   filename:  tmp8gcik39j.schema.json

from pydantic import BaseModel


class ConversationsExternalInvitePermissionsSetResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
