# generated by datamodel-codegen:
#   filename:  tmp5ozt1z19.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class ConversationsCanvasesCreateResponse(BaseModel):
    ok: bool | None = None
    canvas_id: str | None = None
    detail: str | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
