# generated by datamodel-codegen:
#   filename:  tmpqn07u0vs.schema.json

from pydantic import BaseModel


class ConversationsApproveSharedInviteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
