# generated by datamodel-codegen:
#   filename:  tmpmpfcxi6s.schema.json

from pydantic import BaseModel


class ConversationsUnarchiveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
