# generated by datamodel-codegen:
#   filename:  tmpk0bclhc7.schema.json

from pydantic import BaseModel
from typing import List


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Tab(BaseModel):
    type: str | None = None
    label: str | None = None
    id: str | None = None


class TabzItem(BaseModel):
    type: str | None = None


class Properties(BaseModel):
    is_dormant: bool | None = None
    tabs: List[Tab] | None = None
    tabz: List[TabzItem] | None = None
    has_slack_connect_invite_created: bool | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    is_channel: bool | None = None
    is_group: bool | None = None
    is_im: bool | None = None
    created: int | None = None
    is_archived: bool | None = None
    is_general: bool | None = None
    unlinked: int | None = None
    name_normalized: str | None = None
    is_shared: bool | None = None
    creator: str | None = None
    is_ext_shared: bool | None = None
    is_org_shared: bool | None = None
    shared_team_ids: List[str] | None = None
    pending_shared: List[str] | None = None
    pending_connected_team_ids: List[str] | None = None
    is_pending_ext_shared: bool | None = None
    is_member: bool | None = None
    is_private: bool | None = None
    is_mpim: bool | None = None
    last_read: str | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    previous_names: List[str] | None = None
    locale: str | None = None
    num_members: int | None = None
    is_read_only: bool | None = None
    is_thread_only: bool | None = None
    is_non_threadable: bool | None = None
    internal_team_ids: List[str] | None = None
    connected_team_ids: List[str] | None = None
    conversation_host_id: str | None = None
    is_moved: int | None = None
    is_global_shared: bool | None = None
    is_org_default: bool | None = None
    is_org_mandatory: bool | None = None
    connected_limited_team_ids: List[str] | None = None
    context_team_id: str | None = None
    updated: int | None = None
    properties: Properties | None = None


class ConversationsInfoResponse(BaseModel):
    ok: bool | None = None
    channel: Channel | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
