# generated by datamodel-codegen:
#   filename:  tmpjrqi8n2j.schema.json

from pydantic import BaseModel
from typing import List


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class PostingRestrictedTo(BaseModel):
    type: List[str] | None = None
    user: List[str] | None = None


class ThreadsRestrictedTo(BaseModel):
    type: List[str] | None = None
    user: List[str] | None = None


class Canvas(BaseModel):
    file_id: str | None = None
    is_empty: bool | None = None
    quip_thread_id: str | None = None
    is_migrated: bool | None = None


class Data(BaseModel):
    file_id: str | None = None
    shared_ts: str | None = None
    folder_bookmark_id: str | None = None
    mute_edit_updates: bool | None = None


class Tab(BaseModel):
    id: str | None = None
    label: str | None = None
    type: str | None = None
    data: Data | None = None
    is_disabled: bool | None = None


class TabzItem(BaseModel):
    id: str | None = None
    label: str | None = None
    type: str | None = None
    data: Data | None = None
    is_disabled: bool | None = None


class MeetingNotes(BaseModel):
    file_id: str | None = None


class ChannelWorkflow(BaseModel):
    workflow_trigger_id: str | None = None
    title: str | None = None


class Properties(BaseModel):
    posting_restricted_to: PostingRestrictedTo | None = None
    threads_restricted_to: ThreadsRestrictedTo | None = None
    canvas: Canvas | None = None
    tabs: List[Tab] | None = None
    tabz: List[TabzItem] | None = None
    meeting_notes: MeetingNotes | None = None
    is_dormant: bool | None = None
    use_case: str | None = None
    channel_workflows: List[ChannelWorkflow] | None = None
    has_slack_connect_invite_created: bool | None = None


class Channel(BaseModel):
    id: str | None = None
    created: int | None = None
    is_archived: bool | None = None
    is_im: bool | None = None
    is_org_shared: bool | None = None
    user: str | None = None
    is_user_deleted: bool | None = None
    priority: int | None = None
    name: str | None = None
    is_channel: bool | None = None
    is_group: bool | None = None
    is_mpim: bool | None = None
    is_private: bool | None = None
    is_general: bool | None = None
    unlinked: int | None = None
    name_normalized: str | None = None
    is_shared: bool | None = None
    is_pending_ext_shared: bool | None = None
    pending_shared: List[str] | None = None
    creator: str | None = None
    is_ext_shared: bool | None = None
    shared_team_ids: List[str] | None = None
    pending_connected_team_ids: List[str] | None = None
    is_member: bool | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    previous_names: List[str] | None = None
    num_members: int | None = None
    is_moved: int | None = None
    is_global_shared: bool | None = None
    is_org_default: bool | None = None
    is_org_mandatory: bool | None = None
    conversation_host_id: str | None = None
    internal_team_ids: List[str] | None = None
    context_team_id: str | None = None
    updated: int | None = None
    properties: Properties | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class ConversationsListResponse(BaseModel):
    ok: bool | None = None
    channels: List[Channel] | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    arg: str | None = None
    callstack: str | None = None
    warning: str | None = None
