# generated by datamodel-codegen:
#   filename:  tmprykt60cv.schema.json

from pydantic import BaseModel


class ConversationsDeclineSharedInviteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
