# generated by datamodel-codegen:
#   filename:  tmp70kua801.schema.json

from typing import Any, Dict
from pydantic import BaseModel


class ConversationsKickResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    errors: Dict[str, Any] | None = None
    warning: str | None = None
