# generated by datamodel-codegen:
#   filename:  tmpspmn2a_n.schema.json

from pydantic import BaseModel


class ConversationsRequestSharedInviteDenyResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    invite_id: str | None = None
