# generated by datamodel-codegen:
#   filename:  tmppb_glave.schema.json

from pydantic import BaseModel


class ConversationsMarkResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
