# generated by datamodel-codegen:
#   filename:  tmpd9lvzsij.schema.json

from pydantic import BaseModel


class DndSetSnoozeResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    snooze_enabled: bool | None = None
    snooze_endtime: int | None = None
    snooze_remaining: int | None = None
    snooze_is_indefinite: bool | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
