# generated by datamodel-codegen:
#   filename:  tmpbpfddyzr.schema.json

from pydantic import BaseModel, Field


class U00000000(BaseModel):
    dnd_enabled: bool | None = None
    next_dnd_start_ts: int | None = None
    next_dnd_end_ts: int | None = None


class U00000001(BaseModel):
    dnd_enabled: bool | None = None
    next_dnd_start_ts: int | None = None
    next_dnd_end_ts: int | None = None


class Users(BaseModel):
    u00000000: U00000000 | None = Field(None, alias='U00000000')
    u00000001: U00000001 | None = Field(None, alias='U00000001')


class DndTeamInfoResponse(BaseModel):
    ok: bool | None = None
    users: Users | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
