# generated by datamodel-codegen:
#   filename:  tmpg8tyc8sm.schema.json

from pydantic import BaseModel


class DndEndDndResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
