# generated by datamodel-codegen:
#   filename:  tmprzqssrnc.schema.json

from pydantic import BaseModel, Field
from typing import List


class Emoji(BaseModel):
    field_333: str | None = Field(None, alias='333')
    field_444: str | None = Field(None, alias='444')


class Category(BaseModel):
    name: str | None = None
    emoji_names: List[str] | None = None


class EmojiListResponse(BaseModel):
    ok: bool | None = None
    emoji: Emoji | None = None
    cache_ts: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    categories_version: str | None = None
    categories: List[Category] | None = None
    warning: str | None = None
