# generated by datamodel-codegen:
#   filename:  tmpnj7nxvaq.schema.json

from pydantic import BaseModel


class FilesDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
