# generated by datamodel-codegen:
#   filename:  tmpcr4yy2_s.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class FilesGetUploadURLExternalResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    upload_url: str | None = None
    file_id: str | None = None
    response_metadata: ResponseMetadata | None = None
    warning: str | None = None
