# generated by datamodel-codegen:
#   filename:  tmpk8b9nrd8.schema.json

from pydantic import BaseModel, Field
from typing import Any, List


class Preview(BaseModel):
    content: str | None = None
    has_more: bool | None = None


class Transcription(BaseModel):
    status: str | None = None
    locale: str | None = None
    preview: Preview | None = None


class C03E94MkuItem(BaseModel):
    share_user_id: str | None = None
    reply_users: List[str] | None = None
    reply_users_count: int | None = None
    reply_count: int | None = None
    ts: str | None = None
    thread_ts: str | None = None
    latest_reply: str | None = None
    channel_name: str | None = None
    team_id: str | None = None
    access: str | None = None
    source: str | None = None
    date_last_shared: int | None = None


class Public(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Private(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Shares(BaseModel):
    public: Public | None = None
    private: Private | None = None


class ToItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class FromItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class CcItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class Headers(BaseModel):
    date: str | None = None
    in_reply_to: str | None = None
    reply_to: str | None = None
    message_id: str | None = None


class MediaProgress(BaseModel):
    offset_ms: int | None = None
    max_offset_ms: int | None = None
    duration_ms: int | None = None
    media_watched: bool | None = None


class Saved(BaseModel):
    is_archived: bool | None = None
    date_completed: int | None = None
    date_due: int | None = None
    state: str | None = None


class Text(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm1(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Deny(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm1 | None = None
    deny: Deny | None = None
    style: str | None = None


class CustomizableInputParameter(BaseModel):
    name: str | None = None
    value: str | None = None


class Trigger(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow(BaseModel):
    trigger: Trigger | None = None


class SlackFile(BaseModel):
    id: str | None = None
    url: str | None = None


class Element(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm | None = None
    accessibility_label: str | None = None
    workflow: Workflow | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class TitleBlock(BaseModel):
    type: str | None = None
    elements: List[Element] | None = None
    block_id: str | None = None


class DmMpdmUsersWithFileAcces(BaseModel):
    user_id: str | None = None
    access: str | None = None


class Favorite(BaseModel):
    collection_id: str | None = None
    collection_name: str | None = None
    position: str | None = None


class CreationSource(BaseModel):
    type: str | None = None
    reference_id: str | None = None
    workflow_function_id: str | None = None


class Choice(BaseModel):
    value: str | None = None
    label: str | None = None
    color: str | None = None


class DefaultValueTyped(BaseModel):
    select: List[str] | None = None


class CanvasPlaceholderMappingItem(BaseModel):
    variable: str | None = None
    column: str | None = None


class Options(BaseModel):
    choices: List[Choice] | None = None
    format: str | None = None
    default_value: str | None = None
    default_value_typed: DefaultValueTyped | None = None
    emoji: str | None = None
    max: int | None = None
    precision: int | None = None
    show_member_name: bool | None = None
    date_format: str | None = None
    time_format: str | None = None
    currency_format: str | None = None
    emoji_team_id: str | None = None
    currency: str | None = None
    rounding: str | None = None
    mark_as_done_when_checked: bool | None = None
    for_assignment: bool | None = None
    notify_users: bool | None = None
    linked_to: List[str] | None = None
    canvas_id: str | None = None
    canvas_placeholder_mapping: List[CanvasPlaceholderMappingItem] | None = None


class SchemaItem(BaseModel):
    id: str | None = None
    name: str | None = None
    key: str | None = None
    type: str | None = None
    is_primary_column: bool | None = None
    options: Options | None = None


class Column(BaseModel):
    visible: bool | None = None
    key: str | None = None
    id: str | None = None
    position: str | None = None
    width: int | None = None


class Grouping(BaseModel):
    group_by: str | None = None
    group_by_column_id: str | None = None


class Filter(BaseModel):
    key: str | None = None
    operator: str | None = None
    values: List[str] | None = None
    typed_values: List[Any] | None = None
    column_id: str | None = None


class View(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None
    is_locked: bool | None = None
    position: str | None = None
    columns: List[Column] | None = None
    date_created: int | None = None
    created_by: str | None = None
    stick_column_left: bool | None = None
    is_all_items_view: bool | None = None
    default_view_key: str | None = None
    show_completed_items: bool | None = None
    grouping: Grouping | None = None
    filters: List[Filter] | None = None


class Confirm3(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm2(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm3 | None = None
    deny: Deny | None = None
    style: str | None = None


class Trigger1(BaseModel):
    url: str | None = None
    customizable_input_parameters: List[CustomizableInputParameter] | None = None


class Workflow1(BaseModel):
    trigger: Trigger1 | None = None


class Element1(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm2 | None = None
    accessibility_label: str | None = None
    workflow: Workflow1 | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    slack_file: SlackFile | None = None


class DescriptionBlock(BaseModel):
    type: str | None = None
    elements: List[Element1] | None = None
    block_id: str | None = None


class ListMetadata(BaseModel):
    icon: str | None = None
    icon_url: str | None = None
    icon_team_id: str | None = None
    description: str | None = None
    is_trial: bool | None = None
    creation_source: CreationSource | None = None
    schema_: List[SchemaItem] | None = Field(None, alias='schema')
    views: List[View] | None = None
    integrations: List[str] | None = None
    description_blocks: List[DescriptionBlock] | None = None


class ListLimits(BaseModel):
    over_row_maximum: bool | None = None
    row_count_limit: int | None = None
    row_count: int | None = None
    over_column_maximum: bool | None = None
    column_count: int | None = None
    column_count_limit: int | None = None
    over_view_maximum: bool | None = None
    view_count: int | None = None
    view_count_limit: int | None = None
    max_attachments_per_cell: int | None = None


class InitialComment(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    user: str | None = None
    comment: str | None = None
    channel: str | None = None
    is_intro: bool | None = None


class Reaction(BaseModel):
    name: str | None = None
    count: int | None = None
    users: List[str] | None = None
    url: str | None = None


class File(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    editors: List[str] | None = None
    edit_timestamp: int | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    url_static_preview: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    shares: Shares | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    quip_thread_id: str | None = None
    is_channel_space: bool | None = None
    linked_channel_id: str | None = None
    access: str | None = None
    teams_shared_with: List[Any] | None = None
    last_read: int | None = None
    title_blocks: List[TitleBlock] | None = None
    private_channels_with_file_access_count: int | None = None
    private_file_with_access_count: int | None = None
    dm_mpdm_users_with_file_access: List[DmMpdmUsersWithFileAcces] | None = None
    org_or_workspace_access: str | None = None
    update_notification: int | None = None
    canvas_template_mode: str | None = None
    template_conversion_ts: int | None = None
    template_name: str | None = None
    template_title: str | None = None
    template_description: str | None = None
    template_icon: str | None = None
    team_pref_version_history_enabled: bool | None = None
    show_badge: bool | None = None
    favorites: List[Favorite] | None = None
    list_metadata: ListMetadata | None = None
    list_limits: ListLimits | None = None
    list_csv_download_url: str | None = None
    can_toggle_canvas_lock: bool | None = None
    is_restricted_sharing_enabled: bool | None = None
    canvas_printing_enabled: bool | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction] | None = None
    comments_count: int | None = None


class FilesUploadResponse(BaseModel):
    ok: bool | None = None
    file: File | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
