# generated by datamodel-codegen:
#   filename:  tmpnnw6ya96.schema.json

from typing import List
from pydantic import BaseModel, Field


class C00000000Item(BaseModel):
    reply_users: List[str] | None = None
    reply_users_count: int | None = None
    reply_count: int | None = None
    ts: str | None = None
    channel_name: str | None = None
    team_id: str | None = None
    share_user_id: str | None = None
    thread_ts: str | None = None
    latest_reply: str | None = None
    source: str | None = None
    is_silent_share: bool | None = None


class C00000001Item(BaseModel):
    reply_users: List[str] | None = None
    reply_users_count: int | None = None
    reply_count: int | None = None
    ts: str | None = None
    channel_name: str | None = None
    team_id: str | None = None
    share_user_id: str | None = None
    thread_ts: str | None = None
    latest_reply: str | None = None
    source: str | None = None
    is_silent_share: bool | None = None


class Public(BaseModel):
    c00000000: List[C00000000Item] | None = Field(None, alias='C00000000')
    c00000001: List[C00000001Item] | None = Field(None, alias='C00000001')


class Shares(BaseModel):
    public: Public | None = None


class File(BaseModel):
    id: str | None = None
    title: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    editable: bool | None = None
    size: int | None = None
    mode: str | None = None
    is_external: bool | None = None
    external_type: str | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    username: str | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    lines: int | None = None
    lines_more: int | None = None
    preview_is_truncated: bool | None = None
    comments_count: int | None = None
    is_starred: bool | None = None
    shares: Shares | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    has_more_shares: bool | None = None
    has_rich_preview: bool | None = None
    file_access: str | None = None
    media_display_type: str | None = None
    thumb_64: str | None = None
    thumb_80: str | None = None
    thumb_360: str | None = None
    thumb_360_w: int | None = None
    thumb_360_h: int | None = None
    thumb_160: str | None = None
    original_w: int | None = None
    original_h: int | None = None
    thumb_tiny: str | None = None
    alt_txt: str | None = None
    thumb_480: str | None = None
    thumb_480_w: int | None = None
    thumb_480_h: int | None = None
    thumb_360_gif: str | None = None
    thumb_480_gif: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class FilesCompleteUploadExternalResponse(BaseModel):
    ok: bool | None = None
    files: List[File] | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    response_metadata: ResponseMetadata | None = None
    warning: str | None = None
