# generated by datamodel-codegen:
#   filename:  tmpzexlqqji.schema.json

from pydantic import BaseModel


class FilesCommentsDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
