# generated by datamodel-codegen:
#   filename:  tmpnaw54zts.schema.json

from pydantic import BaseModel


class FunctionsCompleteErrorResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
