# generated by datamodel-codegen:
#   filename:  tmpkh07kcs8.schema.json

from pydantic import BaseModel


class FunctionsCompleteSuccessResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
