# generated by datamodel-codegen:
#   filename:  tmpxsylfinl.schema.json

from pydantic import BaseModel
from typing import List


class Latest(BaseModel):
    type: str | None = None
    subtype: str | None = None
    ts: str | None = None
    user: str | None = None
    text: str | None = None
    topic: str | None = None


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Group(BaseModel):
    id: str | None = None
    name: str | None = None
    is_group: bool | None = None
    created: int | None = None
    creator: str | None = None
    is_archived: bool | None = None
    name_normalized: str | None = None
    is_mpim: bool | None = None
    is_open: bool | None = None
    last_read: str | None = None
    latest: Latest | None = None
    unread_count: int | None = None
    unread_count_display: int | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    priority: int | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    warnings: List[str] | None = None


class GroupsInviteResponse(BaseModel):
    ok: bool | None = None
    group: Group | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
