# generated by datamodel-codegen:
#   filename:  tmpaadjrbjn.schema.json

from pydantic import BaseModel


class GroupsCloseResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
