# generated by datamodel-codegen:
#   filename:  tmpa19jc7ky.schema.json

from pydantic import BaseModel
from typing import List


class Message(BaseModel):
    type: str | None = None
    subtype: str | None = None
    ts: str | None = None
    user: str | None = None
    text: str | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    warnings: List[str] | None = None


class GroupsHistoryResponse(BaseModel):
    ok: bool | None = None
    messages: List[Message] | None = None
    has_more: bool | None = None
    channel_actions_count: int | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
