# generated by datamodel-codegen:
#   filename:  tmpaxh75bmi.schema.json

from pydantic import BaseModel
from typing import List


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    is_group: bool | None = None
    created: int | None = None
    creator: str | None = None
    is_archived: bool | None = None
    name_normalized: str | None = None
    is_mpim: bool | None = None
    members: List[str] | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    warnings: List[str] | None = None


class GroupsRenameResponse(BaseModel):
    channel: Channel | None = None
    ok: bool | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
