# generated by datamodel-codegen:
#   filename:  tmpgxe77xe9.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    warnings: List[str] | None = None


class GroupsOpenResponse(BaseModel):
    ok: bool | None = None
    no_op: bool | None = None
    already_open: bool | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
