# generated by datamodel-codegen:
#   filename:  tmp7con6f6_.schema.json

from pydantic import BaseModel
from typing import List


class Im(BaseModel):
    id: str | None = None
    created: int | None = None
    is_archived: bool | None = None
    is_im: bool | None = None
    is_org_shared: bool | None = None
    user: str | None = None
    is_user_deleted: bool | None = None
    priority: int | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None
    messages: List[str] | None = None
    warnings: List[str] | None = None


class ImListResponse(BaseModel):
    ok: bool | None = None
    ims: List[Im] | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
