# generated by datamodel-codegen:
#   filename:  tmpntdl9h2c.schema.json

from pydantic import BaseModel
from typing import List


class Channel(BaseModel):
    id: str | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    warnings: List[str] | None = None


class ImOpenResponse(BaseModel):
    ok: bool | None = None
    channel: Channel | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
    no_op: bool | None = None
    already_open: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
