# generated by datamodel-codegen:
#   filename:  tmp7ovwajux.schema.json

from pydantic import BaseModel, Field
from typing import List


class UserIdMap(BaseModel):
    field_0: str | None = Field(None, alias='0')
    field_1: str | None = Field(None, alias='1')
    field_2: str | None = Field(None, alias='2')


class MigrationExchangeResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    team_id: str | None = None
    enterprise_id: str | None = None
    invalid_user_ids: List[str] | None = None
    user_id_map: UserIdMap | None = None
