# generated by datamodel-codegen:
#   filename:  tmp343rwkvm.schema.json

from pydantic import BaseModel
from typing import List


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Latest(BaseModel):
    bot_id: str | None = None
    type: str | None = None
    text: str | None = None
    user: str | None = None
    ts: str | None = None
    team: str | None = None
    bot_profile: BotProfile | None = None
    thread_ts: str | None = None
    parent_user_id: str | None = None


class Topic(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Purpose(BaseModel):
    value: str | None = None
    creator: str | None = None
    last_set: int | None = None


class Group(BaseModel):
    id: str | None = None
    name: str | None = None
    is_group: bool | None = None
    created: int | None = None
    creator: str | None = None
    is_archived: bool | None = None
    name_normalized: str | None = None
    is_mpim: bool | None = None
    is_open: bool | None = None
    last_read: str | None = None
    latest: Latest | None = None
    unread_count: int | None = None
    unread_count_display: int | None = None
    members: List[str] | None = None
    topic: Topic | None = None
    purpose: Purpose | None = None
    priority: int | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None
    warnings: List[str] | None = None


class MpimOpenResponse(BaseModel):
    ok: bool | None = None
    group: Group | None = None
    warning: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
