# generated by datamodel-codegen:
#   filename:  tmpclqylo7v.schema.json

from pydantic import BaseModel


class AuthedUser(BaseModel):
    id: str | None = None
    scope: str | None = None
    token_type: str | None = None
    access_token: str | None = None
    refresh_token: str | None = None
    expires_in: int | None = None


class Team(BaseModel):
    id: str | None = None
    name: str | None = None


class Enterprise(BaseModel):
    id: str | None = None
    name: str | None = None


class IncomingWebhook(BaseModel):
    url: str | None = None
    channel: str | None = None
    channel_id: str | None = None
    configuration_url: str | None = None


class OauthV2AccessResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    app_id: str | None = None
    authed_user: AuthedUser | None = None
    scope: str | None = None
    token_type: str | None = None
    access_token: str | None = None
    refresh_token: str | None = None
    expires_in: int | None = None
    bot_user_id: str | None = None
    team: Team | None = None
    enterprise: Enterprise | None = None
    is_enterprise_install: bool | None = None
    incoming_webhook: IncomingWebhook | None = None
