# generated by datamodel-codegen

from pydantic import BaseModel


class OauthTokenResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    req_method: str | None = None
    needed: str | None = None
    provided: str | None = None
