# generated by datamodel-codegen:
#   filename:  tmpcb8igg_0.schema.json

from pydantic import BaseModel


class OauthTokenResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    req_method: str | None = None
    needed: str | None = None
    provided: str | None = None
