# generated by datamodel-codegen:
#   filename:  tmphz4j6hv4.schema.json

from pydantic import BaseModel
from typing import List


class IncomingWebhook(BaseModel):
    url: str | None = None
    channel: str | None = None
    channel_id: str | None = None
    configuration_url: str | None = None


class Bot(BaseModel):
    bot_user_id: str | None = None
    bot_access_token: str | None = None


class AuthorizingUser(BaseModel):
    user_id: str | None = None
    app_home: str | None = None


class InstallerUser(BaseModel):
    user_id: str | None = None
    app_home: str | None = None


class Scopes(BaseModel):
    app_home: List[str] | None = None
    team: List[str] | None = None
    channel: List[str] | None = None
    group: List[str] | None = None
    mpim: List[str] | None = None
    im: List[str] | None = None
    user: List[str] | None = None


class OauthAccessResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    token_type: str | None = None
    access_token: str | None = None
    scope: str | None = None
    enterprise_id: str | None = None
    team_name: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    incoming_webhook: IncomingWebhook | None = None
    bot: Bot | None = None
    authorizing_user: AuthorizingUser | None = None
    installer_user: InstallerUser | None = None
    scopes: Scopes | None = None
