# generated by datamodel-codegen:
#   filename:  tmpi42ab07a.schema.json

from pydantic import BaseModel, Field


class OpenidConnectUserInfoResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    sub: str | None = None
    https___slack_com_user_id: str | None = Field(None, alias='https://slack.com/user_id')
    https___slack_com_team_id: str | None = Field(None, alias='https://slack.com/team_id')
    https___slack_com_enterprise_id: str | None = Field(None, alias='https://slack.com/enterprise_id')
    email: str | None = None
    email_verified: bool | None = None
    date_email_verified: int | None = None
    name: str | None = None
    picture: str | None = None
    given_name: str | None = None
    family_name: str | None = None
    locale: str | None = None
    https___slack_com_team_name: str | None = Field(None, alias='https://slack.com/team_name')
    https___slack_com_team_domain: str | None = Field(None, alias='https://slack.com/team_domain')
    https___slack_com_enterprise_name: str | None = Field(None, alias='https://slack.com/enterprise_name')
    https___slack_com_enterprise_domain: str | None = Field(None, alias='https://slack.com/enterprise_domain')
    https___slack_com_user_image_24: str | None = Field(None, alias='https://slack.com/user_image_24')
    https___slack_com_user_image_32: str | None = Field(None, alias='https://slack.com/user_image_32')
    https___slack_com_user_image_48: str | None = Field(None, alias='https://slack.com/user_image_48')
    https___slack_com_user_image_72: str | None = Field(None, alias='https://slack.com/user_image_72')
    https___slack_com_user_image_192: str | None = Field(None, alias='https://slack.com/user_image_192')
    https___slack_com_user_image_512: str | None = Field(None, alias='https://slack.com/user_image_512')
    https___slack_com_user_image_1024: str | None = Field(None, alias='https://slack.com/user_image_1024')
    https___slack_com_team_image_34: str | None = Field(None, alias='https://slack.com/team_image_34')
    https___slack_com_team_image_44: str | None = Field(None, alias='https://slack.com/team_image_44')
    https___slack_com_team_image_68: str | None = Field(None, alias='https://slack.com/team_image_68')
    https___slack_com_team_image_88: str | None = Field(None, alias='https://slack.com/team_image_88')
    https___slack_com_team_image_102: str | None = Field(None, alias='https://slack.com/team_image_102')
    https___slack_com_team_image_132: str | None = Field(None, alias='https://slack.com/team_image_132')
    https___slack_com_team_image_230: str | None = Field(None, alias='https://slack.com/team_image_230')
