# generated by datamodel-codegen:
#   filename:  tmpdfux3rjf.schema.json

from pydantic import BaseModel


class OpenidConnectTokenResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    access_token: str | None = None
    token_type: str | None = None
    id_token: str | None = None
    refresh_token: str | None = None
    expires_in: int | None = None
