# generated by datamodel-codegen:
#   filename:  tmpidpbk11d.schema.json

from pydantic import BaseModel


class PinsRemoveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
