# generated by datamodel-codegen:
#   filename:  tmpwcbf1efr.schema.json

from pydantic import BaseModel


class PinsAddResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
