# generated by datamodel-codegen:
#   filename:  tmpfji0syv0.schema.json

from pydantic import BaseModel


class ReactionsAddResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
