# generated by datamodel-codegen:
#   filename:  tmp36mq_tsl.schema.json

from pydantic import BaseModel


class ReactionsRemoveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
