# generated by datamodel-codegen:
#   filename:  tmp20l4e9s0.schema.json

from pydantic import BaseModel
from typing import List


class Reminder(BaseModel):
    id: str | None = None
    creator: str | None = None
    text: str | None = None
    user: str | None = None
    recurring: bool | None = None
    time: int | None = None
    complete_ts: int | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class RemindersAddResponse(BaseModel):
    ok: bool | None = None
    reminder: Reminder | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
