# generated by datamodel-codegen:
#   filename:  tmpfa022ofs.schema.json

from pydantic import BaseModel


class RemindersCompleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
