# generated by datamodel-codegen:
#   filename:  tmpeb_l171i.schema.json

from pydantic import BaseModel


class Reminder(BaseModel):
    id: str | None = None
    creator: str | None = None
    text: str | None = None
    user: str | None = None
    recurring: bool | None = None
    time: int | None = None
    complete_ts: int | None = None


class RemindersInfoResponse(BaseModel):
    ok: bool | None = None
    reminder: Reminder | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
