# generated by datamodel-codegen:
#   filename:  tmp9ygdujrc.schema.json

from typing import List
from pydantic import BaseModel


class Recurrence(BaseModel):
    frequency: str | None = None
    weekdays: List[str] | None = None


class Reminder(BaseModel):
    id: str | None = None
    creator: str | None = None
    text: str | None = None
    user: str | None = None
    recurring: bool | None = None
    time: int | None = None
    complete_ts: int | None = None
    channel: str | None = None
    recurrence: Recurrence | None = None


class RemindersListResponse(BaseModel):
    ok: bool | None = None
    reminders: List[Reminder] | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
