# generated by datamodel-codegen:
#   filename:  tmpbathq37w.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class SlackListsDownloadGetResponse(BaseModel):
    ok: bool | None = None
    status: str | None = None
    download_url: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
