# generated by datamodel-codegen:
#   filename:  tmpg8uywors.schema.json

from pydantic import BaseModel


class SlackListsItemsDeleteResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
