# generated by datamodel-codegen:
#   filename:  tmp0elgztz8.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class SlackListsDownloadStartResponse(BaseModel):
    ok: bool | None = None
    job_id: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
