# generated by datamodel-codegen:
#   filename:  tmpmuycvd4y.schema.json

from pydantic import BaseModel, Field
from typing import List


class Choice(BaseModel):
    value: str | None = None
    label: str | None = None
    color: str | None = None


class Options(BaseModel):
    format: str | None = None
    show_member_name: bool | None = None
    choices: List[Choice] | None = None


class SchemaItem(BaseModel):
    id: str | None = None
    name: str | None = None
    key: str | None = None
    type: str | None = None
    is_primary_column: bool | None = None
    options: Options | None = None


class Column(BaseModel):
    visible: bool | None = None
    key: str | None = None
    id: str | None = None
    position: str | None = None


class View(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None
    is_locked: bool | None = None
    position: str | None = None
    columns: List[Column] | None = None
    date_created: int | None = None
    created_by: str | None = None
    stick_column_left: bool | None = None
    is_all_items_view: bool | None = None
    default_view_key: str | None = None
    show_completed_items: bool | None = None


class Element1(BaseModel):
    type: str | None = None
    text: str | None = None


class Element(BaseModel):
    type: str | None = None
    elements: List[Element1] | None = None


class DescriptionBlock(BaseModel):
    type: str | None = None
    block_id: str | None = None
    elements: List[Element] | None = None


class Options1(BaseModel):
    format: str | None = None
    show_member_name: bool | None = None


class SubtaskSchemaItem(BaseModel):
    id: str | None = None
    name: str | None = None
    key: str | None = None
    type: str | None = None
    is_primary_column: bool | None = None
    options: Options1 | None = None


class CreationSource(BaseModel):
    type: str | None = None
    reference_id: str | None = None


class ListMetadata(BaseModel):
    schema_: List[SchemaItem] | None = Field(None, alias='schema')
    views: List[View] | None = None
    integrations: List[str] | None = None
    icon: str | None = None
    description: str | None = None
    description_blocks: List[DescriptionBlock] | None = None
    is_trial: bool | None = None
    subtask_schema: List[SubtaskSchemaItem] | None = None
    creation_source: CreationSource | None = None
    todo_mode: bool | None = None
    default_view: str | None = None


class ListLimits(BaseModel):
    over_row_maximum: bool | None = None
    row_count_limit: int | None = None
    row_count: int | None = None
    archived_row_count: int | None = None
    over_column_maximum: bool | None = None
    column_count: int | None = None
    column_count_limit: int | None = None
    over_view_maximum: bool | None = None
    view_count: int | None = None
    view_count_limit: int | None = None
    max_attachments_per_cell: int | None = None


class ListModel(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    editable: bool | None = None
    size: int | None = None
    mode: str | None = None
    is_external: bool | None = None
    external_type: str | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    username: str | None = None
    list_metadata: ListMetadata | None = None
    list_limits: ListLimits | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    last_editor: str | None = None
    list_csv_download_url: str | None = None
    updated: int | None = None
    is_starred: bool | None = None
    skipped_shares: bool | None = None
    teams_shared_with: List[str] | None = None
    is_restricted_sharing_enabled: bool | None = None
    has_rich_preview: bool | None = None
    file_access: str | None = None
    access: str | None = None
    org_or_workspace_access: str | None = None
    is_ai_suggested: bool | None = None


class FieldModel(BaseModel):
    key: str | None = None
    value: bool | None = None
    checkbox: bool | None = None
    column_id: str | None = None


class Record(BaseModel):
    id: str | None = None
    list_id: str | None = None
    date_created: int | None = None
    created_by: str | None = None
    updated_by: str | None = None
    fields: List[FieldModel] | None = None
    updated_timestamp: str | None = None
    is_subscribed: bool | None = None


class Subtask(BaseModel):
    id: str | None = None
    list_id: str | None = None
    date_created: int | None = None
    created_by: str | None = None
    updated_by: str | None = None
    fields: List[FieldModel] | None = None
    updated_timestamp: str | None = None
    is_subscribed: bool | None = None


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class SlackListsItemsInfoResponse(BaseModel):
    ok: bool | None = None
    list: ListModel | None = None
    record: Record | None = None
    subtasks: List[Subtask] | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
