# generated by datamodel-codegen:
#   filename:  tmp2cgu7mep.schema.json

from pydantic import BaseModel
from typing import List


class Element1(BaseModel):
    text: str | None = None
    type: str | None = None


class Element(BaseModel):
    type: str | None = None
    elements: List[Element1] | None = None


class RichTextItem(BaseModel):
    type: str | None = None
    block_id: str | None = None
    elements: List[Element] | None = None


class Field(BaseModel):
    key: str | None = None
    column_id: str | None = None
    value: bool | str | None = None
    rich_text: List[RichTextItem] | None = None
    checkbox: bool | None = None
    text: str | None = None


class Item(BaseModel):
    id: str | None = None
    list_id: str | None = None
    date_created: int | None = None
    created_by: str | None = None
    updated_by: str | None = None
    fields: List[Field] | None = None
    updated_timestamp: str | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None
    messages: List[str] | None = None


class SlackListsItemsListResponse(BaseModel):
    ok: bool | None = None
    items: List[Item] | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
