# generated by datamodel-codegen:
#   filename:  tmpcl94fon4.schema.json

from pydantic import BaseModel


class StarsRemoveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
