# generated by datamodel-codegen:
#   filename:  tmpigy5xtj0.schema.json

from pydantic import BaseModel


class StarsRemoveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
