# generated by datamodel-codegen:
#   filename:  tmpj3fg7yed.schema.json

from pydantic import BaseModel, Field
from typing import List


class FieldModel(BaseModel):
    title: str | None = None
    value: str | None = None
    short: bool | None = None


class Confirm(BaseModel):
    title: str | None = None
    text: str | None = None
    ok_text: str | None = None
    dismiss_text: str | None = None


class Option(BaseModel):
    text: str | None = None
    value: str | None = None


class SelectedOption(BaseModel):
    text: str | None = None
    value: str | None = None


class OptionGroup(BaseModel):
    text: str | None = None
    options: List[Option] | None = None


class Action(BaseModel):
    id: str | None = None
    name: str | None = None
    text: str | None = None
    style: str | None = None
    type: str | None = None
    value: str | None = None
    confirm: Confirm | None = None
    options: List[Option] | None = None
    selected_options: List[SelectedOption] | None = None
    data_source: str | None = None
    min_query_length: int | None = None
    option_groups: List[OptionGroup] | None = None
    url: str | None = None


class Text(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm2(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Deny(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm1(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm2 | None = None
    deny: Deny | None = None
    style: str | None = None


class Description(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Option2(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption1(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Placeholder(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Filter(BaseModel):
    include: List[str] | None = None
    exclude_external_shared_channels: bool | None = None
    exclude_bot_users: bool | None = None


class Label(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Option3(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup1(BaseModel):
    label: Label | None = None
    options: List[Option3] | None = None


class Style(BaseModel):
    bold: bool | None = None
    italic: bool | None = None
    strike: bool | None = None
    code: bool | None = None


class Element2(BaseModel):
    type: str | None = None
    range: str | None = None
    text: str | None = None
    style: Style | None = None
    channel_id: str | None = None
    value: str | None = None
    timestamp: int | None = None
    url: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    usergroup_id: str | None = None
    name: str | None = None
    skin_tone: int | None = None
    unicode: str | None = None


class Element1(BaseModel):
    type: str | None = None
    elements: List[Element2] | None = None
    style: str | None = None
    indent: int | None = None
    offset: int | None = None
    border: int | None = None


class Element(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm1 | None = None
    accessibility_label: str | None = None
    options: List[Option2] | None = None
    initial_options: List[InitialOption] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption1 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    option_groups: List[OptionGroup1] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None
    elements: List[Element1] | None = None
    indent: int | None = None
    offset: int | None = None
    border: int | None = None


class AppIconUrls(BaseModel):
    image_32: str | None = None
    image_36: str | None = None
    image_48: str | None = None
    image_64: str | None = None
    image_72: str | None = None
    image_96: str | None = None
    image_128: str | None = None
    image_192: str | None = None
    image_512: str | None = None
    image_1024: str | None = None
    image_original: str | None = None


class ActiveParticipant(BaseModel):
    slack_id: str | None = None
    external_id: str | None = None
    display_name: str | None = None
    avatar_url: str | None = None


class AllParticipant(BaseModel):
    slack_id: str | None = None
    external_id: str | None = None
    display_name: str | None = None
    avatar_url: str | None = None


class V1(BaseModel):
    id: str | None = None
    app_id: str | None = None
    app_icon_urls: AppIconUrls | None = None
    date_start: int | None = None
    active_participants: List[ActiveParticipant] | None = None
    all_participants: List[AllParticipant] | None = None
    display_id: str | None = None
    join_url: str | None = None
    desktop_app_join_url: str | None = None
    name: str | None = None
    created_by: str | None = None
    date_end: int | None = None
    channels: List[str] | None = None
    is_dm_call: bool | None = None
    was_rejected: bool | None = None
    was_missed: bool | None = None
    was_accepted: bool | None = None
    has_ended: bool | None = None


class Call(BaseModel):
    v1: V1 | None = None
    media_backend_type: str | None = None


class C03E94MkuItem(BaseModel):
    share_user_id: str | None = None
    reply_users: List[str] | None = None
    reply_users_count: int | None = None
    reply_count: int | None = None
    ts: str | None = None
    thread_ts: str | None = None
    latest_reply: str | None = None
    channel_name: str | None = None
    team_id: str | None = None


class Public(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Private(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Shares(BaseModel):
    public: Public | None = None
    private: Private | None = None


class ToItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class FromItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class CcItem(BaseModel):
    address: str | None = None
    name: str | None = None
    original: str | None = None


class Headers(BaseModel):
    date: str | None = None
    in_reply_to: str | None = None
    reply_to: str | None = None
    message_id: str | None = None


class MediaProgress(BaseModel):
    offset_ms: int | None = None
    max_offset_ms: int | None = None
    duration_ms: int | None = None


class Saved(BaseModel):
    is_archived: bool | None = None
    date_completed: int | None = None
    date_due: int | None = None
    state: str | None = None


class InitialComment(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    user: str | None = None
    comment: str | None = None
    channel: str | None = None
    is_intro: bool | None = None


class Reaction(BaseModel):
    name: str | None = None
    count: int | None = None
    users: List[str] | None = None
    url: str | None = None


class Transcription(BaseModel):
    status: str | None = None
    locale: str | None = None


class File(BaseModel):
    shares: Shares | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction] | None = None
    comments_count: int | None = None
    thumb_pdf_w: str | None = None
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None


class Field1(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None
    verbatim: bool | None = None


class Confirm4(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm3(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm4 | None = None
    deny: Deny | None = None
    style: str | None = None


class Option4(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption2(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption3(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Option5(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup2(BaseModel):
    label: Label | None = None
    options: List[Option5] | None = None


class Accessory(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm3 | None = None
    accessibility_label: str | None = None
    options: List[Option4] | None = None
    initial_options: List[InitialOption2] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption3 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    option_groups: List[OptionGroup2] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None


class Confirm6(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm5(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm6 | None = None
    deny: Deny | None = None
    style: str | None = None


class Option6(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption4(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption5(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Option7(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup3(BaseModel):
    label: Label | None = None
    options: List[Option7] | None = None


class Element3(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm5 | None = None
    accessibility_label: str | None = None
    options: List[Option6] | None = None
    initial_options: List[InitialOption4] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption5 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    option_groups: List[OptionGroup3] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None


class Hint(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Block(BaseModel):
    type: str | None = None
    elements: List[Element] | None = None
    block_id: str | None = None
    call_id: str | None = None
    api_decoration_available: bool | None = None
    call: Call | None = None
    external_id: str | None = None
    source: str | None = None
    file_id: str | None = None
    file: File | None = None
    text: Text | None = None
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    alt_text: str | None = None
    title: Title | None = None
    title_url: str | None = None
    description: Description | None = None
    video_url: str | None = None
    thumbnail_url: str | None = None
    author_name: str | None = None
    provider_name: str | None = None
    provider_icon_url: str | None = None
    function_trigger_id: str | None = None
    app_id: str | None = None
    is_workflow_app: bool | None = None
    app_collaborators: List[str] | None = None
    button_label: str | None = None
    bot_user_id: str | None = None
    url: str | None = None
    fields: List[Field1] | None = None
    accessory: Accessory | None = None
    label: Label | None = None
    element: Element3 | None = None
    dispatch_action: bool | None = None
    hint: Hint | None = None
    optional: bool | None = None


class Subtitle(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Preview(BaseModel):
    type: str | None = None
    can_remove: bool | None = None
    title: Title | None = None
    subtitle: Subtitle | None = None
    icon_url: str | None = None


class C00000000Item(BaseModel):
    share_user_id: str | None = None
    reply_users: List[str] | None = None
    reply_users_count: int | None = None
    reply_count: int | None = None
    ts: str | None = None
    thread_ts: str | None = None
    latest_reply: str | None = None
    channel_name: str | None = None
    team_id: str | None = None


class C00000001Item(BaseModel):
    share_user_id: str | None = None
    reply_users: List[str] | None = None
    reply_users_count: int | None = None
    reply_count: int | None = None
    ts: str | None = None
    thread_ts: str | None = None
    latest_reply: str | None = None
    channel_name: str | None = None
    team_id: str | None = None


class Public1(BaseModel):
    c00000000: List[C00000000Item] | None = Field(None, alias='C00000000')
    c00000001: List[C00000001Item] | None = Field(None, alias='C00000001')


class Private1(BaseModel):
    c00000000: List[C00000000Item] | None = Field(None, alias='C00000000')
    c00000001: List[C00000001Item] | None = Field(None, alias='C00000001')


class Shares1(BaseModel):
    public: Public1 | None = None
    private: Private1 | None = None


class File1(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    shares: Shares1 | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction] | None = None
    comments_count: int | None = None


class Metadata(BaseModel):
    thumb_64: bool | None = None
    thumb_80: bool | None = None
    thumb_160: bool | None = None
    original_w: int | None = None
    original_h: int | None = None
    thumb_360_w: int | None = None
    thumb_360_h: int | None = None
    format: str | None = None
    extension: str | None = None
    rotation: int | None = None
    thumb_tiny: str | None = None


class Attachment(BaseModel):
    msg_subtype: str | None = None
    fallback: str | None = None
    callback_id: str | None = None
    color: str | None = None
    pretext: str | None = None
    service_url: str | None = None
    service_name: str | None = None
    service_icon: str | None = None
    author_id: str | None = None
    author_name: str | None = None
    author_link: str | None = None
    author_icon: str | None = None
    from_url: str | None = None
    original_url: str | None = None
    author_subname: str | None = None
    channel_id: str | None = None
    channel_name: str | None = None
    channel_team: str | None = None
    id: int | None = None
    app_id: str | None = None
    bot_id: str | None = None
    indent: bool | None = None
    is_msg_unfurl: bool | None = None
    is_reply_unfurl: bool | None = None
    is_thread_root_unfurl: bool | None = None
    is_app_unfurl: bool | None = None
    app_unfurl_url: str | None = None
    title: str | None = None
    title_link: str | None = None
    text: str | None = None
    fields: List[FieldModel] | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    thumb_url: str | None = None
    thumb_width: int | None = None
    thumb_height: int | None = None
    video_url: str | None = None
    video_html: str | None = None
    video_html_width: int | None = None
    video_html_height: int | None = None
    footer: str | None = None
    footer_icon: str | None = None
    ts: str | None = None
    mrkdwn_in: List[str] | None = None
    actions: List[Action] | None = None
    blocks: List[Block] | None = None
    preview: Preview | None = None
    files: List[File1] | None = None
    filename: str | None = None
    size: int | None = None
    mimetype: str | None = None
    url: str | None = None
    metadata: Metadata | None = None


class Confirm8(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm7(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm8 | None = None
    deny: Deny | None = None
    style: str | None = None


class Option8(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption6(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption7(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Option9(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup4(BaseModel):
    label: Label | None = None
    options: List[Option9] | None = None


class Element6(BaseModel):
    type: str | None = None
    range: str | None = None
    text: str | None = None
    style: Style | None = None
    channel_id: str | None = None
    value: str | None = None
    timestamp: int | None = None
    url: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    usergroup_id: str | None = None
    name: str | None = None
    skin_tone: int | None = None
    unicode: str | None = None


class Element5(BaseModel):
    type: str | None = None
    elements: List[Element6] | None = None
    style: str | None = None
    indent: int | None = None
    offset: int | None = None
    border: int | None = None


class Element4(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm7 | None = None
    accessibility_label: str | None = None
    options: List[Option8] | None = None
    initial_options: List[InitialOption6] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption7 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    option_groups: List[OptionGroup4] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None
    elements: List[Element5] | None = None
    indent: int | None = None
    offset: int | None = None
    border: int | None = None


class V11(BaseModel):
    id: str | None = None
    app_id: str | None = None
    app_icon_urls: AppIconUrls | None = None
    date_start: int | None = None
    active_participants: List[ActiveParticipant] | None = None
    all_participants: List[AllParticipant] | None = None
    display_id: str | None = None
    join_url: str | None = None
    desktop_app_join_url: str | None = None
    name: str | None = None
    created_by: str | None = None
    date_end: int | None = None
    channels: List[str] | None = None
    is_dm_call: bool | None = None
    was_rejected: bool | None = None
    was_missed: bool | None = None
    was_accepted: bool | None = None
    has_ended: bool | None = None


class Call1(BaseModel):
    v1: V11 | None = None
    media_backend_type: str | None = None


class Public2(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Private2(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Shares2(BaseModel):
    public: Public2 | None = None
    private: Private2 | None = None


class File2(BaseModel):
    shares: Shares2 | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction] | None = None
    comments_count: int | None = None
    thumb_pdf_w: str | None = None
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None


class Confirm10(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm9(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm10 | None = None
    deny: Deny | None = None
    style: str | None = None


class Option10(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption8(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption9(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Option11(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup5(BaseModel):
    label: Label | None = None
    options: List[Option11] | None = None


class Accessory1(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm9 | None = None
    accessibility_label: str | None = None
    options: List[Option10] | None = None
    initial_options: List[InitialOption8] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption9 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    option_groups: List[OptionGroup5] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None


class Confirm12(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Confirm11(BaseModel):
    title: Title | None = None
    text: Text | None = None
    confirm: Confirm12 | None = None
    deny: Deny | None = None
    style: str | None = None


class Option12(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption10(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class InitialOption11(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class Option13(BaseModel):
    text: Text | None = None
    value: str | None = None
    description: Description | None = None
    url: str | None = None


class OptionGroup6(BaseModel):
    label: Label | None = None
    options: List[Option13] | None = None


class Element7(BaseModel):
    type: str | None = None
    text: Text | None = None
    action_id: str | None = None
    url: str | None = None
    value: str | None = None
    style: str | None = None
    confirm: Confirm11 | None = None
    accessibility_label: str | None = None
    options: List[Option12] | None = None
    initial_options: List[InitialOption10] | None = None
    focus_on_load: bool | None = None
    initial_option: InitialOption11 | None = None
    placeholder: Placeholder | None = None
    initial_channel: str | None = None
    response_url_enabled: bool | None = None
    initial_channels: List[str] | None = None
    max_selected_items: int | None = None
    initial_conversation: str | None = None
    default_to_current_conversation: bool | None = None
    filter: Filter | None = None
    initial_conversations: List[str] | None = None
    initial_date: str | None = None
    initial_time: str | None = None
    timezone: str | None = None
    initial_date_time: int | None = None
    min_query_length: int | None = None
    image_url: str | None = None
    alt_text: str | None = None
    fallback: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    option_groups: List[OptionGroup6] | None = None
    initial_user: str | None = None
    initial_users: List[str] | None = None


class Block1(BaseModel):
    type: str | None = None
    elements: List[Element4] | None = None
    block_id: str | None = None
    call_id: str | None = None
    api_decoration_available: bool | None = None
    call: Call1 | None = None
    external_id: str | None = None
    source: str | None = None
    file_id: str | None = None
    file: File2 | None = None
    text: Text | None = None
    fallback: str | None = None
    image_url: str | None = None
    image_width: int | None = None
    image_height: int | None = None
    image_bytes: int | None = None
    alt_text: str | None = None
    title: Title | None = None
    title_url: str | None = None
    description: Description | None = None
    video_url: str | None = None
    thumbnail_url: str | None = None
    author_name: str | None = None
    provider_name: str | None = None
    provider_icon_url: str | None = None
    function_trigger_id: str | None = None
    app_id: str | None = None
    is_workflow_app: bool | None = None
    app_collaborators: List[str] | None = None
    button_label: str | None = None
    bot_user_id: str | None = None
    url: str | None = None
    fields: List[Field1] | None = None
    accessory: Accessory1 | None = None
    label: Label | None = None
    element: Element7 | None = None
    dispatch_action: bool | None = None
    hint: Hint | None = None
    optional: bool | None = None


class Reaction3(BaseModel):
    name: str | None = None
    users: List[str] | None = None
    count: int | None = None


class Icons(BaseModel):
    image_36: str | None = None
    image_48: str | None = None
    image_72: str | None = None


class BotProfile(BaseModel):
    id: str | None = None
    deleted: bool | None = None
    name: str | None = None
    updated: int | None = None
    app_id: str | None = None
    icons: Icons | None = None
    team_id: str | None = None


class Edited(BaseModel):
    user: str | None = None
    ts: str | None = None


class Public3(BaseModel):
    c00000000: List[C00000000Item] | None = Field(None, alias='C00000000')
    c00000001: List[C00000001Item] | None = Field(None, alias='C00000001')


class Private3(BaseModel):
    c00000000: List[C00000000Item] | None = Field(None, alias='C00000000')
    c00000001: List[C00000001Item] | None = Field(None, alias='C00000001')


class Shares3(BaseModel):
    public: Public3 | None = None
    private: Private3 | None = None


class Reaction4(BaseModel):
    name: str | None = None
    count: int | None = None
    users: List[str] | None = None
    url: str | None = None


class File3(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    shares: Shares3 | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction4] | None = None
    comments_count: int | None = None


class Message(BaseModel):
    bot_id: str | None = None
    type: str | None = None
    text: str | None = None
    user: str | None = None
    ts: str | None = None
    team: str | None = None
    attachments: List[Attachment] | None = None
    is_starred: bool | None = None
    permalink: str | None = None
    subtype: str | None = None
    username: str | None = None
    blocks: List[Block1] | None = None
    client_msg_id: str | None = None
    thread_ts: str | None = None
    reply_count: int | None = None
    reply_users_count: int | None = None
    latest_reply: str | None = None
    reply_users: List[str] | None = None
    subscribed: bool | None = None
    last_read: str | None = None
    reactions: List[Reaction3] | None = None
    bot_profile: BotProfile | None = None
    edited: Edited | None = None
    files: List[File3] | None = None
    upload: bool | None = None
    display_as_bot: bool | None = None
    is_locked: bool | None = None
    inviter: str | None = None


class Public4(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Private4(BaseModel):
    c03_e94_mku: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU')
    c03_e94_mku_: List[C03E94MkuItem] | None = Field(None, alias='C03E94MKU_')


class Shares4(BaseModel):
    public: Public4 | None = None
    private: Private4 | None = None


class File4(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    name: str | None = None
    title: str | None = None
    subject: str | None = None
    mimetype: str | None = None
    filetype: str | None = None
    pretty_type: str | None = None
    user: str | None = None
    user_team: str | None = None
    source_team: str | None = None
    mode: str | None = None
    editable: bool | None = None
    non_owner_editable: bool | None = None
    editor: str | None = None
    last_editor: str | None = None
    updated: int | None = None
    file_access: str | None = None
    alt_txt: str | None = None
    subtype: str | None = None
    transcription: Transcription | None = None
    mp4: str | None = None
    mp4_low: str | None = None
    vtt: str | None = None
    hls: str | None = None
    hls_embed: str | None = None
    duration_ms: int | None = None
    thumb_video_w: int | None = None
    thumb_video_h: int | None = None
    original_attachment_count: int | None = None
    is_external: bool | None = None
    external_type: str | None = None
    external_id: str | None = None
    external_url: str | None = None
    username: str | None = None
    size: int | None = None
    url_private: str | None = None
    url_private_download: str | None = None
    app_id: str | None = None
    app_name: str | None = None
    thumb_64: str | None = None
    thumb_64_gif: str | None = None
    thumb_64_w: str | None = None
    thumb_64_h: str | None = None
    thumb_80: str | None = None
    thumb_80_gif: str | None = None
    thumb_80_w: str | None = None
    thumb_80_h: str | None = None
    thumb_160: str | None = None
    thumb_160_gif: str | None = None
    thumb_160_w: str | None = None
    thumb_160_h: str | None = None
    thumb_360: str | None = None
    thumb_360_gif: str | None = None
    thumb_360_w: str | None = None
    thumb_360_h: str | None = None
    thumb_480: str | None = None
    thumb_480_gif: str | None = None
    thumb_480_w: str | None = None
    thumb_480_h: str | None = None
    thumb_720: str | None = None
    thumb_720_gif: str | None = None
    thumb_720_w: str | None = None
    thumb_720_h: str | None = None
    thumb_800: str | None = None
    thumb_800_gif: str | None = None
    thumb_800_w: str | None = None
    thumb_800_h: str | None = None
    thumb_960: str | None = None
    thumb_960_gif: str | None = None
    thumb_960_w: str | None = None
    thumb_960_h: str | None = None
    thumb_1024: str | None = None
    thumb_1024_gif: str | None = None
    thumb_1024_w: str | None = None
    thumb_1024_h: str | None = None
    thumb_video: str | None = None
    thumb_gif: str | None = None
    thumb_pdf: str | None = None
    thumb_pdf_w: str | None = None
    thumb_pdf_h: str | None = None
    thumb_tiny: str | None = None
    converted_pdf: str | None = None
    image_exif_rotation: int | None = None
    original_w: str | None = None
    original_h: str | None = None
    deanimate: str | None = None
    deanimate_gif: str | None = None
    pjpeg: str | None = None
    permalink: str | None = None
    permalink_public: str | None = None
    edit_link: str | None = None
    has_rich_preview: bool | None = None
    media_display_type: str | None = None
    preview_is_truncated: bool | None = None
    preview: str | None = None
    preview_highlight: str | None = None
    plain_text: str | None = None
    preview_plain_text: str | None = None
    has_more: bool | None = None
    sent_to_self: bool | None = None
    lines: int | None = None
    lines_more: int | None = None
    is_public: bool | None = None
    public_url_shared: bool | None = None
    display_as_bot: bool | None = None
    channels: List[str] | None = None
    groups: List[str] | None = None
    ims: List[str] | None = None
    shares: Shares4 | None = None
    has_more_shares: bool | None = None
    to: List[ToItem] | None = None
    from_: List[FromItem] | None = Field(None, alias='from')
    cc: List[CcItem] | None = None
    channel_actions_ts: str | None = None
    channel_actions_count: int | None = None
    headers: Headers | None = None
    simplified_html: str | None = None
    media_progress: MediaProgress | None = None
    saved: Saved | None = None
    bot_id: str | None = None
    initial_comment: InitialComment | None = None
    num_stars: int | None = None
    is_starred: bool | None = None
    pinned_to: List[str] | None = None
    reactions: List[Reaction4] | None = None
    comments_count: int | None = None


class Comment(BaseModel):
    id: str | None = None
    created: int | None = None
    timestamp: int | None = None
    user: str | None = None
    is_intro: bool | None = None
    comment: str | None = None
    num_stars: int | None = None
    is_starred: bool | None = None


class Item(BaseModel):
    type: str | None = None
    channel: str | None = None
    date_create: int | None = None
    message: Message | None = None
    file: File4 | None = None
    comment: Comment | None = None


class Paging(BaseModel):
    per_page: int | None = None
    spill: int | None = None
    page: int | None = None
    total: int | None = None
    pages: int | None = None


class StarsListResponse(BaseModel):
    ok: bool | None = None
    items: List[Item] | None = None
    paging: Paging | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
