# generated by datamodel-codegen:
#   filename:  tmpxx84ij9n.schema.json

from pydantic import BaseModel


class StarsAddResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
