# generated by datamodel-codegen:
#   filename:  tmpaq5u15_t.schema.json

from pydantic import BaseModel
from typing import List


class Log(BaseModel):
    user_id: str | None = None
    user_name: str | None = None
    date: str | None = None
    change_type: str | None = None
    app_type: str | None = None
    app_id: str | None = None
    scope: str | None = None
    rss_feed: bool | None = None
    rss_feed_change_type: str | None = None
    rss_feed_title: str | None = None
    rss_feed_url: str | None = None
    service_id: int | None = None
    service_type: str | None = None
    channel: str | None = None
    reason: str | None = None
    resolution: str | None = None


class Paging(BaseModel):
    count: int | None = None
    total: int | None = None
    page: int | None = None
    pages: int | None = None


class TeamIntegrationLogsResponse(BaseModel):
    ok: bool | None = None
    logs: List[Log] | None = None
    paging: Paging | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
