# generated by datamodel-codegen:
#   filename:  tmpjwjxk_jq.schema.json

from pydantic import BaseModel
from typing import List


class Options(BaseModel):
    is_scim: bool | None = None
    is_protected: bool | None = None


class Permissions(BaseModel):
    api: List[str] | None = None
    ui: bool | None = None
    scim: bool | None = None


class Field(BaseModel):
    id: str | None = None
    ordering: int | None = None
    field_name: str | None = None
    label: str | None = None
    hint: str | None = None
    type: str | None = None
    is_hidden: bool | None = None
    options: Options | None = None
    section_id: str | None = None
    permissions: Permissions | None = None
    is_inverse: bool | None = None
    possible_values: List[str] | None = None


class Section(BaseModel):
    id: str | None = None
    team_id: str | None = None
    section_type: str | None = None
    label: str | None = None
    order: int | None = None
    is_hidden: bool | None = None


class Profile(BaseModel):
    fields: List[Field] | None = None
    sections: List[Section] | None = None


class TeamProfileGetResponse(BaseModel):
    ok: bool | None = None
    profile: Profile | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
