# generated by datamodel-codegen:
#   filename:  tmpxveimbmv.schema.json

from pydantic import BaseModel


class TeamPreferencesListResponse(BaseModel):
    ok: bool | None = None
    msg_edit_window_mins: int | None = None
    allow_message_deletion: bool | None = None
    display_real_names: bool | None = None
    disable_file_uploads: str | None = None
    who_can_post_general: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
