# generated by datamodel-codegen:
#   filename:  tmpue9oe2sb.schema.json

from pydantic import BaseModel, Field


class U00000000(BaseModel):
    billing_active: bool | None = None


class U00000001(BaseModel):
    billing_active: bool | None = None


class BillableInfo(BaseModel):
    u00000000: U00000000 | None = Field(None, alias='U00000000')
    u00000001: U00000001 | None = Field(None, alias='U00000001')


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class TeamBillableInfoResponse(BaseModel):
    ok: bool | None = None
    billable_info: BillableInfo | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    response_metadata: ResponseMetadata | None = None
    warning: str | None = None
