# generated by datamodel-codegen:
#   filename:  tmp4ks3tehw.schema.json

from pydantic import BaseModel


class TeamBillingInfoResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    plan: str | None = None
    warning: str | None = None
