# generated by datamodel-codegen:
#   filename:  tmppj6bm6ak.schema.json

from pydantic import BaseModel
from typing import List


class Login(BaseModel):
    user_id: str | None = None
    username: str | None = None
    date_first: int | None = None
    date_last: int | None = None
    count: int | None = None
    ip: str | None = None
    user_agent: str | None = None
    isp: str | None = None
    country: str | None = None
    region: str | None = None


class Paging(BaseModel):
    count: int | None = None
    total: int | None = None
    page: int | None = None
    pages: int | None = None
    warnings: List[str] | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class TeamAccessLogsResponse(BaseModel):
    ok: bool | None = None
    logins: List[Login] | None = None
    paging: Paging | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    response_metadata: ResponseMetadata | None = None
    warning: str | None = None
