# generated by datamodel-codegen

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class ToolingTokensRotateResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    response_metadata: ResponseMetadata | None = None
    needed: str | None = None
    provided: str | None = None
    token: str | None = None
    refresh_token: str | None = None
    team_id: str | None = None
    user_id: str | None = None
    iat: int | None = None
    exp: int | None = None
