# generated by datamodel-codegen:
#   filename:  tmp6bmrypec.schema.json

from pydantic import BaseModel


class User(BaseModel):
    name: str | None = None
    id: str | None = None
    email: str | None = None
    image_24: str | None = None
    image_32: str | None = None
    image_48: str | None = None
    image_72: str | None = None
    image_192: str | None = None
    image_512: str | None = None


class Team(BaseModel):
    name: str | None = None
    id: str | None = None


class UsersIdentityResponse(BaseModel):
    ok: bool | None = None
    warning: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    user: User | None = None
    team: Team | None = None
