# generated by datamodel-codegen:
#   filename:  tmpfh44sopa.schema.json

from typing import List
from pydantic import BaseModel


class Prefs(BaseModel):
    channels: List[str] | None = None
    groups: List[str] | None = None


class Usergroup(BaseModel):
    id: str | None = None
    team_id: str | None = None
    is_usergroup: bool | None = None
    is_subteam: bool | None = None
    name: str | None = None
    description: str | None = None
    handle: str | None = None
    is_external: bool | None = None
    date_create: int | None = None
    date_update: int | None = None
    date_delete: int | None = None
    auto_provision: bool | None = None
    enterprise_subteam_id: str | None = None
    created_by: str | None = None
    updated_by: str | None = None
    prefs: Prefs | None = None
    channel_count: int | None = None
    users: List[str] | None = None
    user_count: int | None = None
    is_section: bool | None = None
    is_idp_group: bool | None = None
    is_visible: bool | None = None
    is_editing_restricted: bool | None = None
    is_membership_locked: bool | None = None
    is_org_level: bool | None = None
    deleted_by: str | None = None


class UsergroupsListResponse(BaseModel):
    ok: bool | None = None
    usergroups: List[Usergroup] | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
