# generated by datamodel-codegen:
#   filename:  tmpzzyf_hkn.schema.json

from pydantic import BaseModel


class UsersSetPresenceResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
