# generated by datamodel-codegen:
#   filename:  tmpwxe96iyb.schema.json

from pydantic import BaseModel, Field
from typing import List


class X00000000(BaseModel):
    value: str | None = None
    alt: str | None = None


class X00000001(BaseModel):
    value: str | None = None
    alt: str | None = None


class Fields(BaseModel):
    x00000000: X00000000 | None = Field(None, alias='X00000000')
    x00000001: X00000001 | None = Field(None, alias='X00000001')


class StatusEmojiDisplayInfoItem(BaseModel):
    emoji_name: str | None = None
    display_alias: str | None = None
    display_url: str | None = None
    unicode: str | None = None


class Profile(BaseModel):
    title: str | None = None
    phone: str | None = None
    skype: str | None = None
    real_name: str | None = None
    real_name_normalized: str | None = None
    display_name: str | None = None
    display_name_normalized: str | None = None
    fields: Fields | None = None
    status_text: str | None = None
    status_emoji: str | None = None
    status_expiration: int | None = None
    avatar_hash: str | None = None
    image_original: str | None = None
    is_custom_image: bool | None = None
    email: str | None = None
    first_name: str | None = None
    last_name: str | None = None
    image_24: str | None = None
    image_32: str | None = None
    image_48: str | None = None
    image_72: str | None = None
    image_192: str | None = None
    image_512: str | None = None
    image_1024: str | None = None
    status_text_canonical: str | None = None
    status_emoji_url: str | None = None
    pronouns: str | None = None
    huddle_state: str | None = None
    huddle_state_expiration_ts: int | None = None
    status_emoji_display_info: List[StatusEmojiDisplayInfoItem] | None = None
    start_date: str | None = None
    status_clear_on_focus_end: bool | None = None


class UsersProfileSetResponse(BaseModel):
    profile: Profile | None = None
    ok: bool | None = None
    username: str | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
