# generated by datamodel-codegen:
#   filename:  tmpwds8pzzy.schema.json

from typing import List
from pydantic import BaseModel


class UsergroupsUsersListResponse(BaseModel):
    ok: bool | None = None
    users: List[str] | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
