# generated by datamodel-codegen:
#   filename:  tmp9kfchhws.schema.json

from typing import List
from pydantic import BaseModel


class ResponseMetadata(BaseModel):
    messages: List[str] | None = None


class UsersDiscoverableContactsLookupResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    response_metadata: ResponseMetadata | None = None
    is_discoverable: bool | None = None
