# generated by datamodel-codegen:
#   filename:  tmpv5ai4tpe.schema.json

from pydantic import BaseModel
from typing import Any, Dict, List


class StatusEmojiDisplayInfoItem(BaseModel):
    emoji_name: str | None = None
    display_alias: str | None = None
    display_url: str | None = None
    unicode: str | None = None


class Profile(BaseModel):
    title: str | None = None
    phone: str | None = None
    skype: str | None = None
    real_name: str | None = None
    real_name_normalized: str | None = None
    display_name: str | None = None
    display_name_normalized: str | None = None
    status_text: str | None = None
    status_emoji: str | None = None
    status_expiration: int | None = None
    avatar_hash: str | None = None
    image_original: str | None = None
    is_custom_image: bool | None = None
    email: str | None = None
    pronouns: str | None = None
    first_name: str | None = None
    last_name: str | None = None
    image_24: str | None = None
    image_32: str | None = None
    image_48: str | None = None
    image_72: str | None = None
    image_192: str | None = None
    image_512: str | None = None
    image_1024: str | None = None
    status_text_canonical: str | None = None
    team: str | None = None
    api_app_id: str | None = None
    bot_id: str | None = None
    always_active: bool | None = None
    guest_invited_by: str | None = None
    guest_expiration_ts: int | None = None
    huddle_state: str | None = None
    huddle_state_expiration_ts: int | None = None
    fields: Dict[str, Any] | None = None
    status_emoji_display_info: List[StatusEmojiDisplayInfoItem] | None = None
    start_date: str | None = None


class EnterpriseUser(BaseModel):
    id: str | None = None
    enterprise_id: str | None = None
    enterprise_name: str | None = None
    is_admin: bool | None = None
    is_owner: bool | None = None
    teams: List[str] | None = None
    is_primary_owner: bool | None = None


class Member(BaseModel):
    id: str | None = None
    team_id: str | None = None
    name: str | None = None
    deleted: bool | None = None
    color: str | None = None
    real_name: str | None = None
    tz: str | None = None
    tz_label: str | None = None
    tz_offset: int | None = None
    profile: Profile | None = None
    is_admin: bool | None = None
    is_owner: bool | None = None
    is_primary_owner: bool | None = None
    is_restricted: bool | None = None
    is_ultra_restricted: bool | None = None
    is_bot: bool | None = None
    is_app_user: bool | None = None
    updated: int | None = None
    is_email_confirmed: bool | None = None
    who_can_share_contact_card: str | None = None
    is_workflow_bot: bool | None = None
    has_2fa: bool | None = None
    locale: str | None = None
    enterprise_user: EnterpriseUser | None = None
    is_invited_user: bool | None = None
    is_connector_bot: bool | None = None
    two_factor_type: str | None = None


class ResponseMetadata(BaseModel):
    next_cursor: str | None = None


class UsersListResponse(BaseModel):
    ok: bool | None = None
    members: List[Member] | None = None
    cache_ts: int | None = None
    offset: str | None = None
    response_metadata: ResponseMetadata | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    arg: str | None = None
    warning: str | None = None
