# generated by datamodel-codegen:
#   filename:  tmps63lq7jb.schema.json

from typing import List
from pydantic import BaseModel


class WorkflowsFeaturedListResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
    invalid_channel_ids: List[str] | None = None
