# generated by datamodel-codegen:
#   filename:  tmp8ev89c7j.schema.json

from pydantic import BaseModel


class WorkflowsFeaturedAddResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
