# generated by datamodel-codegen:
#   filename:  tmp072o3klx.schema.json

from pydantic import BaseModel


class WorkflowsFeaturedRemoveResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
