# generated by datamodel-codegen:
#   filename:  tmp60sce79t.schema.json

from pydantic import BaseModel


class WorkflowsStepCompletedResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
