# generated by datamodel-codegen:
#   filename:  tmpcik8ozzo.schema.json

from pydantic import BaseModel


class WorkflowsStepFailedResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
