# generated by datamodel-codegen:
#   filename:  tmp40u0bc6z.schema.json

from pydantic import BaseModel


class WorkflowsUpdateStepResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
