# generated by datamodel-codegen:
#   filename:  tmp00y21uwy.schema.json

from pydantic import BaseModel


class WorkflowsFeaturedSetResponse(BaseModel):
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
