# generated by datamodel-codegen:
#   filename:  tmpmb8k__2t.schema.json

from pydantic import BaseModel


class SlashCommandPayload(BaseModel):
    token: str | None = None
    api_app_id: str | None = None
    team_id: str | None = None
    team_domain: str | None = None
    enterprise_id: str | None = None
    enterprise_name: str | None = None
    channel_id: str | None = None
    channel_name: str | None = None
    user_id: str | None = None
    user_name: str | None = None
    command: str | None = None
    text: str | None = None
    response_url: str | None = None
    trigger_id: str | None = None
    is_enterprise_install: bool | None = None
