# generated by datamodel-codegen:
#   filename:  tmpymwwu7m6.schema.json

from typing import List
from pydantic import BaseModel, Field


class Actions(BaseModel):
    workspace_or_org: List[str] | None = None
    user: List[str] | None = None
    file: List[str] | None = None
    channel: List[str] | None = None
    app: List[str] | None = None
    workflow_builder: List[str] | None = None
    message: List[str] | None = None
    barrier: List[str] | None = None
    huddle: List[str] | None = None
    anomaly: List[str] | None = None
    slack_cli: List[str] | None = None
    subteam: List[str] | None = None
    role: List[str] | None = None
    account_type_role: List[str] | None = None
    app_approval_automation_rule: List[str] | None = None
    workflow_v2: List[str] | None = None
    canvas: List[str] | None = None
    function: List[str] | None = None
    sales_elevate: List[str] | None = None
    native_dlp: List[str] | None = None
    template: List[str] | None = None
    list_: List[str] | None = Field(None, alias='list')
    slack_first_crm: List[str] | None = None
    legal_hold: List[str] | None = None


class ActionsResponse(BaseModel):
    actions: Actions | None = None
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
