# generated by datamodel-codegen:
#   filename:  tmphr6y00et.schema.json

from pydantic import BaseModel
from typing import List


class Workspace(BaseModel):
    id: str | None = None
    name: str | None = None
    domain: str | None = None


class Enterprise(BaseModel):
    id: str | None = None
    name: str | None = None
    domain: str | None = None


class User(BaseModel):
    id: str | None = None
    name: str | None = None
    email: str | None = None
    team: str | None = None
    account_type: str | None = None


class File(BaseModel):
    id: str | None = None
    name: str | None = None
    filetype: str | None = None
    title: str | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None
    privacy: str | None = None
    is_shared: str | None = None
    is_org_shared: str | None = None
    teams_shared_with: str | None = None


class App(BaseModel):
    id: str | None = None
    name: str | None = None
    is_distributed: str | None = None
    is_directory_approved: str | None = None
    is_workflow_app: str | None = None
    scopes: str | None = None
    app_id: str | None = None
    distribution_type: str | None = None
    user_ids: str | None = None


class Workflow(BaseModel):
    id: str | None = None
    name: str | None = None


class Barrier(BaseModel):
    id: str | None = None
    primary_usergroup: str | None = None
    barriered_from_usergroup: str | None = None


class Message(BaseModel):
    team: str | None = None
    channel: str | None = None
    timestamp: str | None = None


class Usergroup(BaseModel):
    id: str | None = None
    name: str | None = None


class Role(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None


class AccountTypeRole(BaseModel):
    id: str | None = None
    name: str | None = None


class Canvas(BaseModel):
    id: str | None = None
    filetype: str | None = None
    title: str | None = None


class WorkflowV2(BaseModel):
    id: str | None = None
    app_id: str | None = None
    date_updated: str | None = None
    callback_id: str | None = None
    name: str | None = None
    updated_by: str | None = None
    step_configuration: str | None = None
    template_id: str | None = None
    suspicious_keywords: str | None = None
    trigger_name: str | None = None
    trigger_channels: str | None = None
    trigger_configuration: str | None = None


class Template(BaseModel):
    id: str | None = None
    template_name: str | None = None


class LegalHoldPolicy(BaseModel):
    id: str | None = None
    name: str | None = None


class Schema(BaseModel):
    type: str | None = None
    workspace: Workspace | None = None
    enterprise: Enterprise | None = None
    user: User | None = None
    file: File | None = None
    channel: Channel | None = None
    app: App | None = None
    workflow: Workflow | None = None
    barrier: Barrier | None = None
    message: Message | None = None
    usergroup: Usergroup | None = None
    role: Role | None = None
    account_type_role: AccountTypeRole | None = None
    canvas: Canvas | None = None
    workflow_v2: WorkflowV2 | None = None
    template: Template | None = None
    legal_hold_policy: LegalHoldPolicy | None = None


class SchemasResponse(BaseModel):
    schemas: List[Schema] | None = None
    ok: bool | None = None
    error: str | None = None
    needed: str | None = None
    provided: str | None = None
    warning: str | None = None
