# generated by datamodel-codegen:
#   filename:  tmpd5qpn7ap.schema.json

from pydantic import BaseModel
from typing import Any, Dict


class Enterprise(BaseModel):
    id: str | None = None
    name: str | None = None


class Team(BaseModel):
    id: str | None = None
    domain: str | None = None
    enterprise_id: str | None = None
    enterprise_name: str | None = None


class User(BaseModel):
    id: str | None = None
    username: str | None = None
    name: str | None = None
    team_id: str | None = None


class Title(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Submit(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class Close(BaseModel):
    type: str | None = None
    text: str | None = None
    emoji: bool | None = None


class View(BaseModel):
    id: str | None = None
    team_id: str | None = None
    type: str | None = None
    title: Title | None = None
    submit: Submit | None = None
    close: Close | None = None
    private_metadata: str | None = None
    callback_id: str | None = None
    external_id: str | None = None
    state: Dict[str, Any] | None = None
    hash: str | None = None
    clear_on_close: bool | None = None
    notify_on_close: bool | None = None
    submit_disabled: bool | None = None
    root_view_id: str | None = None
    previous_view_id: str | None = None
    app_id: str | None = None
    app_installed_team_id: str | None = None
    bot_id: str | None = None


class Function(BaseModel):
    callback_id: str | None = None


class FunctionData(BaseModel):
    execution_id: str | None = None
    function: Function | None = None


class Interactor(BaseModel):
    id: str | None = None
    secret: str | None = None


class Interactivity(BaseModel):
    interactivity_pointer: str | None = None
    interactor: Interactor | None = None


class ViewClosedPayload(BaseModel):
    type: str | None = None
    enterprise: Enterprise | None = None
    team: Team | None = None
    user: User | None = None
    api_app_id: str | None = None
    token: str | None = None
    view: View | None = None
    is_enterprise_install: bool | None = None
    is_cleared: bool | None = None
    bot_access_token: str | None = None
    function_data: FunctionData | None = None
    interactivity: Interactivity | None = None
