# generated by datamodel-codegen:
#   filename:  tmp5dz86gct.schema.json

from pydantic import BaseModel
from typing import Any, Dict


class Enterprise(BaseModel):
    id: str | None = None
    name: str | None = None


class Team(BaseModel):
    id: str | None = None
    domain: str | None = None
    enterprise_id: str | None = None
    enterprise_name: str | None = None


class User(BaseModel):
    id: str | None = None
    name: str | None = None
    team_id: str | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None


class DialogSubmissionPayload(BaseModel):
    type: str | None = None
    callback_id: str | None = None
    submission: Dict[str, Any] | None = None
    state: str | None = None
    enterprise: Enterprise | None = None
    team: Team | None = None
    user: User | None = None
    channel: Channel | None = None
    action_ts: str | None = None
    token: str | None = None
    response_url: str | None = None
    is_enterprise_install: bool | None = None
