# generated by datamodel-codegen:
#   filename:  tmpql4rx28e.schema.json

from pydantic import BaseModel
from typing import List


class Action(BaseModel):
    name: str | None = None
    type: str | None = None
    value: str | None = None


class Enterprise(BaseModel):
    id: str | None = None
    name: str | None = None


class Team(BaseModel):
    id: str | None = None
    domain: str | None = None
    enterprise_id: str | None = None
    enterprise_name: str | None = None


class Channel(BaseModel):
    id: str | None = None
    name: str | None = None


class User(BaseModel):
    id: str | None = None
    name: str | None = None
    team_id: str | None = None


class Action1(BaseModel):
    name: str | None = None
    text: str | None = None
    type: str | None = None
    value: str | None = None


class Field(BaseModel):
    title: str | None = None
    value: str | None = None
    short: bool | None = None


class Attachment(BaseModel):
    id: int | None = None
    callback_id: str | None = None
    title: str | None = None
    text: str | None = None
    fallback: str | None = None
    color: str | None = None
    attachment_type: str | None = None
    actions: List[Action1] | None = None
    fields: List[Field] | None = None
    author_name: str | None = None
    author_icon: str | None = None
    image_url: str | None = None


class OriginalMessage(BaseModel):
    bot_id: str | None = None
    type: str | None = None
    text: str | None = None
    user: str | None = None
    username: str | None = None
    ts: str | None = None
    attachments: List[Attachment] | None = None
    subtype: str | None = None
    thread_ts: str | None = None
    parent_user_id: str | None = None


class AttachmentActionPayload(BaseModel):
    type: str | None = None
    actions: List[Action] | None = None
    callback_id: str | None = None
    enterprise: Enterprise | None = None
    team: Team | None = None
    channel: Channel | None = None
    user: User | None = None
    action_ts: str | None = None
    message_ts: str | None = None
    attachment_id: str | None = None
    token: str | None = None
    is_app_unfurl: bool | None = None
    original_message: OriginalMessage | None = None
    response_url: str | None = None
    trigger_id: str | None = None
    is_enterprise_install: bool | None = None
