# generated by datamodel-codegen:
#   filename:  tmp4_9yv363.schema.json

from pydantic import BaseModel, Field
from typing import List


class Member(BaseModel):
    value: str | None = None
    display: str | None = None


class Meta(BaseModel):
    created: str | None = None
    location: str | None = None


class GroupResponse(BaseModel):
    schemas: List[str] | None = None
    id: str | None = None
    display_name: str | None = Field(None, alias='displayName')
    members: List[Member] | None = None
    meta: Meta | None = None
