# generated by datamodel-codegen:
#   filename:  tmp2jkpnytd.schema.json

from pydantic import BaseModel, Field
from typing import List


class AuthenticationScheme(BaseModel):
    type: str | None = None
    name: str | None = None
    description: str | None = None
    spec_url: str | None = Field(None, alias='specUrl')
    primary: bool | None = None


class Patch(BaseModel):
    supported: bool | None = None


class Bulk(BaseModel):
    supported: bool | None = None
    max_operations: int | None = Field(None, alias='maxOperations')
    max_payload_size: int | None = Field(None, alias='maxPayloadSize')


class Filter(BaseModel):
    supported: bool | None = None
    max_results: int | None = Field(None, alias='maxResults')


class ChangePassword(BaseModel):
    supported: bool | None = None


class Sort(BaseModel):
    supported: bool | None = None


class Etag(BaseModel):
    supported: bool | None = None


class XmlDataFormat(BaseModel):
    supported: bool | None = None


class ServiceProviderConfigsResponse(BaseModel):
    authentication_schemes: List[AuthenticationScheme] | None = Field(None, alias='authenticationSchemes')
    patch: Patch | None = None
    bulk: Bulk | None = None
    filter: Filter | None = None
    change_password: ChangePassword | None = Field(None, alias='changePassword')
    sort: Sort | None = None
    etag: Etag | None = None
    xml_data_format: XmlDataFormat | None = Field(None, alias='xmlDataFormat')
